"""DriveThruRPG-ready PDF export (V4.4 Phase E).

GET /api/campaigns/{cid}/export.pdf — streams a system-branded PDF.

Layout decisions (per user):
  * Chapter 1 = Session 0 (Prologue) + Session 1 + Session 2.
  * Subsequent chapters group sessions in pairs (Ch2 = S3+S4, Ch3 = S5+S6,
    Ch4 = S7+S8, …).
  * Per-system visual identity — full styling, not just accent colours.
  * Logos at top of cover when available on disk.
  * Legal footer per system, sourced from /app/memory/LEGAL_COMPLIANCE.md.

Style profiles ship initially for BESM 4E and Anime 5E. Other systems
fall back to a neutral DriveThruRPG-friendly profile so a GM never gets
a 500 — they just get a less branded PDF until we author that system.

We sniff each session's `chat_logs` + `recaps` + the GM-finalized
`session_record` chronicle (preferred when present) to assemble chapter
prose. Player journals append as colour quotations.
"""
from __future__ import annotations

import io
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from core.db import db
from core.security import get_current_user

router = APIRouter(prefix="/api", tags=["pdf"])

# ─────────────────────── Style profiles ───────────────────────
# Hex codes per user direction. Each profile carries colour palette,
# font choices (ReportLab built-ins so we don't have to ship TTFs),
# and the legal footer text.

LOGO_DIR = Path("/app/frontend/public/system-logos")
LEGAL_PATH = Path("/app/memory/LEGAL_COMPLIANCE.md")


def _legal_excerpt(system_id: str) -> str:
    """Pull the per-system legal-footer paragraph from LEGAL_COMPLIANCE.md.
    Falls back to a generic DriveThruRPG attribution if the file is
    missing or has no per-system block."""
    default = (
        "All system mechanics referenced are the property of their respective "
        "rights holders. This document was generated by TableGnostic for "
        "personal table use. Distribute only via DriveThruRPG-licenced channels "
        "and only with the consent of the original rights holders."
    )
    try:
        text = LEGAL_PATH.read_text(encoding="utf-8")
    except Exception:
        return default
    # Look for ## or ### header containing the system id.
    needle = system_id.lower()
    lines = text.split("\n")
    capture: List[str] = []
    capturing = False
    for ln in lines:
        if ln.startswith(("#", "##", "###")):
            if capturing:
                break
            if needle in ln.lower():
                capturing = True
                continue
        if capturing:
            capture.append(ln)
    out = "\n".join(capture).strip() or default
    # Cap length — a legal note shouldn't overflow the footer.
    if len(out) > 1200:
        out = out[:1180].rsplit(" ", 1)[0] + "…"
    return out


STYLE_PROFILES: Dict[str, Dict[str, Any]] = {
    "besm-4e": {
        "name": "BESM 4E",
        # User palette: white, purple, red, black, yellow.
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#3B1E63",  # deep purple
            "secondary":  "#C81D1D",  # red
            "accent":     "#E8B339",  # yellow / gold
            "ink":        "#0B0710",  # near-black
            "muted":      "#6B5B82",  # dusk-purple grey
            "rule":       "#3B1E63",
            "callout_bg": "#F4ECFF",
            "callout_border": "#3B1E63",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": ["besm-4e.png", "besm.png", "anime5e-tristat-emporium.png"],
        "cover_subtitle": "Big Eyes, Small Mouth · Fourth Edition",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "diamond",
    },
    "anime-5e": {
        "name": "Anime 5E",
        # User palette: pink, blue, white, red, black.
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#E03A8E",  # pink
            "secondary":  "#1E66C9",  # blue
            "accent":     "#C81D1D",  # red
            "ink":        "#0B0710",
            "muted":      "#5C6B83",
            "rule":       "#E03A8E",
            "callout_bg": "#FFE7F1",
            "callout_border": "#E03A8E",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Bold",
            "body": "Times-Roman",
            "italic": "Times-Italic",
            "mono": "Courier",
        },
        "logo_files": ["anime5e-tristat-emporium.png", "anime-5e.png"],
        "cover_subtitle": "Anime · 5E · A Tri-Stat Emporium System",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "petal",
    },
    "_default": {
        "name": "TableGnostic",
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#1E2A4A",
            "secondary":  "#C8A34A",
            "accent":     "#7A1F2E",
            "ink":        "#0B0710",
            "muted":      "#5B6275",
            "rule":       "#1E2A4A",
            "callout_bg": "#F0EFEC",
            "callout_border": "#1E2A4A",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": [],
        "cover_subtitle": "A Campaign Chronicle",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "rule",
    },
}


def _profile_for(system_id: Optional[str]) -> Dict[str, Any]:
    if not system_id:
        return STYLE_PROFILES["_default"]
    return STYLE_PROFILES.get(system_id, STYLE_PROFILES["_default"])


def _resolve_logo(profile: Dict[str, Any]) -> Optional[Path]:
    for fn in profile["logo_files"]:
        p = LOGO_DIR / fn
        if p.exists() and p.is_file():
            return p
    return None


# ─────────────────────── Chapter assembly ───────────────────────

def _group_sessions_into_chapters(sessions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Chapter 1 = S0 + S1 + S2 ; Ch2+ = pairs.

    Sessions are sorted by `created_at` then a "Session N" hint in the
    title so we honour the seed order when timestamps are clustered.
    """
    def _session_index(s: Dict[str, Any]) -> int:
        t = (s.get("title") or "").lower()
        for i in range(0, 30):
            if f"session {i}" in t:
                return i
        # Fallback: order of insertion.
        return 99 + sessions.index(s)

    ordered = sorted(sessions, key=lambda s: (_session_index(s), s.get("created_at", "")))
    chapters: List[Dict[str, Any]] = []
    if not ordered:
        return chapters

    has_s0 = any(_session_index(s) == 0 for s in ordered)
    if has_s0:
        # Ch1 = S0 + S1 + S2. Then pairs.
        first = [s for s in ordered if _session_index(s) <= 2]
        rest = [s for s in ordered if _session_index(s) > 2]
        if first:
            chapters.append({"number": 1, "title": "Chapter 1", "sessions": first})
        for i in range(0, len(rest), 2):
            chunk = rest[i:i+2]
            chapters.append({
                "number": len(chapters) + 1,
                "title": f"Chapter {len(chapters) + 1}",
                "sessions": chunk,
            })
    else:
        # No Session 0 → Ch1 = S1+S2, Ch2 = S3+S4, etc.
        for i in range(0, len(ordered), 2):
            chunk = ordered[i:i+2]
            chapters.append({
                "number": len(chapters) + 1,
                "title": f"Chapter {len(chapters) + 1}",
                "sessions": chunk,
            })
    return chapters


async def _session_prose(s: Dict[str, Any], camp_id: str) -> Tuple[str, List[Dict[str, Any]]]:
    """Return (narrative_text, journal_quotes). The narrative prefers a
    finalised chronicle node; falls back to the latest recap; falls back
    to a chat-log digest if nothing else exists."""
    sid = s["id"]
    # 1. Look for a finalised session_record node.
    node = await db.nodes.find_one(
        {"campaign_id": camp_id, "type": "session_record",
         "fields.session_id": sid, "fields.is_finalized": True},
        {"_id": 0}
    )
    if node and node.get("content"):
        narrative = node["content"]
    else:
        # 2. Latest recap.
        recap = await db.recaps.find_one({"session_id": sid}, {"_id": 0},
                                          sort=[("created_at", -1)])
        if recap and recap.get("text"):
            narrative = recap["text"]
        else:
            # 3. Chat-log digest (truncated).
            chats = await db.chat_logs.find({"session_id": sid}, {"_id": 0}) \
                                       .sort("created_at", 1).to_list(120)
            lines = []
            for c in chats[:80]:
                kind = c.get("kind", "chat")
                if kind == "system":
                    lines.append(f"  · {c.get('message','')}")
                else:
                    lines.append(f"  {c.get('user_name','?')}: {c.get('message','')}")
            narrative = "\n".join(lines) or "(No transcript available.)"

    # Player journals tied to this session.
    journals = await db.nodes.find(
        {"campaign_id": camp_id, "type": "player_journal",
         "fields.session_id": sid},
        {"_id": 0}
    ).to_list(20)
    return narrative, journals


# ─────────────────────── PDF rendering ───────────────────────

def _build_pdf(camp: Dict[str, Any], chapters_data: List[Dict[str, Any]],
                profile: Dict[str, Any]) -> bytes:
    """Render the PDF and return the raw bytes."""
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        BaseDocTemplate, Frame, NextPageTemplate, PageBreak, PageTemplate,
        Paragraph, Spacer, Image as RLImage, KeepTogether,
    )

    p = profile["palette"]
    f = profile["fonts"]
    primary = HexColor(p["primary"])
    secondary = HexColor(p["secondary"])
    accent = HexColor(p["accent"])
    ink = HexColor(p["ink"])
    muted = HexColor(p["muted"])
    rule = HexColor(p["rule"])
    callout_bg = HexColor(p["callout_bg"])
    callout_border = HexColor(p["callout_border"])

    pw, ph = LETTER
    margin = 0.75 * inch

    buf = io.BytesIO()

    cover_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin,
                        leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                        showBoundary=0, id="cover")
    body_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin - 0.4 * inch,
                       leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                       showBoundary=0, id="body")
    chapter_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin - 0.4 * inch,
                          leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                          showBoundary=0, id="chapter_body")

    legal_text = _legal_excerpt(camp.get("system_id") or "")
    system_name = profile["name"]
    camp_name = camp.get("name", "Untitled Campaign")

    def cover_page(canv, _doc):
        canv.saveState()
        # Background flood
        canv.setFillColor(HexColor(p["background"]))
        canv.rect(0, 0, pw, ph, fill=1, stroke=0)
        # Top accent bar (system colour)
        canv.setFillColor(primary)
        canv.rect(0, ph - 0.5 * inch, pw, 0.5 * inch, fill=1, stroke=0)
        # Bottom accent bar (secondary)
        canv.setFillColor(secondary)
        canv.rect(0, 0, pw, 0.4 * inch, fill=1, stroke=0)
        # Vertical accent stripe (yellow / accent)
        canv.setFillColor(accent)
        canv.rect(0.4 * inch, 0.4 * inch, 0.12 * inch, ph - 0.9 * inch, fill=1, stroke=0)
        # System name (top-right)
        canv.setFont(f["subheading"], 11)
        canv.setFillColor(HexColor("#FFFFFF"))
        canv.drawRightString(pw - margin, ph - 0.3 * inch, system_name.upper())
        # Logo (centred, ~2 inches tall)
        logo_path = _resolve_logo(profile)
        if logo_path:
            try:
                from PIL import Image as PILImage
                with PILImage.open(logo_path) as im:
                    iw, ih = im.size
                target_h = 1.8 * inch
                target_w = (iw / ih) * target_h
                if target_w > pw - 2 * margin - inch:
                    target_w = pw - 2 * margin - inch
                    target_h = (ih / iw) * target_w
                canv.drawImage(str(logo_path),
                                (pw - target_w) / 2,
                                ph - 3.4 * inch,
                                width=target_w, height=target_h,
                                preserveAspectRatio=True, mask='auto')
            except Exception:
                pass
        # Title
        canv.setFillColor(ink)
        canv.setFont(f["heading"], 36)
        title_y = ph - 4.4 * inch
        canv.drawCentredString(pw / 2, title_y, camp_name[:60])
        # Subtitle
        canv.setFont(f["italic"], 14)
        canv.setFillColor(muted)
        canv.drawCentredString(pw / 2, title_y - 0.45 * inch,
                                profile["cover_subtitle"])
        # Decorative diamond / petal
        canv.setStrokeColor(accent)
        canv.setLineWidth(2)
        deco_y = title_y - 1.0 * inch
        canv.line(pw / 2 - 0.6 * inch, deco_y, pw / 2 + 0.6 * inch, deco_y)
        canv.setFillColor(accent)
        canv.circle(pw / 2, deco_y, 0.08 * inch, fill=1, stroke=0)
        # Footer attribution
        canv.setFont(f["body"], 9)
        canv.setFillColor(HexColor("#FFFFFF"))
        canv.drawCentredString(pw / 2, 0.16 * inch,
                                "Generated by TableGnostic · DriveThruRPG-ready")
        canv.restoreState()

    def chrome(canv, doc, kind: str = "body"):
        """Header/footer for non-cover pages."""
        canv.saveState()
        # Top rule
        canv.setStrokeColor(rule)
        canv.setLineWidth(0.6)
        canv.line(margin, ph - 0.55 * inch, pw - margin, ph - 0.55 * inch)
        # Header text
        canv.setFont(f["subheading"], 8)
        canv.setFillColor(muted)
        canv.drawString(margin, ph - 0.4 * inch, camp_name.upper())
        canv.drawRightString(pw - margin, ph - 0.4 * inch, system_name.upper())
        # Bottom rule
        canv.setStrokeColor(rule)
        canv.line(margin, 0.55 * inch, pw - margin, 0.55 * inch)
        canv.setFont(f["body"], 8)
        canv.setFillColor(muted)
        canv.drawString(margin, 0.38 * inch,
                         "Generated by TableGnostic · DriveThruRPG-ready")
        canv.drawRightString(pw - margin, 0.38 * inch, f"p. {doc.page}")
        canv.restoreState()

    doc = BaseDocTemplate(buf, pagesize=LETTER,
                          leftMargin=margin, rightMargin=margin,
                          topMargin=margin, bottomMargin=margin,
                          title=camp_name, author="TableGnostic")
    doc.addPageTemplates([
        PageTemplate(id="cover", frames=[cover_frame], onPage=cover_page),
        PageTemplate(id="body", frames=[body_frame], onPage=lambda c, d: chrome(c, d, "body")),
        PageTemplate(id="chapter", frames=[chapter_frame], onPage=lambda c, d: chrome(c, d, "chapter")),
    ])

    # Paragraph styles
    h1 = ParagraphStyle("h1", fontName=f["heading"], fontSize=26,
                        textColor=primary, leading=30, spaceAfter=12)
    h2 = ParagraphStyle("h2", fontName=f["heading"], fontSize=18,
                        textColor=secondary, leading=22, spaceBefore=16, spaceAfter=8)
    h3 = ParagraphStyle("h3", fontName=f["subheading"], fontSize=12,
                        textColor=primary, leading=16, spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle("body", fontName=f["body"], fontSize=10.5,
                          textColor=ink, leading=15, spaceAfter=8)
    italic = ParagraphStyle("italic", fontName=f["italic"], fontSize=10,
                            textColor=muted, leading=14, spaceAfter=8)
    callout_label = ParagraphStyle("callout-label", fontName=f["heading"], fontSize=8,
                                    textColor=callout_border, leading=10,
                                    spaceAfter=2, alignment=0,
                                    leftIndent=10)
    callout_body = ParagraphStyle("callout", fontName=f["italic"], fontSize=9.5,
                                   textColor=ink, leading=13,
                                   leftIndent=10, rightIndent=10,
                                   spaceAfter=10, backColor=callout_bg,
                                   borderColor=callout_border, borderWidth=0.6,
                                   borderPadding=8)
    legal_style = ParagraphStyle("legal", fontName=f["body"], fontSize=8,
                                  textColor=muted, leading=11,
                                  spaceBefore=10)

    flow: List[Any] = []

    # ── Cover — first page is the cover; rest of doc switches to body.
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())

    # ── Table of contents (simple list, generated from chapters)
    flow.append(Paragraph("Table of Contents", h1))
    flow.append(_thin_rule(rule))
    for ch in chapters_data:
        sess_titles = " · ".join((s.get("title") or "Session").split("—")[0].strip()
                                  for s in ch["sessions"])
        flow.append(Paragraph(f"<b>{ch['title']}</b> &nbsp;&nbsp; <font color='{p['muted']}'>{sess_titles}</font>",
                                body))
    flow.append(Spacer(1, 0.2 * inch))

    # ── Chapters
    for ch in chapters_data:
        flow.append(NextPageTemplate("chapter"))
        flow.append(PageBreak())
        flow.append(Paragraph(f"{profile['chapter_prefix']} {ch['number']}", h3))
        flow.append(Paragraph(ch["title"], h1))
        flow.append(_thin_rule(rule))
        for s in ch["sessions"]:
            flow.append(Paragraph(s.get("title") or "Session", h2))
            narrative = s.get("_narrative") or "(No transcript available.)"
            for para in [pp.strip() for pp in narrative.split("\n\n") if pp.strip()]:
                flow.append(Paragraph(_html_escape(para), body))
            journals = s.get("_journals") or []
            for j in journals:
                ch_name = (j.get("fields") or {}).get("character_name", "")
                title = f"Journal — {ch_name}" if ch_name else "Journal"
                flow.append(KeepTogether([
                    Paragraph(title.upper(), callout_label),
                    Paragraph(_html_escape(j.get("content", "").strip()), callout_body),
                ]))

    # ── Legal footer page
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())
    flow.append(Paragraph("Legal &amp; Compliance", h1))
    flow.append(_thin_rule(rule))
    flow.append(Paragraph("Distribution channel: <b>DriveThruRPG</b>.", italic))
    for para in [pp.strip() for pp in legal_text.split("\n\n") if pp.strip()]:
        flow.append(Paragraph(_html_escape(para), legal_style))
    flow.append(Spacer(1, 0.2 * inch))
    flow.append(Paragraph(
        f"This chronicle was generated by TableGnostic for the campaign "
        f"<b>{_html_escape(camp_name)}</b>. The {_html_escape(system_name)} "
        f"branding is used under the publisher's distribution licence.",
        legal_style,
    ))

    doc.build(flow)
    return buf.getvalue()


def _thin_rule(color):
    """A 0.5-pt horizontal rule as a Platypus Flowable."""
    from reportlab.platypus import Flowable
    class _R(Flowable):
        def __init__(self, c):
            super().__init__()
            self.c = c
        def wrap(self, w, h):
            self._w = w
            return (w, 6)
        def draw(self):
            self.canv.setStrokeColor(self.c)
            self.canv.setLineWidth(0.6)
            self.canv.line(0, 2, self._w, 2)
    return _R(color)


def _html_escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;"))


# ─────────────────────── Endpoint ───────────────────────

@router.get("/campaigns/{cid}/export.pdf")
async def export_pdf(cid: str, user: dict = Depends(get_current_user)):
    """GM/admin downloads a system-branded PDF chronicle."""
    camp = await db.campaigns.find_one({"id": cid}, {"_id": 0})
    if not camp:
        raise HTTPException(404, "Campaign not found")
    if camp["gm_id"] != user["id"] and user.get("role") != "admin":
        raise HTTPException(403, "GM/admin only.")
    sessions = await db.sessions.find({"campaign_id": cid}, {"_id": 0}) \
                                 .sort("created_at", 1).to_list(60)
    if not sessions:
        raise HTTPException(400, "No sessions to export.")
    profile = _profile_for(camp.get("system_id"))
    chapters_data = _group_sessions_into_chapters(sessions)
    # Hydrate each session with its narrative + journals.
    for ch in chapters_data:
        for s in ch["sessions"]:
            narrative, journals = await _session_prose(s, cid)
            s["_narrative"] = narrative
            s["_journals"] = journals
    pdf_bytes = _build_pdf(camp, chapters_data, profile)
    # Header values must be latin-1 safe; strip non-ASCII from filename.
    raw_name = (camp.get("name") or "campaign").replace(" ", "_")
    safe = "".join(ch if ord(ch) < 128 and ch not in '"\\' else "_" for ch in raw_name)
    fname = f"{safe.strip('_') or 'campaign'}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )
