"""DriveThruRPG-ready PDF export (V4.4 Phase E).

GET /api/campaigns/{cid}/export.pdf — streams a system-branded PDF.

Layout decisions (per user):
  * Chapter 1 = Session 0 (Prologue) + Session 1 + Session 2.
  * Subsequent chapters group sessions in pairs (Ch2 = S3+S4, Ch3 = S5+S6,
    Ch4 = S7+S8, …).
  * Per-system visual identity — full styling, not just accent colours.
  * Logos at top of cover when available on disk.
  * Legal footer per system, sourced from /app/memory/LEGAL_COMPLIANCE.md.

Style profiles ship initially for BESM 4E and Anime 5E. Other systems
fall back to a neutral DriveThruRPG-friendly profile so a GM never gets
a 500 — they just get a less branded PDF until we author that system.

We sniff each session's `chat_logs` + `recaps` + the GM-finalized
`session_record` chronicle (preferred when present) to assemble chapter
prose. Player journals append as colour quotations.
"""
from __future__ import annotations

import io
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from core.db import db
from core.security import get_current_user

router = APIRouter(prefix="/api", tags=["pdf"])

# ─────────────────────── Style profiles ───────────────────────
# Hex codes per user direction. Each profile carries colour palette,
# font choices (ReportLab built-ins so we don't have to ship TTFs),
# and the legal footer text.

LOGO_DIR = Path("/app/frontend/public/system-logos")
LEGAL_PATH = Path("/app/memory/LEGAL_COMPLIANCE.md")


def _legal_required_footer(system_id: str) -> str:
    """Extract ONLY the ``Required PDF footer`` blockquote from the
    per-system entry in LEGAL_COMPLIANCE.md. This is the official text
    the publisher requires us to print verbatim on saleable PDFs (e.g.
    Dyskami's Tri-Stat Emporium attribution for BESM 4E)."""
    try:
        text = LEGAL_PATH.read_text(encoding="utf-8")
    except Exception:
        return ""
    needle = system_id.lower().replace("-", "").replace(" ", "")
    needle_loose = system_id.lower().replace("-", " ")
    lines = text.split("\n")
    in_section = False
    in_quote = False
    quote_lines: List[str] = []
    saw_required_marker = False
    for ln in lines:
        if ln.startswith("###"):
            stripped = ln.lower().replace("-", " ")
            is_system_block = (needle in stripped.replace(" ", "")
                               or needle_loose in stripped)
            if is_system_block and any(c.isdigit() for c in ln[:8]):
                in_section = True
                in_quote = False
                continue
            elif in_section and any(c.isdigit() for c in ln[:8]):
                # Hit the next system block — stop.
                break
        if not in_section:
            continue
        if "required pdf footer" in ln.lower():
            saw_required_marker = True
            continue
        if saw_required_marker and ln.startswith(">"):
            in_quote = True
            quote_lines.append(ln.lstrip("> ").rstrip())
            continue
        if in_quote and not ln.startswith(">"):
            if quote_lines and ln.strip() == "":
                continue  # tolerate blank lines inside the quote
            break
    return " ".join(q for q in quote_lines if q).strip()


def _legal_excerpt(system_id: str) -> str:
    """Pull the per-system legal-footer paragraph from LEGAL_COMPLIANCE.md.
    Falls back to a generic DriveThruRPG attribution if the file is
    missing or has no per-system block."""
    default = (
        "All system mechanics referenced are the property of their respective "
        "rights holders. This document was generated by TableGnostic for "
        "personal table use. Distribute only via DriveThruRPG-licenced channels "
        "and only with the consent of the original rights holders."
    )
    try:
        text = LEGAL_PATH.read_text(encoding="utf-8")
    except Exception:
        return default
    # Look for a header containing the system id. The system_id arrives
    # with a hyphen (e.g. "besm-4e") but the markdown headers are
    # human-readable ("BESM 4E"); compare both shapes plus a stripped
    # alpha-numeric form so the match is robust.
    needle = system_id.lower().replace("-", "").replace(" ", "")  # "besm4e"
    needle_loose = system_id.lower().replace("-", " ")  # "besm 4e"
    lines = text.split("\n")
    capture: List[str] = []
    capturing = False
    for ln in lines:
        if ln.startswith("#"):
            if capturing:
                # Stop only when we hit another top-level system header
                # (### at the same depth). Within-section ### subheaders
                # like "Required PDF footer" should still be captured.
                if ln.startswith("### ") and any(c.isdigit() for c in ln[:8]):
                    break
                # Otherwise keep going — we want the full system block.
                capture.append(ln)
                continue
            stripped = ln.lower().replace("-", " ")
            if needle in stripped.replace(" ", "") or needle_loose in stripped:
                capturing = True
                continue
        if capturing:
            capture.append(ln)
    out = "\n".join(capture).strip() or default
    if len(out) > 2400:
        out = out[:2380].rsplit(" ", 1)[0] + "…"
    return out


STYLE_PROFILES: Dict[str, Dict[str, Any]] = {
    "besm-4e": {
        "name": "BESM 4E",
        # User palette: white, purple, red, black, yellow.
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#3B1E63",  # deep purple
            "secondary":  "#C81D1D",  # red
            "accent":     "#E8B339",  # yellow / gold
            "ink":        "#0B0710",  # near-black
            "muted":      "#6B5B82",  # dusk-purple grey
            "rule":       "#3B1E63",
            "callout_bg": "#F4ECFF",
            "callout_border": "#3B1E63",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": ["besm-4e.png", "besm.png", "anime5e-tristat-emporium.png"],
        "cover_subtitle": "Big Eyes, Small Mouth · Fourth Edition",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "diamond",
    },
    "anime-5e": {
        "name": "Anime 5E",
        # User palette: pink, blue, white, red, black.
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#E03A8E",  # pink
            "secondary":  "#1E66C9",  # blue
            "accent":     "#C81D1D",  # red
            "ink":        "#0B0710",
            "muted":      "#5C6B83",
            "rule":       "#E03A8E",
            "callout_bg": "#FFE7F1",
            "callout_border": "#E03A8E",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Bold",
            "body": "Times-Roman",
            "italic": "Times-Italic",
            "mono": "Courier",
        },
        "logo_files": ["anime5e-tristat-emporium.png", "anime-5e.png"],
        "cover_subtitle": "Anime · 5E · A Tri-Stat Emporium System",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "petal",
    },
    "_default": {
        "name": "TableGnostic",
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#1E2A4A",
            "secondary":  "#C8A34A",
            "accent":     "#7A1F2E",
            "ink":        "#0B0710",
            "muted":      "#5B6275",
            "rule":       "#1E2A4A",
            "callout_bg": "#F0EFEC",
            "callout_border": "#1E2A4A",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": [],
        "cover_subtitle": "A Campaign Chronicle",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "rule",
    },
}


def _profile_for(system_id: Optional[str]) -> Dict[str, Any]:
    if not system_id:
        return STYLE_PROFILES["_default"]
    return STYLE_PROFILES.get(system_id, STYLE_PROFILES["_default"])


def _resolve_logo(profile: Dict[str, Any]) -> Optional[Path]:
    for fn in profile["logo_files"]:
        p = LOGO_DIR / fn
        if p.exists() and p.is_file():
            return p
    return None


# ─────────────────────── Chapter assembly ───────────────────────

def _group_sessions_into_chapters(sessions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Chapter 1 = S0 + S1 + S2 ; Ch2+ = pairs.

    Sessions are sorted by `created_at` then a "Session N" hint in the
    title so we honour the seed order when timestamps are clustered.

    Each returned chapter carries:
      number — int (1-based).
      title  — short descriptor like "Chapter I" (used in TOC).
      title_text — the chapter's narrative title (e.g. taken from the
                   first session's title-after-em-dash). Used as the
                   single big H1 on the chapter page so we never render
                   "Chapter 1" twice.
      sessions — list of full session dicts.
    """
    def _session_index(s: Dict[str, Any]) -> int:
        t = (s.get("title") or "").lower()
        for i in range(0, 30):
            if f"session {i}" in t:
                return i
        # Fallback: order of insertion.
        return 99 + sessions.index(s)

    def _short_title(s: Dict[str, Any]) -> str:
        """The phrase after the em-dash, e.g. 'The Maiden Road'."""
        t = (s.get("title") or "Session")
        if "—" in t:
            return t.split("—", 1)[1].strip()
        if "-" in t:
            return t.split("-", 1)[1].strip()
        return t

    ordered = sorted(sessions, key=lambda s: (_session_index(s), s.get("created_at", "")))
    chapters: List[Dict[str, Any]] = []
    if not ordered:
        return chapters

    has_s0 = any(_session_index(s) == 0 for s in ordered)

    def _emit(sess_chunk: List[Dict[str, Any]]):
        chapters.append({
            "number": len(chapters) + 1,
            "title": f"Chapter {_roman(len(chapters) + 1)}",
            # Narrative chapter title = first session's short title.
            "title_text": _short_title(sess_chunk[0]) if sess_chunk else "",
            "sessions": sess_chunk,
        })

    if has_s0:
        # Ch1 = S0 + S1 + S2. Then pairs.
        first = [s for s in ordered if _session_index(s) <= 2]
        rest = [s for s in ordered if _session_index(s) > 2]
        if first:
            _emit(first)
        for i in range(0, len(rest), 2):
            _emit(rest[i:i+2])
    else:
        # No Session 0 → Ch1 = S1+S2, Ch2 = S3+S4, etc.
        for i in range(0, len(ordered), 2):
            _emit(ordered[i:i+2])
    return chapters


async def _session_prose(s: Dict[str, Any], camp_id: str) -> Tuple[str, List[Dict[str, Any]]]:
    """Return (narrative_text, journal_quotes). The narrative prefers a
    finalised chronicle node; falls back to the latest recap; falls back
    to a chat-log digest if nothing else exists.

    For the digest fallback we paragraph-break on every speaker change
    so the Paragraph flowable renders distinct paragraphs (with first-
    line indent) instead of a single wall of text.
    """
    sid = s["id"]
    # 1. Look for a finalised session_record node.
    node = await db.nodes.find_one(
        {"campaign_id": camp_id, "type": "session_record",
         "fields.session_id": sid, "fields.is_finalized": True},
        {"_id": 0}
    )
    if node and node.get("content"):
        narrative = node["content"]
    else:
        # 2. Latest recap.
        recap = await db.recaps.find_one({"session_id": sid}, {"_id": 0},
                                          sort=[("created_at", -1)])
        if recap and recap.get("text"):
            narrative = recap["text"]
        else:
            # 3. Chat-log digest. Group by speaker so each speaker turn
            #    becomes its own paragraph.
            chats = await db.chat_logs.find({"session_id": sid}, {"_id": 0}) \
                                       .sort("created_at", 1).to_list(120)
            paragraphs: List[str] = []
            buf: List[str] = []
            last_speaker: Optional[str] = None
            for c in chats[:120]:
                kind = c.get("kind", "chat")
                speaker = c.get("user_name", "?")
                msg = (c.get("message", "") or "").strip()
                if not msg:
                    continue
                if kind == "system":
                    # GM narration — its own paragraph.
                    if buf:
                        paragraphs.append(" ".join(buf))
                        buf = []
                    paragraphs.append(msg)
                    last_speaker = None
                else:
                    line = (
                        f"\u201C{msg}\u201D" if kind == "chat" else
                        f"{speaker} {msg.lstrip()}" if kind == "action" else
                        f"({speaker}: {msg})"
                    )
                    # New speaker starts a new paragraph; same speaker
                    # continues the current one for natural prose flow.
                    if speaker != last_speaker:
                        if buf:
                            paragraphs.append(" ".join(buf))
                            buf = []
                        buf.append(f"\u2014 {speaker}: {line}" if kind == "chat" else line)
                    else:
                        buf.append(line)
                    last_speaker = speaker
            if buf:
                paragraphs.append(" ".join(buf))
            narrative = "\n\n".join(paragraphs) or "(No transcript available.)"

    # Player journals tied to this session.
    journals = await db.nodes.find(
        {"campaign_id": camp_id, "type": "player_journal",
         "fields.session_id": sid},
        {"_id": 0}
    ).to_list(20)
    return narrative, journals


# ─────────────────────── PDF rendering ───────────────────────

def _build_pdf(camp: Dict[str, Any], chapters_data: List[Dict[str, Any]],
                profile: Dict[str, Any], gm_user: Optional[Dict[str, Any]] = None) -> bytes:
    """Render the PDF and return the raw bytes."""
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        BaseDocTemplate, Frame, NextPageTemplate, PageBreak, PageTemplate,
        Paragraph, Spacer, Image as RLImage, KeepTogether, HRFlowable,
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

    p = profile["palette"]
    f = profile["fonts"]
    primary = HexColor(p["primary"])
    secondary = HexColor(p["secondary"])
    accent = HexColor(p["accent"])
    ink = HexColor(p["ink"])
    muted = HexColor(p["muted"])
    rule = HexColor(p["rule"])
    callout_bg = HexColor(p["callout_bg"])
    callout_border = HexColor(p["callout_border"])

    pw, ph = LETTER
    margin = 0.75 * inch

    buf = io.BytesIO()

    cover_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin,
                        leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                        showBoundary=0, id="cover")
    body_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin - 0.4 * inch,
                       leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                       showBoundary=0, id="body")
    chapter_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin - 0.4 * inch,
                          leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                          showBoundary=0, id="chapter_body")

    legal_text = _legal_excerpt(camp.get("system_id") or "")
    required_footer = _legal_required_footer(camp.get("system_id") or "")
    legal_block = required_footer or _legal_block(camp.get("system_id") or "")  # short cover-footer attribution
    system_name = profile["name"]
    camp_name = camp.get("name", "Untitled Campaign")
    gm_byline = (gm_user or {}).get("byline_name") or (gm_user or {}).get("name") or "the GM"
    current_year = datetime.now(timezone.utc).year

    def cover_page(canv, _doc):
        canv.saveState()
        # Background flood
        canv.setFillColor(HexColor(p["background"]))
        canv.rect(0, 0, pw, ph, fill=1, stroke=0)
        # Top accent bar (system colour)
        canv.setFillColor(primary)
        canv.rect(0, ph - 0.5 * inch, pw, 0.5 * inch, fill=1, stroke=0)
        # Bottom accent bar (secondary) — slightly taller to host the legal block
        canv.setFillColor(secondary)
        canv.rect(0, 0, pw, 1.4 * inch, fill=1, stroke=0)
        # Vertical accent stripe (yellow / accent)
        canv.setFillColor(accent)
        canv.rect(0.4 * inch, 1.4 * inch, 0.12 * inch, ph - 1.9 * inch, fill=1, stroke=0)
        # System name (top-right)
        canv.setFont(f["subheading"], 11)
        canv.setFillColor(HexColor("#FFFFFF"))
        canv.drawRightString(pw - margin, ph - 0.3 * inch, system_name.upper())
        # Logo (centred, ~2.4 inches tall — bigger now that it's the system mark)
        logo_path = _resolve_logo(profile)
        logo_bottom = ph - 4.0 * inch  # default if no logo
        if logo_path:
            try:
                from PIL import Image as PILImage
                with PILImage.open(logo_path) as im:
                    iw, ih = im.size
                target_h = 2.4 * inch
                target_w = (iw / ih) * target_h
                max_w = pw - 2 * margin - inch
                if target_w > max_w:
                    target_w = max_w
                    target_h = (ih / iw) * target_w
                logo_x = (pw - target_w) / 2
                logo_y = ph - 1.0 * inch - target_h
                canv.drawImage(str(logo_path), logo_x, logo_y,
                                width=target_w, height=target_h,
                                preserveAspectRatio=True, mask='auto')
                logo_bottom = logo_y - 0.2 * inch
            except Exception:
                pass
        # Title — width-aware, centred. We render through a paragraph so
        # long titles wrap onto multiple lines instead of overflowing.
        title_style = ParagraphStyle(
            "cover-title", fontName=f["heading"], fontSize=42,
            textColor=ink, leading=46, alignment=TA_CENTER,
        )
        title_para = Paragraph(_html_escape(camp_name), title_style)
        # Width = full inner width minus a comfortable gutter so long titles
        # don't visually crash into the accent stripe.
        title_max_w = pw - 2 * margin - 0.4 * inch
        title_avail_h = logo_bottom - 2.2 * inch  # reserve space below for byline+legal
        # Auto-shrink the font if the title still overflows.
        for fontsize, leading in [(42, 46), (34, 38), (28, 32), (22, 26), (18, 22)]:
            ts = ParagraphStyle("cover-title", fontName=f["heading"],
                                 fontSize=fontsize, textColor=ink,
                                 leading=leading, alignment=TA_CENTER)
            tp = Paragraph(_html_escape(camp_name), ts)
            tw, th = tp.wrap(title_max_w, title_avail_h)
            if th <= title_avail_h:
                title_para = tp
                title_h = th
                break
        else:
            title_h = title_avail_h
        title_top_y = logo_bottom - 0.2 * inch
        title_para.drawOn(canv, (pw - title_max_w) / 2,
                           title_top_y - title_h)
        title_bottom_y = title_top_y - title_h
        # Subtitle
        canv.setFont(f["italic"], 14)
        canv.setFillColor(muted)
        canv.drawCentredString(pw / 2, title_bottom_y - 0.35 * inch,
                                profile["cover_subtitle"])
        # Decorative diamond rule
        canv.setStrokeColor(accent)
        canv.setLineWidth(2)
        deco_y = title_bottom_y - 0.75 * inch
        canv.line(pw / 2 - 0.6 * inch, deco_y, pw / 2 + 0.6 * inch, deco_y)
        canv.setFillColor(accent)
        canv.circle(pw / 2, deco_y, 0.08 * inch, fill=1, stroke=0)
        # GM byline
        canv.setFont(f["heading"], 14)
        canv.setFillColor(primary)
        canv.drawCentredString(pw / 2, deco_y - 0.45 * inch,
                                f"by {gm_byline}")
        canv.setFont(f["italic"], 10)
        canv.setFillColor(muted)
        canv.drawCentredString(pw / 2, deco_y - 0.65 * inch,
                                "Weaved in TableGnostic")
        # Bottom legal block — sits inside the secondary-coloured bar.
        canv.setFillColor(HexColor("#FFFFFF"))
        canv.setFont(f["heading"], 8)
        canv.drawCentredString(pw / 2, 1.18 * inch,
                                f"© {current_year} {gm_byline} · All Aurea original content")
        canv.setFont(f["body"], 7.5)
        # Wrap the per-system legal block across 4-5 lines.
        legal_lines = _wrap_lines(legal_block, 110)
        ly = 0.95 * inch
        for ln in legal_lines[:5]:
            canv.drawCentredString(pw / 2, ly, ln)
            ly -= 0.13 * inch
        # Footer attribution at the very bottom
        canv.setFont(f["body"], 8)
        canv.drawCentredString(pw / 2, 0.18 * inch,
                                "Generated by TableGnostic · DriveThruRPG-ready")
        canv.restoreState()

    def chrome(canv, doc, kind: str = "body"):
        """Header/footer for non-cover pages."""
        canv.saveState()
        # Top rule
        canv.setStrokeColor(rule)
        canv.setLineWidth(0.6)
        canv.line(margin, ph - 0.55 * inch, pw - margin, ph - 0.55 * inch)
        # Header text
        canv.setFont(f["subheading"], 8)
        canv.setFillColor(muted)
        canv.drawString(margin, ph - 0.4 * inch, camp_name.upper())
        canv.drawRightString(pw - margin, ph - 0.4 * inch, system_name.upper())
        # Bottom rule
        canv.setStrokeColor(rule)
        canv.line(margin, 0.55 * inch, pw - margin, 0.55 * inch)
        canv.setFont(f["body"], 8)
        canv.setFillColor(muted)
        canv.drawString(margin, 0.38 * inch,
                         f"Weaved in TableGnostic · by {gm_byline}")
        canv.drawRightString(pw - margin, 0.38 * inch, f"p. {doc.page}")
        canv.restoreState()

    doc = BaseDocTemplate(buf, pagesize=LETTER,
                          leftMargin=margin, rightMargin=margin,
                          topMargin=margin, bottomMargin=margin,
                          title=camp_name, author=gm_byline)
    doc.addPageTemplates([
        PageTemplate(id="cover", frames=[cover_frame], onPage=cover_page),
        PageTemplate(id="body", frames=[body_frame], onPage=lambda c, d: chrome(c, d, "body")),
        PageTemplate(id="chapter", frames=[chapter_frame], onPage=lambda c, d: chrome(c, d, "chapter")),
    ])

    # Paragraph styles — first-line indent for body, generous spacing.
    chapter_label = ParagraphStyle("chapter-label", fontName=f["subheading"],
                                    fontSize=10, textColor=secondary,
                                    leading=12, spaceAfter=2,
                                    alignment=TA_CENTER, letterSpacing=2)
    chapter_title = ParagraphStyle("chapter-title", fontName=f["heading"],
                                    fontSize=30, textColor=primary,
                                    leading=34, spaceAfter=4,
                                    alignment=TA_CENTER)
    chapter_subtitle = ParagraphStyle("chapter-subtitle",
                                       fontName=f["italic"], fontSize=11,
                                       textColor=muted, leading=14,
                                       spaceAfter=18, alignment=TA_CENTER)
    h1 = chapter_title
    session_label = ParagraphStyle("session-label", fontName=f["subheading"],
                                    fontSize=9, textColor=secondary,
                                    leading=11, spaceBefore=22, spaceAfter=2,
                                    alignment=TA_LEFT, letterSpacing=2)
    session_title = ParagraphStyle("session-title", fontName=f["heading"],
                                    fontSize=18, textColor=primary,
                                    leading=22, spaceAfter=10,
                                    alignment=TA_LEFT)
    body = ParagraphStyle("body", fontName=f["body"], fontSize=10.5,
                          textColor=ink, leading=16, spaceAfter=10,
                          firstLineIndent=18, alignment=TA_JUSTIFY)
    body_first = ParagraphStyle("body-first", parent=body,
                                 firstLineIndent=0)  # first paragraph of a section, no indent
    italic = ParagraphStyle("italic", fontName=f["italic"], fontSize=10,
                            textColor=muted, leading=14, spaceAfter=8)
    callout_label = ParagraphStyle("callout-label", fontName=f["heading"], fontSize=8,
                                    textColor=callout_border, leading=10,
                                    spaceAfter=2, alignment=0,
                                    leftIndent=10, letterSpacing=1)
    callout_body = ParagraphStyle("callout", fontName=f["italic"], fontSize=9.5,
                                   textColor=ink, leading=13,
                                   leftIndent=10, rightIndent=10,
                                   spaceAfter=10, backColor=callout_bg,
                                   borderColor=callout_border, borderWidth=0.6,
                                   borderPadding=8)
    legal_style = ParagraphStyle("legal", fontName=f["body"], fontSize=8,
                                  textColor=muted, leading=11,
                                  spaceBefore=10, alignment=TA_JUSTIFY)
    toc_style = ParagraphStyle("toc", fontName=f["body"], fontSize=11,
                                textColor=ink, leading=18, spaceAfter=6)

    flow: List[Any] = []

    # ── Cover — first page is the cover; rest of doc switches to body.
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())

    # ── Table of contents (simple list, generated from chapters)
    flow.append(Paragraph("Table of Contents", h1))
    flow.append(_thin_rule(rule))
    for ch in chapters_data:
        sess_titles = " · ".join((s.get("title") or "Session").split("—")[0].strip()
                                  for s in ch["sessions"])
        flow.append(Paragraph(
            f"<b>{_html_escape(ch['title'])}</b> &nbsp;&nbsp; "
            f"<font color='{p['muted']}'>{_html_escape(sess_titles)}</font>",
            toc_style))
    flow.append(Spacer(1, 0.2 * inch))

    # ── Chapters
    for ch in chapters_data:
        flow.append(NextPageTemplate("chapter"))
        flow.append(PageBreak())
        # Single-source heading: small kerned label + big roman-numeral
        # title. No more duplicated "Chapter N" lines.
        flow.append(Paragraph(_chapter_label(ch["number"]), chapter_label))
        flow.append(Paragraph(_html_escape(ch["title_text"] or ch["title"]),
                                chapter_title))
        # Subtitle = list of session titles in this chapter, comma-joined.
        sub = " · ".join((s.get("title") or "").strip() for s in ch["sessions"])
        if sub:
            flow.append(Paragraph(_html_escape(sub), chapter_subtitle))
        flow.append(_thin_rule(rule))
        # Each session within the chapter is its own block, separated by
        # a horizontal divider so the user can keep them visually distinct.
        for s_idx, s in enumerate(ch["sessions"]):
            if s_idx > 0:
                # Divider between sessions inside the same chapter.
                flow.append(Spacer(1, 0.25 * inch))
                flow.append(HRFlowable(width="50%", thickness=0.5,
                                        color=accent, spaceBefore=0, spaceAfter=10,
                                        hAlign="CENTER"))
            # Session header — "SESSION N" small label + bigger title
            sess_label_text = _session_label(s)
            if sess_label_text:
                flow.append(Paragraph(sess_label_text, session_label))
            flow.append(Paragraph(_html_escape((s.get("title") or "Session")),
                                    session_title))

            narrative = s.get("_narrative") or "(No transcript available.)"
            paragraphs = [pp.strip() for pp in narrative.split("\n\n") if pp.strip()]
            for i, para in enumerate(paragraphs):
                style = body_first if i == 0 else body
                flow.append(Paragraph(_html_escape(para), style))
            journals = s.get("_journals") or []
            for j in journals:
                ch_name = (j.get("fields") or {}).get("character_name", "")
                title = f"Journal — {ch_name}" if ch_name else "Journal"
                flow.append(KeepTogether([
                    Paragraph(title.upper(), callout_label),
                    Paragraph(_html_escape(j.get("content", "").strip()), callout_body),
                ]))

    # ── Legal footer page
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())
    flow.append(Paragraph("Legal &amp; Compliance", h1))
    flow.append(_thin_rule(rule))
    flow.append(Paragraph("Distribution channel: <b>DriveThruRPG</b>.", italic))
    flow.append(Paragraph(
        f"This chronicle was produced and weaved by <b>{_html_escape(gm_byline)}</b> "
        f"in TableGnostic during {current_year}. © {current_year} {_html_escape(gm_byline)}. "
        f"All Aurea original content © Table-Gnostic contributors.",
        legal_style,
    ))
    # Publisher's required attribution — printed verbatim, prominently.
    if required_footer:
        flow.append(Spacer(1, 0.15 * inch))
        flow.append(Paragraph("Publisher's Required Attribution", chapter_label))
        flow.append(Paragraph(
            _html_escape(required_footer),
            ParagraphStyle("required-quote", parent=legal_style,
                            fontSize=9.5, leading=14,
                            textColor=ink, leftIndent=14, rightIndent=14,
                            borderColor=callout_border, borderWidth=0.5,
                            borderPadding=10, backColor=callout_bg,
                            spaceBefore=4, spaceAfter=12),
        ))
    # Compliance summary — strip markdown markers so the prose reads
    # cleanly on the printed page.
    cleaned_summary = _strip_markdown(legal_text)
    if cleaned_summary:
        flow.append(Paragraph("Compliance Summary", chapter_label))
        for para in [pp.strip() for pp in cleaned_summary.split("\n\n") if pp.strip()]:
            flow.append(Paragraph(_html_escape(para), legal_style))

    doc.build(flow)
    return buf.getvalue()


def _chapter_label(n: int) -> str:
    return f"CHAPTER&nbsp;&nbsp;{_roman(n)}"


def _session_label(s: Dict[str, Any]) -> str:
    """Extract 'Session N' from a title like 'Session 2 — The Faunamimic's Apology'."""
    t = (s.get("title") or "").lower()
    for i in range(0, 30):
        if f"session {i}" in t:
            return f"SESSION&nbsp;&nbsp;{i}"
    return ""


def _roman(n: int) -> str:
    if n <= 0:
        return str(n)
    table = [
        (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
        (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
        (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
    ]
    out = []
    for value, sym in table:
        while n >= value:
            out.append(sym)
            n -= value
    return "".join(out)


def _wrap_lines(text: str, width: int) -> List[str]:
    """Soft word-wrap for canvas-drawn legal text (no Paragraph available
    inside the cover_page callback)."""
    out: List[str] = []
    for raw in text.split("\n"):
        words = raw.split()
        if not words:
            out.append("")
            continue
        line = words[0]
        for w in words[1:]:
            if len(line) + 1 + len(w) > width:
                out.append(line)
                line = w
            else:
                line = line + " " + w
        out.append(line)
    return out


def _strip_markdown(text: str) -> str:
    """Strip markdown markers so the printed legal page reads as prose.
    Removes ** bold markers, leading * / - / > bullets, and collapses
    consecutive blank lines."""
    import re
    lines: List[str] = []
    for raw in text.split("\n"):
        ln = raw
        # Strip blockquote and bullet markers at start of line.
        ln = re.sub(r"^[\s>*\-]+", "", ln).strip()
        # Convert markdown bold/italic ** → drop, * (single) → drop.
        ln = ln.replace("**", "")
        ln = ln.replace("`", "")
        if ln:
            lines.append(ln)
    return "\n\n".join(lines)


def _legal_block(system_id: str) -> str:
    """Short cover-footer legal — first 3-4 sentences from the per-system
    excerpt in LEGAL_COMPLIANCE.md, condensed to fit the bottom bar."""
    full = _legal_excerpt(system_id)
    # Strip markdown blockquote markers and bullets.
    cleaned = []
    for ln in full.split("\n"):
        s = ln.lstrip(" >*-").strip()
        if s:
            cleaned.append(s)
    cleaned_text = " ".join(cleaned)
    # Cap at ~520 chars for the cover bar.
    if len(cleaned_text) > 520:
        cleaned_text = cleaned_text[:510].rsplit(" ", 1)[0] + "…"
    return cleaned_text or full


def _thin_rule(color):
    """A 0.5-pt horizontal rule as a Platypus Flowable."""
    from reportlab.platypus import Flowable
    class _R(Flowable):
        def __init__(self, c):
            super().__init__()
            self.c = c
        def wrap(self, w, h):
            self._w = w
            return (w, 6)
        def draw(self):
            self.canv.setStrokeColor(self.c)
            self.canv.setLineWidth(0.6)
            self.canv.line(0, 2, self._w, 2)
    return _R(color)


def _html_escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;"))


# ─────────────────────── Endpoint ───────────────────────

@router.get("/campaigns/{cid}/export.pdf")
async def export_pdf(cid: str, user: dict = Depends(get_current_user)):
    """GM/admin downloads a system-branded PDF chronicle."""
    camp = await db.campaigns.find_one({"id": cid}, {"_id": 0})
    if not camp:
        raise HTTPException(404, "Campaign not found")
    if camp["gm_id"] != user["id"] and user.get("role") != "admin":
        raise HTTPException(403, "GM/admin only.")
    sessions = await db.sessions.find({"campaign_id": cid}, {"_id": 0}) \
                                 .sort("created_at", 1).to_list(60)
    if not sessions:
        raise HTTPException(400, "No sessions to export.")
    profile = _profile_for(camp.get("system_id"))
    chapters_data = _group_sessions_into_chapters(sessions)
    # Hydrate each session with its narrative + journals.
    for ch in chapters_data:
        for s in ch["sessions"]:
            narrative, journals = await _session_prose(s, cid)
            s["_narrative"] = narrative
            s["_journals"] = journals
    # Look up the campaign's GM user (preferred byline_name, fall back to
    # name) so the cover + page footer can credit a real human.
    gm_user = await db.users.find_one({"id": camp.get("gm_id")},
                                       {"_id": 0, "byline_name": 1, "name": 1, "email": 1})
    pdf_bytes = _build_pdf(camp, chapters_data, profile, gm_user)
    # Header values must be latin-1 safe; strip non-ASCII from filename.
    raw_name = (camp.get("name") or "campaign").replace(" ", "_")
    safe = "".join(ch if ord(ch) < 128 and ch not in '"\\' else "_" for ch in raw_name)
    fname = f"{safe.strip('_') or 'campaign'}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )
