"""DriveThruRPG-ready PDF export (V4.4 Phase E).

GET /api/campaigns/{cid}/export.pdf — streams a system-branded PDF.

Layout decisions (per user):
  * Chapter 1 = Session 0 (Prologue) + Session 1 + Session 2.
  * Subsequent chapters group sessions in pairs (Ch2 = S3+S4, Ch3 = S5+S6,
    Ch4 = S7+S8, …).
  * Per-system visual identity — full styling, not just accent colours.
  * Logos at top of cover when available on disk.
  * Legal footer per system, sourced from /app/memory/LEGAL_COMPLIANCE.md.

Style profiles ship initially for BESM 4E and Anime 5E. Other systems
fall back to a neutral DriveThruRPG-friendly profile so a GM never gets
a 500 — they just get a less branded PDF until we author that system.

We sniff each session's `chat_logs` + `recaps` + the GM-finalized
`session_record` chronicle (preferred when present) to assemble chapter
prose. Player journals append as colour quotations.
"""
from __future__ import annotations

import io
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from core.db import db
from core.security import get_current_user

router = APIRouter(prefix="/api", tags=["pdf"])

# ─────────────────────── Style profiles ───────────────────────
# Hex codes per user direction. Each profile carries colour palette,
# font choices (ReportLab built-ins so we don't have to ship TTFs),
# and the legal footer text.

LOGO_DIR = Path("/app/frontend/public/system-logos")
LEGAL_PATH = Path("/app/memory/LEGAL_COMPLIANCE.md")


def _legal_required_footer(system_id: str) -> str:
    """Extract ONLY the ``Required PDF footer`` blockquote from the
    per-system entry in LEGAL_COMPLIANCE.md. This is the official text
    the publisher requires us to print verbatim on saleable PDFs (e.g.
    Dyskami's Tri-Stat Emporium attribution for BESM 4E)."""
    try:
        text = LEGAL_PATH.read_text(encoding="utf-8")
    except Exception:
        return ""
    needle = system_id.lower().replace("-", "").replace(" ", "")
    needle_loose = system_id.lower().replace("-", " ")
    lines = text.split("\n")
    in_section = False
    in_quote = False
    quote_lines: List[str] = []
    saw_required_marker = False
    for ln in lines:
        if ln.startswith("###"):
            stripped = ln.lower().replace("-", " ")
            is_system_block = (needle in stripped.replace(" ", "")
                               or needle_loose in stripped)
            if is_system_block and any(c.isdigit() for c in ln[:8]):
                in_section = True
                in_quote = False
                continue
            elif in_section and any(c.isdigit() for c in ln[:8]):
                # Hit the next system block — stop.
                break
        if not in_section:
            continue
        if "required pdf footer" in ln.lower():
            saw_required_marker = True
            continue
        if saw_required_marker and ln.startswith(">"):
            in_quote = True
            quote_lines.append(ln.lstrip("> ").rstrip())
            continue
        if in_quote and not ln.startswith(">"):
            if quote_lines and ln.strip() == "":
                continue  # tolerate blank lines inside the quote
            break
    return " ".join(q for q in quote_lines if q).strip()


def _legal_excerpt(system_id: str) -> str:
    """Pull the per-system legal-footer paragraph from LEGAL_COMPLIANCE.md.
    Falls back to a generic DriveThruRPG attribution if the file is
    missing or has no per-system block."""
    default = (
        "All system mechanics referenced are the property of their respective "
        "rights holders. This document was generated by TableGnostic for "
        "personal table use. Distribute only via DriveThruRPG-licenced channels "
        "and only with the consent of the original rights holders."
    )
    try:
        text = LEGAL_PATH.read_text(encoding="utf-8")
    except Exception:
        return default
    # Look for a header containing the system id. The system_id arrives
    # with a hyphen (e.g. "besm-4e") but the markdown headers are
    # human-readable ("BESM 4E"); compare both shapes plus a stripped
    # alpha-numeric form so the match is robust.
    needle = system_id.lower().replace("-", "").replace(" ", "")  # "besm4e"
    needle_loose = system_id.lower().replace("-", " ")  # "besm 4e"
    lines = text.split("\n")
    capture: List[str] = []
    capturing = False
    for ln in lines:
        if ln.startswith("#"):
            if capturing:
                # Stop only when we hit another top-level system header
                # (### at the same depth). Within-section ### subheaders
                # like "Required PDF footer" should still be captured.
                if ln.startswith("### ") and any(c.isdigit() for c in ln[:8]):
                    break
                # Otherwise keep going — we want the full system block.
                capture.append(ln)
                continue
            stripped = ln.lower().replace("-", " ")
            if needle in stripped.replace(" ", "") or needle_loose in stripped:
                capturing = True
                continue
        if capturing:
            capture.append(ln)
    out = "\n".join(capture).strip() or default
    if len(out) > 2400:
        out = out[:2380].rsplit(" ", 1)[0] + "…"
    return out


STYLE_PROFILES: Dict[str, Dict[str, Any]] = {
    "besm-4e": {
        "name": "BESM 4E",
        # User palette: white, purple, red, black, yellow.
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#3B1E63",  # deep purple
            "secondary":  "#C81D1D",  # red
            "accent":     "#E8B339",  # yellow / gold
            "ink":        "#0B0710",  # near-black
            "muted":      "#6B5B82",  # dusk-purple grey
            "rule":       "#3B1E63",
            "callout_bg": "#F4ECFF",
            "callout_border": "#3B1E63",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": ["besm-4e.png", "besm.png", "anime5e-tristat-emporium.png"],
        "cover_subtitle": "Big Eyes, Small Mouth · Fourth Edition",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "diamond",
    },
    "anime-5e": {
        "name": "Anime 5E",
        # User palette: pink, blue, white, red, black.
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#E03A8E",  # pink
            "secondary":  "#1E66C9",  # blue
            "accent":     "#C81D1D",  # red
            "ink":        "#0B0710",
            "muted":      "#5C6B83",
            "rule":       "#E03A8E",
            "callout_bg": "#FFE7F1",
            "callout_border": "#E03A8E",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Bold",
            "body": "Times-Roman",
            "italic": "Times-Italic",
            "mono": "Courier",
        },
        "logo_files": ["anime5e-tristat-emporium.png", "anime-5e.png"],
        "cover_subtitle": "Anime · 5E · A Tri-Stat Emporium System",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "petal",
    },
    "_default": {
        "name": "TableGnostic",
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#1E2A4A",
            "secondary":  "#C8A34A",
            "accent":     "#7A1F2E",
            "ink":        "#0B0710",
            "muted":      "#5B6275",
            "rule":       "#1E2A4A",
            "callout_bg": "#F0EFEC",
            "callout_border": "#1E2A4A",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": [],
        "cover_subtitle": "A Campaign Chronicle",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "rule",
    },
    "dnd-5e": {
        "name": "D&D 5E (CC-BY SRD)",
        "palette": {
            "background": "#FAF6EC",  # parchment
            "primary":    "#7A1F2E",  # heraldic crimson
            "secondary":  "#1E2A4A",  # midnight indigo
            "accent":     "#C8A34A",  # antique gold
            "ink":        "#0B0710",
            "muted":      "#5B5040",
            "rule":       "#7A1F2E",
            "callout_bg": "#F4E9C8",
            "callout_border": "#7A1F2E",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Bold",
            "body": "Times-Roman",
            "italic": "Times-Italic",
            "mono": "Courier",
        },
        "logo_files": ["dnd-5e.png"],
        "cover_subtitle": "A 5th Edition Chronicle (CC-BY SRD 5.1)",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "fleur",
    },
    "cypher": {
        "name": "Cypher System (Cypher System Creator)",
        "palette": {
            "background": "#FFFFFF",
            "primary":    "#0F2540",  # deep cyber-cobalt
            "secondary":  "#7B68B5",  # arcane violet
            "accent":     "#1F8C7A",  # numenera-teal
            "ink":        "#0A1020",
            "muted":      "#5A6380",
            "rule":       "#0F2540",
            "callout_bg": "#E8F1F8",
            "callout_border": "#0F2540",
        },
        "fonts": {
            "heading": "Helvetica-Bold",
            "subheading": "Helvetica-Oblique",
            "body": "Helvetica",
            "italic": "Helvetica-Oblique",
            "mono": "Courier",
        },
        "logo_files": ["cypher.png"],
        "cover_subtitle": "A Cypher System Chronicle",
        "chapter_prefix": "Chapter",
        "chapter_decoration": "circuit",
    },
}


def _profile_for(system_id: Optional[str]) -> Dict[str, Any]:
    if not system_id:
        return STYLE_PROFILES["_default"]
    return STYLE_PROFILES.get(system_id, STYLE_PROFILES["_default"])


def _narrative_profile(system_id: Optional[str]) -> Dict[str, Any]:
    """Generic narrative-only profile used when a GM exports as a story (not
    as a sellable supplement). Strips system trade-dress / logos and uses the
    neutral parchment palette so no licensable mark appears on the cover."""
    base = dict(STYLE_PROFILES["_default"])
    base = {**base, "palette": dict(base["palette"]), "fonts": dict(base["fonts"])}
    base["name"] = "Narrative Story"
    base["logo_files"] = []
    sys_label = (STYLE_PROFILES.get(system_id or "") or {}).get("name", "")
    base["cover_subtitle"] = (
        "A Narrative Chronicle · setting & system-influenced voicing"
        + (f" · {sys_label}" if sys_label else "")
    )
    base["chapter_decoration"] = "rule"
    base["narrative_only"] = True
    return base


def _resolve_logo(profile: Dict[str, Any]) -> Optional[Path]:
    for fn in profile["logo_files"]:
        p = LOGO_DIR / fn
        if p.exists() and p.is_file():
            return p
    return None


# ─────────────────────── Chapter assembly ───────────────────────

def _group_sessions_into_chapters(sessions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Chapter 1 = S0 + S1 + S2 ; Ch2+ = pairs.

    Sessions are sorted by `created_at` then a "Session N" hint in the
    title so we honour the seed order when timestamps are clustered.

    Each returned chapter carries:
      number — int (1-based).
      title  — short descriptor like "Chapter I" (used in TOC).
      title_text — the chapter's narrative title (e.g. taken from the
                   first session's title-after-em-dash). Used as the
                   single big H1 on the chapter page so we never render
                   "Chapter 1" twice.
      sessions — list of full session dicts.
    """
    def _session_index(s: Dict[str, Any]) -> int:
        t = (s.get("title") or "").lower()
        for i in range(0, 30):
            if f"session {i}" in t:
                return i
        # Fallback: order of insertion.
        return 99 + sessions.index(s)

    def _short_title(s: Dict[str, Any]) -> str:
        """The phrase after the em-dash, e.g. 'The Maiden Road'."""
        t = (s.get("title") or "Session")
        if "—" in t:
            return t.split("—", 1)[1].strip()
        if "-" in t:
            return t.split("-", 1)[1].strip()
        return t

    ordered = sorted(sessions, key=lambda s: (_session_index(s), s.get("created_at", "")))
    chapters: List[Dict[str, Any]] = []
    if not ordered:
        return chapters

    has_s0 = any(_session_index(s) == 0 for s in ordered)

    def _emit(sess_chunk: List[Dict[str, Any]]):
        chapters.append({
            "number": len(chapters) + 1,
            "title": f"Chapter {_roman(len(chapters) + 1)}",
            # Narrative chapter title = first session's short title.
            "title_text": _short_title(sess_chunk[0]) if sess_chunk else "",
            "sessions": sess_chunk,
        })

    if has_s0:
        # Ch1 = S0 + S1 + S2. Then pairs.
        first = [s for s in ordered if _session_index(s) <= 2]
        rest = [s for s in ordered if _session_index(s) > 2]
        if first:
            _emit(first)
        for i in range(0, len(rest), 2):
            _emit(rest[i:i+2])
    else:
        # No Session 0 → Ch1 = S1+S2, Ch2 = S3+S4, etc.
        for i in range(0, len(ordered), 2):
            _emit(ordered[i:i+2])
    return chapters


async def _session_prose(s: Dict[str, Any], camp_id: str) -> Tuple[str, List[Dict[str, Any]]]:
    """Return (narrative_text, journal_quotes). The narrative prefers a
    finalised chronicle node; falls back to the latest recap; falls back
    to a chat-log digest if nothing else exists.

    For the digest fallback we paragraph-break on every speaker change
    so the Paragraph flowable renders distinct paragraphs (with first-
    line indent) instead of a single wall of text.
    """
    sid = s["id"]
    # 1. Look for a finalised session_record node.
    node = await db.nodes.find_one(
        {"campaign_id": camp_id, "type": "session_record",
         "fields.session_id": sid, "fields.is_finalized": True},
        {"_id": 0}
    )
    if node and node.get("content"):
        narrative = node["content"]
    else:
        # 2. Latest recap.
        recap = await db.recaps.find_one({"session_id": sid}, {"_id": 0},
                                          sort=[("created_at", -1)])
        if recap and recap.get("text"):
            narrative = recap["text"]
        else:
            # 3. Chat-log digest. Group by speaker so each speaker turn
            #    becomes its own paragraph.
            chats = await db.chat_logs.find({"session_id": sid}, {"_id": 0}) \
                                       .sort("created_at", 1).to_list(120)
            paragraphs: List[str] = []
            buf: List[str] = []
            last_speaker: Optional[str] = None
            for c in chats[:120]:
                kind = c.get("kind", "chat")
                speaker = c.get("user_name", "?")
                msg = (c.get("message", "") or "").strip()
                if not msg:
                    continue
                if kind == "system":
                    # GM narration — its own paragraph.
                    if buf:
                        paragraphs.append(" ".join(buf))
                        buf = []
                    paragraphs.append(msg)
                    last_speaker = None
                else:
                    line = (
                        f"\u201C{msg}\u201D" if kind == "chat" else
                        f"{speaker} {msg.lstrip()}" if kind == "action" else
                        f"({speaker}: {msg})"
                    )
                    # New speaker starts a new paragraph; same speaker
                    # continues the current one for natural prose flow.
                    if speaker != last_speaker:
                        if buf:
                            paragraphs.append(" ".join(buf))
                            buf = []
                        buf.append(f"\u2014 {speaker}: {line}" if kind == "chat" else line)
                    else:
                        buf.append(line)
                    last_speaker = speaker
            if buf:
                paragraphs.append(" ".join(buf))
            narrative = "\n\n".join(paragraphs) or "(No transcript available.)"

    # Player journals tied to this session.
    journals = await db.nodes.find(
        {"campaign_id": camp_id, "type": "player_journal",
         "fields.session_id": sid},
        {"_id": 0}
    ).to_list(20)
    return narrative, journals


# ─────────────────────── PDF rendering ───────────────────────

def _build_pdf(camp: Dict[str, Any], chapters_data: List[Dict[str, Any]],
                profile: Dict[str, Any], gm_user: Optional[Dict[str, Any]] = None,
                extras: Optional[Dict[str, Any]] = None) -> bytes:
    """Render the PDF and return the raw bytes."""
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        BaseDocTemplate, Frame, NextPageTemplate, PageBreak, PageTemplate,
        Paragraph, Spacer, Image as RLImage, KeepTogether, HRFlowable,
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

    p = profile["palette"]
    f = profile["fonts"]
    primary = HexColor(p["primary"])
    secondary = HexColor(p["secondary"])
    accent = HexColor(p["accent"])
    ink = HexColor(p["ink"])
    muted = HexColor(p["muted"])
    rule = HexColor(p["rule"])
    callout_bg = HexColor(p["callout_bg"])
    callout_border = HexColor(p["callout_border"])

    pw, ph = LETTER
    margin = 0.75 * inch

    buf = io.BytesIO()

    cover_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin,
                        leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                        showBoundary=0, id="cover")
    body_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin - 0.4 * inch,
                       leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                       showBoundary=0, id="body")
    chapter_frame = Frame(margin, margin, pw - 2 * margin, ph - 2 * margin - 0.4 * inch,
                          leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0,
                          showBoundary=0, id="chapter_body")

    legal_text = _legal_excerpt(camp.get("system_id") or "")
    required_footer = _legal_required_footer(camp.get("system_id") or "")
    # Note: legal_block (short cover-footer attribution) intentionally unused —
    # the new BESM4-styled cover prints its own trademark text in the rounded
    # blue bar. Kept the helper available for non-BESM systems.
    system_name = profile["name"]
    camp_name = camp.get("name", "Untitled Campaign")
    gm_byline = (gm_user or {}).get("byline_name") or (gm_user or {}).get("name") or "the GM"
    current_year = datetime.now(timezone.utc).year

    def cover_page(canv, _doc):
        # Cover layout adapted from the BESM 4E Layout Templates
        # (Tri-Stat Emporium content-creator pack):
        #   * Wide title block at the top in primary system colour.
        #   * Centred logo at upper-mid.
        #   * Three credit rows (WRITTEN BY / ADDITIONAL WRITING BY /
        #     SPECIAL THANKS TO) — no Artwork-By or Graphic-Production-By
        #     rows per user request (strips art-copyright surface area).
        #   * Mark MacKinnon attribution + Dyskami Publishing Company line.
        #   * Bottom rounded blue bar with the Tri-Stat trademark text +
        #     http://BESM4.life URL + Tri-Stat Emporium logo at right.
        canv.saveState()
        # Background
        canv.setFillColor(HexColor(p["background"]))
        canv.rect(0, 0, pw, ph, fill=1, stroke=0)
        # Top primary band — TITLE OF THE BOOK area
        canv.setFillColor(primary)
        canv.rect(0, ph - 1.5 * inch, pw, 1.5 * inch, fill=1, stroke=0)
        # System badge top-left
        canv.setFont(f["subheading"], 10)
        canv.setFillColor(HexColor("#FFFFFF"))
        canv.drawString(margin, ph - 0.4 * inch, system_name.upper())
        # Big TITLE — width-aware, centred inside the top band.
        title_max_w = pw - 2 * margin
        title_para = None
        title_h = 0
        for fontsize, leading in [(38, 42), (32, 36), (26, 30), (22, 26)]:
            ts = ParagraphStyle("cover-title", fontName=f["heading"],
                                 fontSize=fontsize,
                                 textColor=HexColor("#FFFFFF"),
                                 leading=leading, alignment=TA_CENTER)
            tp = Paragraph(_html_escape(camp_name.upper()), ts)
            tw, th = tp.wrap(title_max_w, 1.2 * inch)
            if th <= 1.2 * inch:
                title_para = tp
                title_h = th
                break
        if title_para is None:
            title_para = tp
            title_h = th
        title_para.drawOn(canv, margin,
                           ph - 0.5 * inch - title_h - 0.05 * inch)

        # Centred logo at upper-mid
        logo_path = _resolve_logo(profile)
        logo_bottom = ph - 4.0 * inch
        if logo_path:
            try:
                from PIL import Image as PILImage
                with PILImage.open(logo_path) as im:
                    iw, ih = im.size
                target_h = 1.6 * inch
                target_w = (iw / ih) * target_h
                max_w = pw - 2 * margin - inch
                if target_w > max_w:
                    target_w = max_w
                    target_h = (ih / iw) * target_w
                logo_x = (pw - target_w) / 2
                logo_y = ph - 1.7 * inch - target_h - 0.4 * inch
                canv.drawImage(str(logo_path), logo_x, logo_y,
                                width=target_w, height=target_h,
                                preserveAspectRatio=True, mask='auto')
                logo_bottom = logo_y - 0.25 * inch
            except Exception:
                pass

        # Credits block (centred). Order matches BESM 4 layout, minus art rows.
        credits_y = logo_bottom
        canv.setFont(f["subheading"], 11)
        canv.setFillColor(secondary)
        canv.drawCentredString(pw / 2, credits_y, "WRITTEN BY:")
        canv.setFont(f["heading"], 14)
        canv.setFillColor(ink)
        canv.drawCentredString(pw / 2, credits_y - 0.22 * inch, gm_byline)

        canv.setFont(f["subheading"], 10)
        canv.setFillColor(secondary)
        canv.drawCentredString(pw / 2, credits_y - 0.55 * inch, "ADDITIONAL WRITING BY:")
        canv.setFont(f["body"], 10)
        canv.setFillColor(muted)
        canv.drawCentredString(pw / 2, credits_y - 0.72 * inch, "the players at the Evereantha table")

        canv.setFont(f["subheading"], 10)
        canv.setFillColor(secondary)
        canv.drawCentredString(pw / 2, credits_y - 1.0 * inch, "SPECIAL THANKS TO:")
        canv.setFont(f["body"], 10)
        canv.setFillColor(muted)
        canv.drawCentredString(pw / 2, credits_y - 1.17 * inch,
                                "the wider TableGnostic community of Game Masters")

        # Mark MacKinnon attribution
        canv.setFont(f["subheading"], 9)
        canv.setFillColor(secondary)
        canv.drawCentredString(pw / 2, credits_y - 1.55 * inch,
                                f"{system_name.upper()} CREATED AND WRITTEN BY:")
        canv.setFont(f["heading"], 11)
        canv.setFillColor(ink)
        canv.drawCentredString(pw / 2, credits_y - 1.70 * inch, "Mark MacKinnon")

        canv.setFont(f["subheading"], 9)
        canv.setFillColor(secondary)
        canv.drawCentredString(pw / 2, credits_y - 1.95 * inch,
                                f"{system_name.upper()} PUBLISHED BY:")
        canv.setFont(f["heading"], 11)
        canv.setFillColor(ink)
        canv.drawCentredString(pw / 2, credits_y - 2.10 * inch,
                                "Dyskami Publishing Company with Japanime Games")

        # Bottom rounded blue bar — system-specific trademark line + URL.
        bar_h = 1.35 * inch
        canv.setFillColor(secondary)
        canv.roundRect(margin / 2, 0.4 * inch, pw - margin, bar_h,
                        radius=14, fill=1, stroke=0)
        canv.setFillColor(HexColor("#FFFFFF"))
        canv.setFont(f["body"], 8)
        sys_id = camp.get("system_id") or "besm-4e"
        if sys_id == "cypher":
            ttext_lines = [
                # Required cover line per the Cypher System Creator licence.
                "Requires the Cypher System Rulebook from Monte Cook Games.",
                "Distributed through the Cypher System Creator™ at DriveThruRPG.",
                "CYPHER SYSTEM and CYPHER SYSTEM CREATOR are trademarks of Monte Cook Games, LLC.",
                f"This chronicle was weaved in TableGnostic by {gm_byline} · © {current_year} {gm_byline}.",
                "www.montecookgames.com",
            ]
        elif sys_id == "dnd-5e":
            ttext_lines = [
                "Mechanics drawn from the System Reference Document 5.1, licensed under CC-BY-4.0.",
                "© Wizards of the Coast LLC. The trademark D&D and Dungeons & Dragons are NOT used.",
                f"This chronicle was weaved in TableGnostic by {gm_byline} · © {current_year} {gm_byline}.",
                "All original adventure content © Table-Gnostic contributors. All other rights reserved.",
                "https://dnd.wizards.com/resources/systems-reference-document",
            ]
        elif sys_id == "anime-5e":
            ttext_lines = [
                "Anime 5E is a Tri-Stat Emporium system © Mark MacKinnon, published by Dyskami Publishing Company.",
                "Tri-Stat System trademarks are used under licence; OGL components per Anime 5E SRD.",
                f"This chronicle was weaved in TableGnostic by {gm_byline} · © {current_year} {gm_byline}.",
                "All original adventure content © Table-Gnostic contributors. All other rights reserved.",
                "http://BESM4.life",
            ]
        else:
            ttext_lines = [
                "Tri-Stat System and BESM are trademarks of Paradox Interactive Group, used under licence.",
                "BESM Fourth Edition mechanics © Mark MacKinnon, published by Dyskami Publishing Company.",
                f"This chronicle was weaved in TableGnostic by {gm_byline} · © {current_year} {gm_byline}.",
                "All Aurea original content © Table-Gnostic contributors. All other rights reserved.",
                "http://BESM4.life",
            ]
        ly = 0.4 * inch + bar_h - 0.25 * inch
        for ln in ttext_lines:
            canv.drawCentredString(pw / 2, ly, ln)
            ly -= 0.18 * inch
        # Right-side trade-dress logo. For Cypher we MUST use the Cypher
        # System Creator logo (not the Cypher System logo). For BESM/Anime
        # we use the Tri-Stat Emporium mark.
        if sys_id == "cypher":
            corner_logo = LOGO_DIR / "cypher.png"
        else:
            corner_logo = LOGO_DIR / "anime5e-tristat-emporium.png"
        if corner_logo.exists():
            try:
                from PIL import Image as PILImage
                with PILImage.open(corner_logo) as im:
                    iw, ih = im.size
                em_h = 0.8 * inch
                em_w = (iw / ih) * em_h
                canv.drawImage(str(corner_logo),
                                pw - margin - em_w - 0.1 * inch,
                                0.5 * inch,
                                width=em_w, height=em_h,
                                preserveAspectRatio=True, mask='auto')
            except Exception:
                pass
        canv.restoreState()

    def _draw_system_ornament(canv, x, y, size, kind):
        """V6.5 — per-system header/footer ornamental glyph.
        Drawn at (x,y) sized `size` points. Pure vector so scales cleanly.
        * diamond  — BESM 4E: lozenge outline
        * petal    — Anime 5E: four-petal rosette
        * fleur    — D&D 5E: stylised fleur-de-lis stroke
        * circuit  — Cypher: nested brackets with a dot core
        * rule     — Default: simple horizontal tick
        """
        canv.saveState()
        canv.setStrokeColor(rule)
        canv.setFillColor(rule)
        canv.setLineWidth(0.7)
        if kind == "diamond":
            half = size / 2
            p = canv.beginPath()
            p.moveTo(x, y + half)
            p.lineTo(x + half, y)
            p.lineTo(x, y - half)
            p.lineTo(x - half, y)
            p.close()
            canv.drawPath(p, stroke=1, fill=0)
        elif kind == "petal":
            r = size / 2
            for dx, dy in ((r, 0), (-r, 0), (0, r), (0, -r)):
                canv.circle(x + dx / 2, y + dy / 2, r / 2.2, stroke=1, fill=0)
        elif kind == "fleur":
            # Cluster of three strokes + a crossbar.
            canv.setLineWidth(1.0)
            canv.line(x, y - size / 2, x, y + size / 2)
            canv.line(x - size / 3, y - size / 3, x, y + size / 3)
            canv.line(x + size / 3, y - size / 3, x, y + size / 3)
            canv.line(x - size / 2, y - size / 4, x + size / 2, y - size / 4)
        elif kind == "circuit":
            # Numenera-teal bracket pair + dot.
            canv.setLineWidth(0.8)
            half = size / 2
            # Left bracket
            canv.line(x - half, y - half, x - half, y + half)
            canv.line(x - half, y - half, x - half + size / 4, y - half)
            canv.line(x - half, y + half, x - half + size / 4, y + half)
            # Right bracket
            canv.line(x + half, y - half, x + half, y + half)
            canv.line(x + half, y - half, x + half - size / 4, y - half)
            canv.line(x + half, y + half, x + half - size / 4, y + half)
            # Core dot
            canv.circle(x, y, size / 10, stroke=0, fill=1)
        else:
            canv.line(x - size / 2, y, x + size / 2, y)
        canv.restoreState()

    def chrome(canv, doc, kind: str = "body"):
        """Header/footer for non-cover pages."""
        canv.saveState()
        # Top rule
        canv.setStrokeColor(rule)
        canv.setLineWidth(0.6)
        canv.line(margin, ph - 0.55 * inch, pw - margin, ph - 0.55 * inch)
        # V6.5 — per-system ornament midway in the top rule (subtle flourish).
        deco = profile.get("chapter_decoration") or "rule"
        _draw_system_ornament(canv, pw / 2, ph - 0.55 * inch, 0.15 * inch, deco)
        # Header text
        canv.setFont(f["subheading"], 8)
        canv.setFillColor(muted)
        canv.drawString(margin, ph - 0.4 * inch, camp_name.upper())
        canv.drawRightString(pw - margin, ph - 0.4 * inch, system_name.upper())
        # Bottom rule
        canv.setStrokeColor(rule)
        canv.line(margin, 0.55 * inch, pw - margin, 0.55 * inch)
        # V6.5 — mirrored ornament on the footer rule.
        _draw_system_ornament(canv, pw / 2, 0.55 * inch, 0.15 * inch, deco)
        canv.setFont(f["body"], 8)
        canv.setFillColor(muted)
        canv.drawString(margin, 0.38 * inch,
                         f"Weaved in TableGnostic · by {gm_byline}")
        canv.drawRightString(pw - margin, 0.38 * inch, f"p. {doc.page}")
        canv.restoreState()

    doc = BaseDocTemplate(buf, pagesize=LETTER,
                          leftMargin=margin, rightMargin=margin,
                          topMargin=margin, bottomMargin=margin,
                          title=camp_name, author=gm_byline)
    doc.addPageTemplates([
        PageTemplate(id="cover", frames=[cover_frame], onPage=cover_page),
        PageTemplate(id="body", frames=[body_frame], onPage=lambda c, d: chrome(c, d, "body")),
        PageTemplate(id="chapter", frames=[chapter_frame], onPage=lambda c, d: chrome(c, d, "chapter")),
    ])

    # Paragraph styles — first-line indent for body, generous spacing.
    chapter_label = ParagraphStyle("chapter-label", fontName=f["subheading"],
                                    fontSize=10, textColor=secondary,
                                    leading=12, spaceAfter=2,
                                    alignment=TA_CENTER, letterSpacing=2)
    chapter_title = ParagraphStyle("chapter-title", fontName=f["heading"],
                                    fontSize=30, textColor=primary,
                                    leading=34, spaceAfter=4,
                                    alignment=TA_CENTER)
    chapter_subtitle = ParagraphStyle("chapter-subtitle",
                                       fontName=f["italic"], fontSize=11,
                                       textColor=muted, leading=14,
                                       spaceAfter=18, alignment=TA_CENTER)
    h1 = chapter_title
    session_label = ParagraphStyle("session-label", fontName=f["subheading"],
                                    fontSize=9, textColor=secondary,
                                    leading=11, spaceBefore=22, spaceAfter=2,
                                    alignment=TA_LEFT, letterSpacing=2)
    session_title = ParagraphStyle("session-title", fontName=f["heading"],
                                    fontSize=18, textColor=primary,
                                    leading=22, spaceAfter=10,
                                    alignment=TA_LEFT)
    body = ParagraphStyle("body", fontName=f["body"], fontSize=10.5,
                          textColor=ink, leading=16, spaceAfter=10,
                          firstLineIndent=18, alignment=TA_JUSTIFY)
    body_first = ParagraphStyle("body-first", parent=body,
                                 firstLineIndent=0)  # first paragraph of a section, no indent
    italic = ParagraphStyle("italic", fontName=f["italic"], fontSize=10,
                            textColor=muted, leading=14, spaceAfter=8)
    callout_label = ParagraphStyle("callout-label", fontName=f["heading"], fontSize=8,
                                    textColor=callout_border, leading=10,
                                    spaceAfter=2, alignment=0,
                                    leftIndent=10, letterSpacing=1)
    callout_body = ParagraphStyle("callout", fontName=f["italic"], fontSize=9.5,
                                   textColor=ink, leading=13,
                                   leftIndent=10, rightIndent=10,
                                   spaceAfter=10, backColor=callout_bg,
                                   borderColor=callout_border, borderWidth=0.6,
                                   borderPadding=8)
    legal_style = ParagraphStyle("legal", fontName=f["body"], fontSize=8,
                                  textColor=muted, leading=11,
                                  spaceBefore=10, alignment=TA_JUSTIFY)
    toc_style = ParagraphStyle("toc", fontName=f["body"], fontSize=11,
                                textColor=ink, leading=18, spaceAfter=6)

    flow: List[Any] = []

    # ── Cover — first page is the cover; rest of doc switches to body.
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())

    # ── Table of contents (simple list, generated from chapters)
    flow.append(Paragraph("Table of Contents", h1))
    flow.append(_thin_rule(rule))
    for ch in chapters_data:
        sess_titles = " · ".join((s.get("title") or "Session").split("—")[0].strip()
                                  for s in ch["sessions"])
        flow.append(Paragraph(
            f"<b>{_html_escape(ch['title'])}</b> &nbsp;&nbsp; "
            f"<font color='{p['muted']}'>{_html_escape(sess_titles)}</font>",
            toc_style))
    flow.append(Spacer(1, 0.2 * inch))

    # ── Chapters
    for ch in chapters_data:
        flow.append(NextPageTemplate("chapter"))
        flow.append(PageBreak())
        # Single-source heading: small kerned label + big roman-numeral
        # title. No more duplicated "Chapter N" lines.
        flow.append(Paragraph(_chapter_label(ch["number"]), chapter_label))
        flow.append(Paragraph(_html_escape(ch["title_text"] or ch["title"]),
                                chapter_title))
        # Subtitle = list of session titles in this chapter, comma-joined.
        sub = " · ".join((s.get("title") or "").strip() for s in ch["sessions"])
        if sub:
            flow.append(Paragraph(_html_escape(sub), chapter_subtitle))
        flow.append(_thin_rule(rule))
        # Each session within the chapter is its own block, separated by
        # a horizontal divider so the user can keep them visually distinct.
        for s_idx, s in enumerate(ch["sessions"]):
            if s_idx > 0:
                # Divider between sessions inside the same chapter.
                flow.append(Spacer(1, 0.25 * inch))
                flow.append(HRFlowable(width="50%", thickness=0.5,
                                        color=accent, spaceBefore=0, spaceAfter=10,
                                        hAlign="CENTER"))
            # Session header — "SESSION N" small label + bigger title
            sess_label_text = _session_label(s)
            if sess_label_text:
                flow.append(Paragraph(sess_label_text, session_label))
            flow.append(Paragraph(_html_escape((s.get("title") or "Session")),
                                    session_title))

            narrative = s.get("_narrative") or "(No transcript available.)"
            paragraphs = [pp.strip() for pp in narrative.split("\n\n") if pp.strip()]
            for i, para in enumerate(paragraphs):
                style = body_first if i == 0 else body
                flow.append(Paragraph(_html_escape(para), style))
            journals = s.get("_journals") or []
            for j in journals:
                ch_name = (j.get("fields") or {}).get("character_name", "")
                title = f"Journal — {ch_name}" if ch_name else "Journal"
                flow.append(KeepTogether([
                    Paragraph(title.upper(), callout_label),
                    Paragraph(_html_escape(j.get("content", "").strip()), callout_body),
                ]))

    # ── Knowledge Web Appendix ──
    # Pull all SHARED nodes (gm_only excluded so we never publish GM secrets).
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())
    flow.append(Paragraph("Appendix · World Codex", h1))
    flow.append(_thin_rule(rule))
    flow.append(Paragraph(
        "The Knowledge Web below collects every shared lore entry, location, "
        "NPC, creature, and faction the table referenced during play. "
        "GM-only entries are intentionally excluded so the chronicle is safe "
        "to publish.", italic))
    if extras and extras.get("nodes"):
        # Sort nodes: locations first (by scale), then NPCs/creatures, then everything else.
        scale_rank = {"country": 0, "kingdom": 0, "region": 1, "biome": 2,
                       "mountain-range": 2, "forest": 2,
                       "city": 3, "town": 4, "hamlet": 5, "landmark": 6,
                       "building": 7}
        type_rank = {"location": 0, "npc": 1, "creature": 2, "faction": 3,
                     "lore": 4, "event": 5, "object": 6, "quest": 7}
        def _node_key(n):
            t = n.get("type", "lore")
            tr = type_rank.get(t, 9)
            sc = (n.get("fields") or {}).get("scale")
            sr = scale_rank.get(sc, 9) if t == "location" else 0
            return (tr, sr, n.get("title", "").lower())
        for n in sorted(extras["nodes"], key=_node_key):
            tags_str = " · ".join((n.get("tags") or [])[:5]) if n.get("tags") else ""
            type_label = (n.get("type") or "lore").upper()
            scale_str = ""
            if n.get("type") == "location":
                sc = (n.get("fields") or {}).get("scale")
                if sc:
                    scale_str = f"  [scale: {sc}]"
            flow.append(Paragraph(
                f"{type_label}{scale_str}", chapter_label))
            flow.append(Paragraph(_html_escape(n.get("title", "Untitled")),
                                    session_title))
            if tags_str:
                flow.append(Paragraph(_html_escape(tags_str), italic))
            content = (n.get("content") or "").strip()
            if content:
                for para in [pp.strip() for pp in content.split("\n\n") if pp.strip()]:
                    flow.append(Paragraph(_html_escape(para), body_first))
            # Structured fields table.
            fields = n.get("fields") or {}
            interesting = [(k, v) for k, v in fields.items()
                           if k not in ("character_id", "linked_character_name",
                                          "is_pinned", "is_gm_journal",
                                          "is_player_character", "entries")
                           and v not in (None, "", [], {})]
            for k, v in interesting:
                if isinstance(v, (list, tuple)):
                    val = "; ".join(str(x) for x in v)
                else:
                    val = str(v)
                flow.append(Paragraph(
                    f"<b>{_html_escape(k.replace('_',' ').title())}:</b> "
                    f"{_html_escape(val[:600])}",
                    callout_body))
            flow.append(Spacer(1, 0.15 * inch))
    else:
        flow.append(Paragraph("(No shared codex entries.)", italic))

    # ── Character Sheet Appendices ──
    # Each published PC gets a one-page sheet so the chronicle is play-ready.
    # System-aware: BESM-shape for besm-4e/anime-5e (Tri-Stat point-buy),
    # D&D class+slot for dnd-5e, type-focus-descriptor for cypher.
    if extras and extras.get("characters"):
        camp_system = camp.get("system_id") or "besm-4e"
        for ci, ch in enumerate(extras["characters"]):
            flow.append(PageBreak())
            flow.append(Paragraph(f"APPENDIX&nbsp;&nbsp;{chr(ord('A')+ci)}", chapter_label))
            flow.append(Paragraph(_html_escape(f"{ch.get('name','?')} — Character Sheet"),
                                    chapter_title))
            concept = ch.get("concept", "")
            if concept:
                flow.append(Paragraph(_html_escape(concept), chapter_subtitle))
            flow.append(_thin_rule(rule))

            folio = ch.get("folio") or {}
            cypher_state = folio.get("cypher_state") if camp_system == "cypher" else None
            dnd_state = folio.get("dnd_state") if camp_system == "dnd-5e" else None

            # V6.13 — embed character portrait (uploaded via
            # /api/uploads/character-portrait/{cid}) when present. We
            # resolve the /api/uploads/portraits/{cid}.{ext} URL to the
            # local uploads directory so reportlab can render it inline.
            _render_character_portrait(flow, ch)

            if cypher_state:
                _render_cypher_pc_sheet(flow, ch, cypher_state, p, body_first, session_title)
            elif dnd_state:
                _render_dnd_pc_sheet(flow, ch, dnd_state, p, body_first, session_title)
            else:
                _render_besm_pc_sheet(flow, ch, p, body_first, session_title)

            # V6.10 — folio.journal entries inline with the character sheet
            # so the chronicle preserves each PC's diary alongside their
            # mechanics. Read-only excerpts; one paragraph per entry.
            entries = (folio.get("journal") or [])
            if isinstance(entries, list) and entries:
                flow.append(Spacer(1, 0.15 * inch))
                flow.append(Paragraph("Character Journal", session_title))
                flow.append(_thin_rule(rule))
                for ej in entries[:80]:
                    when = ej.get("created_at", "")[:19].replace("T", " ") if ej.get("created_at") else ""
                    by = ej.get("by_name") or "—"
                    head = f"<font size='8' color='{p['muted']}'>{_html_escape(when)} · {_html_escape(by)}</font>"
                    text = _html_escape((ej.get("text") or "").strip())
                    flow.append(Paragraph(head, body_first))
                    flow.append(Paragraph(text, body_first))
                    flow.append(Spacer(1, 0.06 * inch))

    # ── Custom Reference Appendix (GM-editable weapons/armor/items/companions) ──
    if extras and extras.get("reference"):
        flow.append(PageBreak())
        flow.append(Paragraph("Appendix · Campaign Reference", chapter_title))
        flow.append(_thin_rule(rule))
        kinds = {"weapon": "Weapons", "armor": "Armor", "item": "Items",
                  "companion": "Companions", "custom": "Custom Rules"}
        for kind, label in kinds.items():
            kind_rows = [r for r in extras["reference"] if r.get("kind") == kind
                         and not (r.get("fields") or {}).get("gm_only")]
            if not kind_rows:
                continue
            flow.append(Paragraph(label, session_title))
            for r in kind_rows:
                page = f"  <font size='8' color='{p['muted']}'>p.{r['page']}</font>" if r.get("page") else ""
                cost = f"  ({r['cost']})" if r.get("cost") else ""
                flow.append(Paragraph(
                    f"<b>{_html_escape(r.get('name','?'))}</b>{cost}{page}",
                    body_first))
                if r.get("summary"):
                    flow.append(Paragraph(_html_escape(r["summary"]), body))
            flow.append(Spacer(1, 0.1 * inch))

    # ── Timeline Appendix (V6.10) — codex pins clustered by session.
    timeline_markers = (extras or {}).get("timeline_markers") or []
    if timeline_markers:
        flow.append(PageBreak())
        flow.append(Paragraph("Appendix · Campaign Timeline", chapter_title))
        flow.append(_thin_rule(rule))
        flow.append(Paragraph(
            "Pins dropped on the Codex Chart by the GM, anchored to the session that introduced them. "
            "Use this to retrace which world elements entered the story on which night.",
            italic,
        ))
        # Group by session_id (preserve order of `sessions_for_timeline`)
        sess_lookup = {s["id"]: s for s in (extras or {}).get("sessions_for_timeline", [])}
        by_session = {}
        for m in timeline_markers:
            by_session.setdefault(m["session_id"], []).append(m)
        for sid, marks in by_session.items():
            sess = sess_lookup.get(sid, {})
            sname = sess.get("name") or sess.get("title") or "Session"
            sdate = (sess.get("scheduled_at") or sess.get("played_at") or "")[:10]
            head = f"<b>{_html_escape(sname)}</b>"
            if sdate:
                head += f"  <font size='8' color='{p['muted']}'>{_html_escape(sdate)}</font>"
            flow.append(Paragraph(head, session_title))
            for mk in marks:
                bullet = f"· <b>{_html_escape(mk.get('label','?'))}</b>"
                if mk.get("kind") and mk["kind"] != "node":
                    bullet += f"  <font size='8' color='{p['muted']}'>[{_html_escape(mk['kind'])}]</font>"
                flow.append(Paragraph(bullet, body_first))
            flow.append(Spacer(1, 0.08 * inch))

    # ── Chat-Transcript Appendix (V6.10) — full conversation logs by session.
    chat_logs_by_session = (extras or {}).get("chat_logs_by_session") or {}
    if chat_logs_by_session:
        flow.append(PageBreak())
        flow.append(Paragraph("Appendix · Chat Transcripts", chapter_title))
        flow.append(_thin_rule(rule))
        flow.append(Paragraph(
            "Verbatim chat logs from each session — narration, dice, journal lines, and table chatter. "
            "Useful for fact-checking recaps and resolving disputes long after the night is done.",
            italic,
        ))
        sess_lookup2 = {s["id"]: s for s in (extras or {}).get("sessions_for_timeline", [])}
        for sid, logs in chat_logs_by_session.items():
            sess = sess_lookup2.get(sid, {})
            sname = sess.get("name") or sess.get("title") or "Session"
            flow.append(Paragraph(_html_escape(sname), session_title))
            for c in logs[:200]:
                speaker = c.get("speaker") or c.get("by_name") or "?"
                kind = c.get("kind", "chat")
                msg = (c.get("body") or c.get("text") or "").strip()
                if not msg:
                    continue
                line = f"<b>{_html_escape(speaker)}:</b> {_html_escape(msg)}"
                if kind != "chat":
                    line = f"<font size='8' color='{p['muted']}'>[{_html_escape(kind)}]</font> {line}"
                flow.append(Paragraph(line, body_first))
            flow.append(Spacer(1, 0.1 * inch))

    # ── Legal footer page
    flow.append(NextPageTemplate("body"))
    flow.append(PageBreak())
    flow.append(Paragraph("Legal &amp; Compliance", h1))
    flow.append(_thin_rule(rule))
    flow.append(Paragraph("Distribution channel: <b>DriveThruRPG</b>.", italic))
    flow.append(Paragraph(
        f"This chronicle was produced and weaved by <b>{_html_escape(gm_byline)}</b> "
        f"in TableGnostic during {current_year}. © {current_year} {_html_escape(gm_byline)}. "
        f"All Aurea original content © Table-Gnostic contributors.",
        legal_style,
    ))
    # Publisher's required attribution — printed verbatim, prominently.
    if required_footer:
        flow.append(Spacer(1, 0.15 * inch))
        flow.append(Paragraph("Publisher's Required Attribution", chapter_label))
        flow.append(Paragraph(
            _html_escape(required_footer),
            ParagraphStyle("required-quote", parent=legal_style,
                            fontSize=9.5, leading=14,
                            textColor=ink, leftIndent=14, rightIndent=14,
                            borderColor=callout_border, borderWidth=0.5,
                            borderPadding=10, backColor=callout_bg,
                            spaceBefore=4, spaceAfter=12),
        ))
    # Compliance summary — strip markdown markers so the prose reads
    # cleanly on the printed page.
    cleaned_summary = _strip_markdown(legal_text)
    if cleaned_summary:
        flow.append(Paragraph("Compliance Summary", chapter_label))
        for para in [pp.strip() for pp in cleaned_summary.split("\n\n") if pp.strip()]:
            flow.append(Paragraph(_html_escape(para), legal_style))

    doc.build(flow)
    return buf.getvalue()


def _chapter_label(n: int) -> str:
    return f"CHAPTER&nbsp;&nbsp;{_roman(n)}"


def _session_label(s: Dict[str, Any]) -> str:
    """Extract 'Session N' from a title like 'Session 2 — The Faunamimic's Apology'."""
    t = (s.get("title") or "").lower()
    for i in range(0, 30):
        if f"session {i}" in t:
            return f"SESSION&nbsp;&nbsp;{i}"
    return ""


def _roman(n: int) -> str:
    if n <= 0:
        return str(n)
    table = [
        (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
        (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
        (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
    ]
    out = []
    for value, sym in table:
        while n >= value:
            out.append(sym)
            n -= value
    return "".join(out)


def _wrap_lines(text: str, width: int) -> List[str]:
    """Soft word-wrap for canvas-drawn legal text (no Paragraph available
    inside the cover_page callback)."""
    out: List[str] = []
    for raw in text.split("\n"):
        words = raw.split()
        if not words:
            out.append("")
            continue
        line = words[0]
        for w in words[1:]:
            if len(line) + 1 + len(w) > width:
                out.append(line)
                line = w
            else:
                line = line + " " + w
        out.append(line)
    return out


def _strip_markdown(text: str) -> str:
    """Strip markdown markers so the printed legal page reads as prose.
    Removes ** bold markers, leading * / - / > bullets, and collapses
    consecutive blank lines."""
    import re
    lines: List[str] = []
    for raw in text.split("\n"):
        ln = raw
        # Strip blockquote and bullet markers at start of line.
        ln = re.sub(r"^[\s>*\-]+", "", ln).strip()
        # Convert markdown bold/italic ** → drop, * (single) → drop.
        ln = ln.replace("**", "")
        ln = ln.replace("`", "")
        if ln:
            lines.append(ln)
    return "\n\n".join(lines)


def _legal_block(system_id: str) -> str:
    """Short cover-footer legal — first 3-4 sentences from the per-system
    excerpt in LEGAL_COMPLIANCE.md, condensed to fit the bottom bar."""
    full = _legal_excerpt(system_id)
    # Strip markdown blockquote markers and bullets.
    cleaned = []
    for ln in full.split("\n"):
        s = ln.lstrip(" >*-").strip()
        if s:
            cleaned.append(s)
    cleaned_text = " ".join(cleaned)
    # Cap at ~520 chars for the cover bar.
    if len(cleaned_text) > 520:
        cleaned_text = cleaned_text[:510].rsplit(" ", 1)[0] + "…"
    return cleaned_text or full


def _thin_rule(color):
    """A 0.5-pt horizontal rule as a Platypus Flowable."""
    from reportlab.platypus import Flowable
    class _R(Flowable):
        def __init__(self, c):
            super().__init__()
            self.c = c
        def wrap(self, w, h):
            self._w = w
            return (w, 6)
        def draw(self):
            self.canv.setStrokeColor(self.c)
            self.canv.setLineWidth(0.6)
            self.canv.line(0, 2, self._w, 2)
    return _R(color)


def _html_escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;"))


# ─────────────────────── Endpoint ───────────────────────

def _render_character_portrait(flow, ch):
    """V6.13 — embed the character's portrait inline in the appendix.

    Silently no-op if no portrait_url is set or the file can't be read
    (the sheet still renders without it).
    """
    portrait_url = ch.get("portrait_url")
    if not portrait_url or not portrait_url.startswith("/api/uploads/"):
        return
    from pathlib import Path
    from reportlab.platypus import Image, Spacer
    from reportlab.lib.units import inch
    upload_root = Path(os.environ.get("UPLOAD_DIR", "/app/uploads"))
    # portrait_url format: /api/uploads/portraits/{cid}.{ext}
    rel = portrait_url.replace("/api/uploads/", "", 1)
    candidate = upload_root / rel
    if not candidate.exists() or not candidate.is_file():
        return
    try:
        # Scale to a tidy 1.6" × 2.1" portrait frame so it sits on the
        # opening line of the character appendix without dominating the
        # page. Landscape / square images get the same box — reportlab
        # preserves aspect ratio within width/height constraints.
        img = Image(str(candidate), width=1.6 * inch, height=2.1 * inch,
                    kind="proportional")
        img.hAlign = "LEFT"
        flow.append(img)
        flow.append(Spacer(1, 0.08 * inch))
    except Exception:
        # Bad image file — just skip; sheet still renders fine.
        return


def _render_besm_pc_sheet(flow, ch, p, body_first, session_title):
    """Tri-Stat / point-buy character appendix (BESM 4E + Anime 5E)."""
    from reportlab.platypus import Paragraph, Spacer
    from reportlab.lib.units import inch
    stats = ch.get("stats", {})
    derived = ch.get("derived", {})
    flow.append(Paragraph(
        f"<b>Body</b> {stats.get('body','-')} &nbsp;·&nbsp; "
        f"<b>Mind</b> {stats.get('mind','-')} &nbsp;·&nbsp; "
        f"<b>Soul</b> {stats.get('soul','-')} &nbsp;·&nbsp; "
        f"<b>ACV</b> {derived.get('acv','-')} &nbsp; "
        f"<b>DCV</b> {derived.get('dcv','-')} &nbsp; "
        f"<b>HP</b> {derived.get('hp','-')} &nbsp; "
        f"<b>EP</b> {derived.get('ep','-')}",
        body_first))
    flow.append(Paragraph(
        f"<b>Power Level:</b> {ch.get('power_level','-')} · "
        f"<b>Total Points:</b> {ch.get('total_points',0)} · "
        f"<b>Spent:</b> {ch.get('spent',{}).get('total_spent',0)} · "
        f"<b>XP:</b> {ch.get('xp_total',0)} earned / "
        f"{ch.get('xp_unspent',0)} unspent",
        body_first))
    # Attributes
    for a in (ch.get("attributes") or []):
        enh = a.get("enhancements") or []
        lim = a.get("limiters") or []
        eff = max(1, int(a.get("level", 1)) + len(lim) - len(enh))
        line = (f"<b>{_html_escape(a.get('name','?'))}</b> ×{a.get('level',1)} "
                f"<font color='{p['muted']}'>(eff. ×{eff} · "
                f"{a.get('cost_per_level',0)} pt/lvl)</font>")
        if enh:
            line += f" &nbsp; <i>+ {_html_escape('; '.join(enh))}</i>"
        if lim:
            line += f" &nbsp; <i>− {_html_escape('; '.join(lim))}</i>"
        if a.get("page"):
            line += f" &nbsp; <font color='{p['muted']}' size='8'>p.{a['page']}</font>"
        flow.append(Paragraph(line, body_first))
    # Skills
    if ch.get("skills"):
        flow.append(Spacer(1, 0.1 * inch))
        flow.append(Paragraph("Skills", session_title))
        for s in ch["skills"]:
            flow.append(Paragraph(
                f"<b>{_html_escape(s.get('group','?'))}</b> ×{s.get('level',1)} "
                f"<font color='{p['muted']}'>({s.get('cost_per_level',0)} pt/lvl)</font>",
                body_first))
            for c in s.get("components", []) or []:
                flow.append(Paragraph(
                    f"&nbsp;&nbsp;&nbsp;· {_html_escape(c.get('name','?'))} "
                    f"×{c.get('level','-')}", body_first))
    # Defects
    if ch.get("defects"):
        flow.append(Spacer(1, 0.1 * inch))
        flow.append(Paragraph("Defects", session_title))
        for d in ch["defects"]:
            flow.append(Paragraph(
                f"<b>{_html_escape(d.get('name','?'))}</b> rank&nbsp;{d.get('rank',1)} "
                f"<font color='{p['muted']}'>(refund "
                f"{d.get('points_per_rank',1)}×{d.get('rank',1)} = "
                f"{int(d.get('points_per_rank',1))*int(d.get('rank',1))} pts)</font>",
                body_first))


def _render_dnd_pc_sheet(flow, ch, state, p, body_first, session_title):
    """D&D 5E class+slot character appendix.

    Mechanics restated in our own words; uses only CC-BY SRD 5.1
    structural references — no Wizards-trademarked content.
    """
    from reportlab.platypus import Paragraph, Spacer
    from reportlab.lib.units import inch
    cls = state.get("class") or "—"
    lvl = int(state.get("level") or 1)
    race = state.get("race") or "—"
    bg = state.get("background") or ""
    flow.append(Paragraph(
        f"<b>Class:</b> {_html_escape(cls)} · <b>Level:</b> {lvl} · "
        f"<b>Race:</b> {_html_escape(race)}"
        + (f" · <b>Background:</b> {_html_escape(bg)}" if bg else "")
        + " &nbsp; <font size='8' color='" + p['muted']
        + "'>(SRD 5.1 / CC-BY-4.0)</font>",
        body_first))
    # Ability scores + modifiers (single line, six pairs).
    scores = state.get("ability_scores") or {}
    abbr = {"Strength": "STR", "Dexterity": "DEX", "Constitution": "CON",
            "Intelligence": "INT", "Wisdom": "WIS", "Charisma": "CHA"}
    score_chunks = []
    for name in ["Strength", "Dexterity", "Constitution",
                 "Intelligence", "Wisdom", "Charisma"]:
        sc = int(scores.get(name) or 10)
        mod = (sc - 10) // 2
        score_chunks.append(
            f"<b>{abbr[name]}</b> {sc} ({'+' if mod >= 0 else ''}{mod})"
        )
    flow.append(Paragraph(" &nbsp;·&nbsp; ".join(score_chunks), body_first))
    # Proficiency / saves / skills
    prof_bonus = max(2, 2 + (max(1, lvl) - 1) // 4)
    saves = state.get("saving_throw_profs") or []
    skill_profs = state.get("skill_profs") or []
    flow.append(Paragraph(
        f"<b>Proficiency:</b> +{prof_bonus} · "
        f"<b>Saves:</b> {_html_escape(', '.join(saves) or '—')} · "
        f"<b>Skill Profs:</b> {_html_escape(', '.join(skill_profs) or '—')}",
        body_first))
    # Inventory + spells
    if state.get("inventory"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Inventory", session_title))
        for item in state["inventory"]:
            flow.append(Paragraph(f"· {_html_escape(str(item))}", body_first))
    if state.get("spells_known"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Spells Known / Prepared", session_title))
        for sp in state["spells_known"]:
            flow.append(Paragraph(f"· {_html_escape(str(sp))}", body_first))
    if state.get("notes"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Notes", session_title))
        flow.append(Paragraph(_html_escape(str(state["notes"])), body_first))


def _render_cypher_pc_sheet(flow, ch, state, p, body_first, session_title):
    """Cypher type-focus-descriptor character appendix.

    Per Cypher System Creator licence: short stat lines and rules
    references are permissible; we cite mechanic names and tier numbers
    only, never reproducing flavour prose.
    """
    from reportlab.platypus import Paragraph, Spacer
    from reportlab.lib.units import inch
    sentence = state.get("sentence") or (
        f"I am a {state.get('descriptor','?')} {state.get('type','?')} "
        f"who {(state.get('focus') or '?').lower()}."
    )
    tier = int(state.get("tier") or 1)
    flow.append(Paragraph(
        f"<i>\u201c{_html_escape(sentence)}\u201d</i> &nbsp; "
        f"<font size='8' color='{p['muted']}'>Tier {tier} · Cypher System Creator</font>",
        body_first))
    pools = state.get("pools") or {}
    edge = state.get("edge") or {}
    pool_chunks = []
    for k in ("Might", "Speed", "Intellect"):
        pool_chunks.append(
            f"<b>{k}</b> {int(pools.get(k) or 0)} "
            f"<font color='{p['muted']}'>(Edge {int(edge.get(k) or 0)})</font>"
        )
    flow.append(Paragraph(
        " &nbsp;·&nbsp; ".join(pool_chunks)
        + f" &nbsp;·&nbsp; <b>Effort:</b> {int(state.get('effort') or 1)}",
        body_first))
    if state.get("skill_trains"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Skills Trained", session_title))
        flow.append(Paragraph(_html_escape(", ".join(state["skill_trains"])), body_first))
    if state.get("abilities"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Type / Focus Abilities", session_title))
        for ab in state["abilities"]:
            flow.append(Paragraph(f"· {_html_escape(str(ab))}", body_first))
    if state.get("cyphers"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Cyphers Carried", session_title))
        for cyp in state["cyphers"]:
            flow.append(Paragraph(f"· {_html_escape(str(cyp))}", body_first))
    if state.get("notes"):
        flow.append(Spacer(1, 0.08 * inch))
        flow.append(Paragraph("Notes / GM Intrusion ledger", session_title))
        flow.append(Paragraph(_html_escape(str(state["notes"])), body_first))


# ─── Per-licence setting gate ───────────────────────────────────────────
# Some system licences (notably Cypher System Creator) explicitly forbid
# Creator-distributed content for certain campaign settings. The export
# endpoint refuses to generate a PDF when the campaign is tagged with a
# forbidden setting — players can still run the campaign in-app, but
# nothing leaves TableGnostic in a form that could be redistributed.

_FORBIDDEN_SETTINGS_BY_SYSTEM: Dict[str, List[str]] = {
    # Cypher System Creator — these three settings are NOT licensed for
    # Creator-distributed content per the published Creator agreement.
    "cypher": ["Numenera", "The Strange", "No Thank You, Evil!",
               "no thank you evil", "no thank you, evil"],
}


def _setting_violates_licence(system_id: str, setting_name: str) -> Optional[str]:
    """Return the matching forbidden-setting string if there's a violation,
    otherwise None. Match is case-insensitive substring (so "A Numenera
    homebrew" or "the Strange but darker" both trip the gate)."""
    if not setting_name:
        return None
    forbidden = _FORBIDDEN_SETTINGS_BY_SYSTEM.get(system_id) or []
    haystack = setting_name.lower()
    for f in forbidden:
        if f.lower() in haystack:
            return f
    return None


_LICENCE_GATE_BLURBS: Dict[str, str] = {
    "cypher": (
        "PDF EXPORT BLOCKED — Cypher System Creator licence violation.\n\n"
        "Campaign setting \"{setting}\" matches a setting that the Cypher "
        "System Creator programme explicitly forbids for Creator-distributed "
        "content: {forbidden}. Per the licence (Monte Cook Games, LLC), "
        "Creators may NOT publish or distribute content for the Numenera, "
        "The Strange, or No Thank You, Evil! settings.\n\n"
        "You can still run this campaign inside Table-Gnostic — the in-app "
        "tables, sessions, dice, and Knowledge Web all continue to work. "
        "Only PDF export is blocked because exports are the surface that "
        "could be redistributed.\n\n"
        "If you intended to run a Creator-eligible setting "
        "(Godforsaken / Gods of the Fall / Masters of the Night / "
        "Predation / The Heartwood / The Revel / Unmasked), update the "
        "campaign's Setting Name in the Atelier to that name and re-export."
    ),
}


@router.get("/campaigns/{cid}/export.pdf")
async def export_pdf(cid: str, mode: str = "campaign",
                     user: dict = Depends(get_current_user)):
    """GM/admin downloads a chronicle PDF.

    mode = "campaign"  (default) — branded chronicle. Subject to per-system
                                   licence gating (Cypher forbidden-settings
                                   block the export with HTTP 451).
    mode = "narrative" — pure-prose narrative story export. Bypasses the
                         licence gate (no system trade dress, no claim of
                         publishable product). The PDF carries a verbatim
                         "Narrative story only — not a licensable product"
                         banner. Voice is omnipotent / setting-aware.
    """
    camp = await db.campaigns.find_one({"id": cid}, {"_id": 0})
    if not camp:
        raise HTTPException(404, "Campaign not found")
    if camp["gm_id"] != user["id"] and user.get("role") != "admin":
        raise HTTPException(403, "GM/admin only.")
    sys_id = camp.get("system_id") or "besm-4e"
    is_narrative = (mode or "").lower() == "narrative"
    # Per-licence setting gate — only enforced in branded "campaign" mode.
    # Narrative mode is by definition NOT a sellable product, so the
    # forbidden-setting block does not apply.
    if not is_narrative:
        forbidden_match = _setting_violates_licence(sys_id, camp.get("setting_name") or "")
        if forbidden_match:
            blurb = _LICENCE_GATE_BLURBS.get(sys_id, "PDF export not permitted.").format(
                setting=camp.get("setting_name", ""), forbidden=forbidden_match,
            )
            raise HTTPException(status_code=451, detail=blurb)
    sessions = await db.sessions.find({"campaign_id": cid}, {"_id": 0}) \
                                 .sort("created_at", 1).to_list(60)
    if not sessions:
        raise HTTPException(400, "No sessions to export.")
    profile = _narrative_profile(sys_id) if is_narrative else _profile_for(camp.get("system_id"))
    chapters_data = _group_sessions_into_chapters(sessions)
    # Hydrate each session with its narrative + journals.
    for ch in chapters_data:
        for s in ch["sessions"]:
            narrative, journals = await _session_prose(s, cid)
            s["_narrative"] = narrative
            s["_journals"] = journals
    # Look up the campaign's GM user (preferred byline_name, fall back to
    # name) so the cover + page footer can credit a real human.
    gm_user = await db.users.find_one({"id": camp.get("gm_id")},
                                       {"_id": 0, "byline_name": 1, "name": 1, "email": 1})
    # Hydrate extras: shared codex nodes, published characters, GM-editable
    # campaign reference. All are filtered to be safe-to-publish.
    nodes = await db.nodes.find(
        {"campaign_id": cid, "visibility": "shared"}, {"_id": 0}
    ).sort("title", 1).to_list(500)
    chars = await db.characters.find(
        {"campaign_id": cid, "published": True}, {"_id": 0}
    ).sort("name", 1).to_list(50)
    refs = await db.campaign_reference.find(
        {"campaign_id": cid}, {"_id": 0}
    ).sort("kind", 1).to_list(500)
    extras = {"nodes": nodes, "characters": chars, "reference": refs}
    # V6.10 — chronicle bundle expansion: timeline pins + chat transcripts.
    timeline_markers = await db.timeline_markers.find(
        {"campaign_id": cid}, {"_id": 0}
    ).sort("created_at", 1).to_list(500)
    chat_logs_by_session = {}
    for s in sessions:
        sid = s["id"]
        logs = await db.chat_logs.find(
            {"session_id": sid}, {"_id": 0}
        ).sort("created_at", 1).to_list(500)
        if logs:
            chat_logs_by_session[sid] = logs
    extras["timeline_markers"] = timeline_markers
    extras["chat_logs_by_session"] = chat_logs_by_session
    extras["sessions_for_timeline"] = sessions
    pdf_bytes = _build_pdf(camp, chapters_data, profile, gm_user, extras)
    # Header values must be latin-1 safe; strip non-ASCII from filename.
    raw_name = (camp.get("name") or "campaign").replace(" ", "_")
    safe = "".join(ch if ord(ch) < 128 and ch not in '"\\' else "_" for ch in raw_name)
    fname = f"{safe.strip('_') or 'campaign'}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )
