"""V6.19 — Per-level class progression timeline + proficiency block.

Surfaces, for any class+level pair, the cumulative list of features /
proficiencies / spell-known counts unlocked from level 1 to current.
Used by:
  - Character sheet "Granted at this level" timeline component
  - Pending-ticket compliance pre-flight (sanity-check spell counts)
  - Reference page (left-rail Class section auto-populates by class)

In-house authored summaries — no rulebook prose verbatim. Values come
from the SRD 5.1 class tables and the Anime 5E core class chassis (p.42-60).
"""
from __future__ import annotations
from typing import Any, Dict, List


# Compact per-class progression. Each class lists per-level grants:
#   level 1 grants: hit dice, save proficiencies, weapon/armor profs,
#                   skill picks, starting features.
#   level N grants: incremental features only.
# This is summary text — for detail the reference page links out.
CLASS_PROGRESSION: Dict[str, Dict[str, Any]] = {
    "Artificer": {
        "hit_die": "1d8",
        "save_profs": ["Constitution", "Intelligence"],
        "armor_profs": ["Light armor", "Medium armor", "Shields"],
        "weapon_profs": ["Simple weapons", "Hand crossbows", "Heavy crossbows"],
        "tool_profs_default": ["Thieves' tools", "Tinker's tools",
                                "+1 artisan tool of your choice"],
        "skill_choices": "2 from Arcana, History, Investigation, Medicine, Nature, Perception, Sleight of Hand",
        "spell_progression": "half_caster",
        "levels": {
            1: ["Magical Tinkering — turn 1-lb objects into magic-light/sound novelties.",
                "Spellcasting — Intelligence-based, Artificer spell list."],
            2: ["Infuse Item — 2 infusions known, 2 active (e.g. +1 weapon, bag of holding-equiv)."],
            3: ["Subclass — choose Alchemist / Artillerist / Battle Smith.",
                "The Right Tool for the Job — fabricate any artisan tool in 1 hour."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Subclass feature (e.g. Alchemical Savant / Arcane Firearm / Extra Attack).",
                "Artificer cantrips: 2 known."],
            6: ["Tool Expertise — double proficiency on tool checks.",
                "Subclass feature."],
            7: ["Flash of Genius — reaction, +INT to ally save/check 1/long rest."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Subclass feature."],
            10: ["Magic Item Adept — attune to 4 items max, faster crafting."],
        },
    },
    "Wizard": {
        "hit_die": "1d6",
        "save_profs": ["Intelligence", "Wisdom"],
        "armor_profs": [],
        "weapon_profs": ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light crossbows"],
        "tool_profs_default": [],
        "skill_choices": "2 from Arcana, History, Insight, Investigation, Medicine, Religion",
        "spell_progression": "full_caster",
        "levels": {
            1: ["Spellcasting — Intelligence-based, Wizard spell list.",
                "Arcane Recovery — once/day on short rest, recover slots equal to ½ wizard level."],
            2: ["Arcane Tradition (subclass) — pick School of Evocation / Abjuration / etc."],
            3: ["2nd-level slots."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["3rd-level slots."],
            6: ["Subclass feature."],
            7: ["4th-level slots."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["5th-level slots."],
            10: ["Subclass feature."],
        },
    },
    "Fighter": {
        "hit_die": "1d10",
        "save_profs": ["Strength", "Constitution"],
        "armor_profs": ["All armor", "Shields"],
        "weapon_profs": ["Simple weapons", "Martial weapons"],
        "tool_profs_default": [],
        "skill_choices": "2 from Acrobatics, Animal Handling, Athletics, History, Insight, Intimidation, Perception, Survival",
        "spell_progression": "none",
        "levels": {
            1: ["Fighting Style — pick 1 of 6 (Archery / Defense / Dueling / GWF / Protection / TWF).",
                "Second Wind — bonus action, 1d10+level HP, 1/short rest."],
            2: ["Action Surge — 1 extra action, 1/short rest."],
            3: ["Martial Archetype (subclass) — Champion / Battle Master / Eldritch Knight."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack — 2 attacks per Attack action."],
            6: ["Ability Score Improvement (or feat) [Fighter bonus]."],
            7: ["Subclass feature."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Indomitable — re-roll 1 failed save 1/long rest."],
            10: ["Subclass feature."],
        },
    },
    # Anime 5E originals (chassis is D&D-5E-flavoured):
    "Adept": {
        "hit_die": "1d8",
        "save_profs": ["Wisdom", "Charisma"],
        "armor_profs": ["Light armor"],
        "weapon_profs": ["Simple weapons", "Martial finesse weapons"],
        "tool_profs_default": ["Calligrapher's set OR meditation kit"],
        "skill_choices": "2 from Arcana, Insight, Perception, Persuasion, Religion",
        "spell_progression": "full_caster",
        "levels": {
            1: ["Spellcasting — Wisdom-based, Adept spell list.",
                "Inner Focus — bonus action, +CHA mod to next save 1/short rest."],
            2: ["Psychic Surge — overload a check or spell-attack 1/short rest (1d6, burnout on nat-1)."],
            3: ["Subclass — Way of the Empath / Way of the Aether."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["3rd-level slots."],
        },
    },
    "Idol": {
        "hit_die": "1d8",
        "save_profs": ["Charisma", "Constitution"],
        "armor_profs": ["Light armor"],
        "weapon_profs": ["Simple weapons", "Hand crossbows", "Whips", "Concert mics-as-improvised"],
        "tool_profs_default": ["Disguise kit", "Choose 1 musical instrument"],
        "skill_choices": "3 from Acrobatics, Athletics, Performance, Persuasion, Sleight of Hand",
        "spell_progression": "half_caster",
        "levels": {
            1: ["Spellcasting — Charisma-based, Idol spell list.",
                "Charm Anthem — bonus action, target one creature within 30 ft, advantage on next CHA roll."],
            2: ["Idol Reserve — gain temp HP equal to CHA + idol level on Performance success 1/short rest."],
            3: ["Subclass — Stage Maven / Idol of Hope."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Encore Performance — heal allies who hear you for CHA × prof bonus 1/long rest."],
        },
    },
    "Pilot": {
        "hit_die": "1d10",
        "save_profs": ["Dexterity", "Intelligence"],
        "armor_profs": ["Light armor", "Medium armor", "Mecha-frame armor"],
        "weapon_profs": ["Simple weapons", "Vehicle-mounted weapons"],
        "tool_profs_default": ["Vehicles (mecha)", "Tinker's tools"],
        "skill_choices": "2 from Athletics, Investigation, Perception, Piloting, Tech",
        "spell_progression": "none",
        "levels": {
            1: ["Sortie Lock — bond with 1 mecha/vehicle; +PB to vehicle attacks; cockpit darkvision.",
                "Manoeuvre die — d6, fuels Pilot tactics."],
            2: ["Vehicle Action Surge — extra action while bonded 1/short rest."],
            3: ["Subclass — Sortie Specialist / Mecha Knight."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack — 2 vehicle attacks per Attack action."],
        },
    },
    "Tinker": {
        "hit_die": "1d8",
        "save_profs": ["Constitution", "Intelligence"],
        "armor_profs": ["Light armor", "Medium armor"],
        "weapon_profs": ["Simple weapons", "Hand crossbows"],
        "tool_profs_default": ["Tinker's tools", "+2 artisan tools of your choice"],
        "skill_choices": "2 from Arcana, History, Investigation, Medicine, Sleight of Hand",
        "spell_progression": "half_caster",
        "levels": {
            1: ["Spellcasting — Intelligence-based, Tinker spell list.",
                "Improvised Gadget — fabricate a 1-shot gadget once/short rest."],
            2: ["Infuse Item — 2 infusions known, 2 active."],
            3: ["Subclass — Alchemist / Artillerist / Battle Smith."],
            4: ["Concoct Cypher — fabricate a single-use cypher gadget (1 hour, 25gp parts)."],
            5: ["Subclass feature."],
        },
    },
    # Add Cypher Type / Focus progression separately (different paradigm).

    # ─── V6.22 PHB 5E expansion ──────────────────────────────────────
    "Barbarian": {
        "hit_die": "1d12",
        "save_profs": ["Strength", "Constitution"],
        "armor_profs": ["Light armor", "Medium armor", "Shields"],
        "weapon_profs": ["Simple weapons", "Martial weapons"],
        "tool_profs_default": [],
        "skill_choices": "2 from Animal Handling, Athletics, Intimidation, Nature, Perception, Survival",
        "spell_progression": "none",
        "levels": {
            1: ["Rage — 2/long rest; +2 dmg to STR melee; advantage on STR checks/saves; resistance to b/p/s.",
                "Unarmored Defense — AC = 10 + DEX + CON when no armor."],
            2: ["Reckless Attack — advantage on STR melee, attacks against you have advantage.",
                "Danger Sense — advantage on DEX saves vs. effects you see."],
            3: ["Primal Path subclass (Berserker / Totem Warrior / Zealot / …)."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack.",
                "Fast Movement — +10 ft speed when unarmored."],
            6: ["Path feature."],
            7: ["Feral Instinct — advantage on initiative; cancel rage-restriction on surprise."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Brutal Critical — +1 weapon die on crit."],
            10: ["Path feature."],
        },
    },
    "Bard": {
        "hit_die": "1d8",
        "save_profs": ["Dexterity", "Charisma"],
        "armor_profs": ["Light armor"],
        "weapon_profs": ["Simple weapons", "Hand crossbows", "Longswords",
                          "Rapiers", "Shortswords"],
        "tool_profs_default": ["3 musical instruments of your choice"],
        "skill_choices": "Any 3 skills",
        "spell_progression": "full_caster",
        "levels": {
            1: ["Spellcasting — Charisma-based, Bard spell list; rituals.",
                "Bardic Inspiration (d6) — bonus action; CHA-mod uses/long rest."],
            2: ["Jack of All Trades — ½ prof on non-proficient ability checks.",
                "Song of Rest (d6) — short-rest healing bonus."],
            3: ["Bard College subclass (Lore / Valor / Eloquence / Glamour / …).",
                "Expertise — 2 skills."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Bardic Inspiration (d8).",
                "Font of Inspiration — regain Inspiration on short rest too."],
            6: ["College feature.",
                "Countercharm — action, advantage on frightened/charmed saves for allies in range."],
            7: ["4th-level slots."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Song of Rest (d8).",
                "5th-level slots."],
            10: ["Bardic Inspiration (d10).",
                 "Expertise — 2 more skills.",
                 "Magical Secrets — learn 2 spells from any class."],
        },
    },
    "Cleric": {
        "hit_die": "1d8",
        "save_profs": ["Wisdom", "Charisma"],
        "armor_profs": ["Light armor", "Medium armor", "Shields"],
        "weapon_profs": ["Simple weapons"],
        "tool_profs_default": [],
        "skill_choices": "2 from History, Insight, Medicine, Persuasion, Religion",
        "spell_progression": "full_caster",
        "levels": {
            1: ["Spellcasting — Wisdom-based, Cleric spell list; rituals.",
                "Divine Domain subclass (Life / Light / War / Trickery / Knowledge / Nature / Tempest / …).",
                "Domain features — varies (bonus proficiencies, bonus spells, 1st-level feature)."],
            2: ["Channel Divinity — Turn Undead + 1 domain option; 1/short rest."],
            3: ["2nd-level slots."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Destroy Undead (CR ½).",
                 "3rd-level slots."],
            6: ["Channel Divinity — 2/short rest.",
                 "Domain feature."],
            7: ["4th-level slots."],
            8: ["Ability Score Improvement (or feat).",
                 "Destroy Undead (CR 1).",
                 "Domain feature (often a damage boost to cantrip / WIS-mod dmg)."],
            9: ["5th-level slots."],
            10: ["Divine Intervention — once/long rest, pray for domain aid."],
        },
    },
    "Druid": {
        "hit_die": "1d8",
        "save_profs": ["Intelligence", "Wisdom"],
        "armor_profs": ["Light armor (non-metal)", "Medium armor (non-metal)",
                         "Shields (non-metal)"],
        "weapon_profs": ["Clubs", "Daggers", "Darts", "Javelins", "Maces",
                          "Quarterstaffs", "Scimitars", "Sickles", "Slings", "Spears"],
        "tool_profs_default": ["Herbalism kit"],
        "skill_choices": "2 from Arcana, Animal Handling, Insight, Medicine, Nature, Perception, Religion, Survival",
        "spell_progression": "full_caster",
        "levels": {
            1: ["Druidic — secret language.",
                "Spellcasting — Wisdom-based, Druid spell list; rituals."],
            2: ["Wild Shape — 2/short rest; CR ¼, no fly/swim.",
                "Druid Circle subclass (Land / Moon / Shepherd / Spores / …).",
                "Circle feature."],
            3: ["2nd-level slots."],
            4: ["Wild Shape — CR ½ (no fly); now swim.",
                 "Ability Score Improvement (or feat)."],
            5: ["3rd-level slots."],
            6: ["Circle feature."],
            7: ["4th-level slots."],
            8: ["Wild Shape — CR 1 (now fly).",
                 "Ability Score Improvement (or feat)."],
            9: ["5th-level slots."],
            10: ["Circle feature."],
        },
    },
    "Monk": {
        "hit_die": "1d8",
        "save_profs": ["Strength", "Dexterity"],
        "armor_profs": [],
        "weapon_profs": ["Simple weapons", "Shortswords"],
        "tool_profs_default": ["1 artisan tool or 1 musical instrument of your choice"],
        "skill_choices": "2 from Acrobatics, Athletics, History, Insight, Religion, Stealth",
        "spell_progression": "none",
        "levels": {
            1: ["Unarmored Defense — AC = 10 + DEX + WIS.",
                "Martial Arts — 1d4 unarmed, DEX for monk weapons, bonus-action unarmed."],
            2: ["Ki — 2 points; Flurry of Blows / Patient Defense / Step of the Wind.",
                "Unarmored Movement — +10 ft speed."],
            3: ["Monastic Tradition subclass (Open Hand / Shadow / Four Elements / Mercy / …).",
                "Deflect Missiles — reaction, reduce ranged damage."],
            4: ["Ability Score Improvement (or feat).",
                "Slow Fall."],
            5: ["Extra Attack.",
                 "Stunning Strike — spend Ki point to stun (CON save)."],
            6: ["Ki-Empowered Strikes — unarmed count as magical.",
                 "Tradition feature."],
            7: ["Evasion — take 0 dmg on successful DEX save, half on fail.",
                 "Stillness of Mind — action, end charm/fear on self."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Unarmored Movement — climb sheer + short-run over liquid."],
            10: ["Purity of Body — immune to disease/poison.",
                 "Martial Arts dice: 1d6."],
        },
    },
    "Paladin": {
        "hit_die": "1d10",
        "save_profs": ["Wisdom", "Charisma"],
        "armor_profs": ["All armor", "Shields"],
        "weapon_profs": ["Simple weapons", "Martial weapons"],
        "tool_profs_default": [],
        "skill_choices": "2 from Athletics, Insight, Intimidation, Medicine, Persuasion, Religion",
        "spell_progression": "half_caster",
        "levels": {
            1: ["Divine Sense — 1 + CHA-mod/long rest.",
                "Lay on Hands — pool = 5 × paladin level."],
            2: ["Fighting Style — pick 1 (Defense / Dueling / Great Weapon / Protection / …).",
                "Spellcasting — Charisma-based, Paladin spell list.",
                "Divine Smite — spend slot, +2d8 radiant (+1d8 per slot level above 1st)."],
            3: ["Divine Health — immune to disease.",
                "Sacred Oath subclass (Devotion / Ancients / Vengeance / Crown / Redemption / …)."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack."],
            6: ["Aura of Protection — +CHA-mod to saves for self + allies within 10 ft."],
            7: ["Oath feature (aura)."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["3rd-level slots."],
            10: ["Aura of Courage — self + allies within 10 ft can't be frightened."],
        },
    },
    "Ranger": {
        "hit_die": "1d10",
        "save_profs": ["Strength", "Dexterity"],
        "armor_profs": ["Light armor", "Medium armor", "Shields"],
        "weapon_profs": ["Simple weapons", "Martial weapons"],
        "tool_profs_default": [],
        "skill_choices": "3 from Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, Survival",
        "spell_progression": "half_caster",
        "levels": {
            1: ["Favored Enemy — advantage on survival vs. a type + related INT checks.",
                "Natural Explorer — pick a favored terrain (double prof WIS/INT, ignore difficult terrain, etc.)."],
            2: ["Fighting Style (Archery / Defense / Dueling / TWF).",
                "Spellcasting — Wisdom-based, Ranger spell list."],
            3: ["Ranger Conclave subclass (Hunter / Beast Master / Gloom Stalker / Fey Wanderer / …).",
                "Primeval Awareness — spend slot to sense creature-type presence."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack."],
            6: ["Second favored enemy + favored terrain."],
            7: ["Conclave feature."],
            8: ["Ability Score Improvement (or feat).",
                 "Land's Stride — ignore nonmagical difficult terrain; advantage vs. plant effects."],
            9: ["3rd-level slots."],
            10: ["Hide in Plain Sight — 10-min camouflage; +10 to Stealth if unmoving.",
                 "Third favored terrain."],
        },
    },
    "Rogue": {
        "hit_die": "1d8",
        "save_profs": ["Dexterity", "Intelligence"],
        "armor_profs": ["Light armor"],
        "weapon_profs": ["Simple weapons", "Hand crossbows", "Longswords",
                          "Rapiers", "Shortswords"],
        "tool_profs_default": ["Thieves' tools"],
        "skill_choices": "4 from Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, Stealth",
        "spell_progression": "none",
        "levels": {
            1: ["Expertise — 2 skills or 1 skill + thieves' tools (double prof).",
                "Sneak Attack — 1d6 extra once/turn on advantage/ally-adjacent.",
                "Thieves' Cant — secret language."],
            2: ["Cunning Action — bonus-action Dash / Disengage / Hide."],
            3: ["Roguish Archetype subclass (Thief / Assassin / Arcane Trickster / Swashbuckler / Inquisitive / …).",
                "Sneak Attack 2d6."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Uncanny Dodge — reaction, halve damage from one attack.",
                 "Sneak Attack 3d6."],
            6: ["Expertise — 2 more."],
            7: ["Evasion — 0 dmg on successful DEX save.",
                 "Sneak Attack 4d6."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Archetype feature.",
                 "Sneak Attack 5d6."],
            10: ["Ability Score Improvement (or feat)."],
        },
    },
    "Sorcerer": {
        "hit_die": "1d6",
        "save_profs": ["Constitution", "Charisma"],
        "armor_profs": [],
        "weapon_profs": ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light crossbows"],
        "tool_profs_default": [],
        "skill_choices": "2 from Arcana, Deception, Insight, Intimidation, Persuasion, Religion",
        "spell_progression": "full_caster",
        "levels": {
            1: ["Sorcerous Origin subclass (Draconic / Wild Magic / Clockwork / Divine Soul / Shadow / Storm / …).",
                "Spellcasting — Charisma-based, Sorcerer spell list."],
            2: ["Font of Magic — 2 sorcery points.",
                "Flexible Casting — convert points↔slots."],
            3: ["Metamagic — 2 options (Careful / Distant / Empowered / Extended / Heightened / Quickened / Seeking / Subtle / Twinned)."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["3rd-level slots."],
            6: ["Origin feature."],
            7: ["4th-level slots."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["5th-level slots."],
            10: ["Metamagic — 1 more option.",
                 "Origin feature."],
        },
    },
    "Warlock": {
        "hit_die": "1d8",
        "save_profs": ["Wisdom", "Charisma"],
        "armor_profs": ["Light armor"],
        "weapon_profs": ["Simple weapons"],
        "tool_profs_default": [],
        "skill_choices": "2 from Arcana, Deception, History, Intimidation, Investigation, Nature, Religion",
        "spell_progression": "pact_caster",  # unique Pact Magic recovery
        "levels": {
            1: ["Otherworldly Patron subclass (Archfey / Fiend / Great Old One / Celestial / Hexblade / Genie / …).",
                "Pact Magic — 1 slot max at this tier, short-rest recovery."],
            2: ["Eldritch Invocations — 2 known (Agonizing Blast / Devil's Sight / Eldritch Spear / …)."],
            3: ["Pact Boon — Pact of the Blade / Chain / Tome / Talisman."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["3rd-level Pact slots (2 slots)."],
            6: ["Patron feature."],
            7: ["4th-level Pact slots."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["5th-level Pact slots."],
            10: ["Patron feature.",
                 "More invocations known."],
        },
    },

    # ─── V6.22 Anime 5E specialty classes ────────────────────────────
    # Anime 5E core book p.60-108. Chassis approximation; subclasses
    # (e.g. Sentai colour, Mech frame) are picked at L3 via the standard
    # subclass-wizard.
    "Magical Girl": {
        "hit_die": "1d8",
        "save_profs": ["Wisdom", "Charisma"],
        "armor_profs": [],
        "weapon_profs": ["Simple weapons", "Transformation weapon (signature)"],
        "tool_profs_default": ["Disguise kit"],
        "skill_choices": "2 from Insight, Performance, Persuasion, Religion, Arcana",
        "spell_progression": "full_caster",  # Charisma-based, Magical Girl list
        "levels": {
            1: ["Henshin — bonus-action transformation grants +CHA-mod temp HP and signature weapon.",
                "Spellcasting — Charisma-based, Magical Girl spell list (Heart / Star / Moon themes)."],
            2: ["Friendship Is Power — reaction, spend slot to grant ally advantage + heal CHA-mod."],
            3: ["Magical Girl Archetype subclass (Heart / Star / Moon / Shadow / Tech).",
                "Sparkling Finisher — 1/long rest, spend 2nd-level slot for radiant-burst."],
            4: ["Ability Score Improvement (or feat).",
                "Henshin now grants flight 30 ft while transformed."],
            5: ["Extra Attack (signature weapon)."],
            6: ["Archetype feature.",
                "Group Henshin — transform up to 3 allies for 1 min (reduced bonus)."],
            7: ["Purifying Light — action, end charm/curse on ally (spend slot)."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Archetype feature.",
                "5th-level slots."],
            10: ["Hope Burns Bright — 1/long rest, drop to 1 HP instead of 0 and regain slot."],
        },
    },
    "Mech Pilot": {
        "hit_die": "1d10",
        "save_profs": ["Intelligence", "Strength"],
        "armor_profs": ["Light armor", "Medium armor", "Mech frame (signature)"],
        "weapon_profs": ["Simple weapons", "Martial weapons",
                          "Mecha weapon systems"],
        "tool_profs_default": ["Tinker's tools", "Vehicles (land/air)"],
        "skill_choices": "2 from Athletics, Investigation, Perception, Arcana, Survival",
        "spell_progression": "none",
        "levels": {
            1: ["Mech Frame — signature mecha with own HP, AC, speed, and systems (2 hardpoints).",
                "Cockpit Focus — DEX+INT control rolls; can't be surprised while seated."],
            2: ["Hardpoint Retrofit — swap one mecha weapon per short rest."],
            3: ["Frame Archetype subclass (Striker / Bulwark / Scout / Arcane-Fused / Colossus).",
                "Overdrive — 1/long rest, double mecha speed + +2d6 dmg for 1 min."],
            4: ["Ability Score Improvement (or feat).",
                "Pilot Sync — mecha reactions use your reaction."],
            5: ["Extra Attack (mecha weapons).",
                "Frame feature."],
            6: ["Bailout — reaction, auto-eject from crippled mecha; half-fall damage."],
            7: ["Third hardpoint slot."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Frame feature.",
                "Adaptive AI — +PB to one saving throw while piloted."],
            10: ["Combination Attack — stack your attack roll w/ an adjacent ally's."],
        },
    },
    "Sentai": {
        "hit_die": "1d10",
        "save_profs": ["Strength", "Charisma"],
        "armor_profs": ["Light armor", "Medium armor", "Shields"],
        "weapon_profs": ["Simple weapons", "Martial weapons",
                          "Team signature weapon"],
        "tool_profs_default": [],
        "skill_choices": "2 from Acrobatics, Athletics, Intimidation, Performance, Persuasion",
        "spell_progression": "none",
        "levels": {
            1: ["Morph — bonus-action morph grants +PB temp HP & colored uniform.",
                "Team Pose — allies w/in 30 ft gain +1 AC until start of your next turn."],
            2: ["Finishing Strike — 1/short rest, +PB weapon dice on a hit."],
            3: ["Sentai Color subclass (Red / Blue / Yellow / Pink / Black / Green).",
                "Rallying Cry — bonus-action, 1 ally regains HP = 1d6 + PB."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack.",
                "Colored Weapon Upgrade (from subclass)."],
            6: ["Color feature."],
            7: ["Combine Attack — GM may pair morphs; 3+ Sentai allies can fuse into a Megazord (30 ft team construct, 1/long rest)."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Color feature."],
            10: ["Team Resilience — 1/short rest, allies w/in 30 ft re-roll a failed save."],
        },
    },
    "Esper": {
        "hit_die": "1d6",
        "save_profs": ["Intelligence", "Wisdom"],
        "armor_profs": [],
        "weapon_profs": ["Simple weapons"],
        "tool_profs_default": [],
        "skill_choices": "3 from Arcana, Insight, Investigation, Medicine, Perception, Religion",
        "spell_progression": "full_caster",  # Psionic Power (Int or Wis)
        "levels": {
            1: ["Psionic Awakening — pick casting stat (INT or WIS); learn 2 disciplines.",
                "Mind's Shield — +PB to mental saves 1/short rest.",
                "Spellcasting — Psionic disciplines list."],
            2: ["Psychic Focus — spend slot, boost a stat check +d6."],
            3: ["Esper Path subclass (Telepath / Psychokinetic / Nomad / Awakened / …).",
                "Read Mind — cast detect thoughts as a ritual 1/long rest."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["3rd-level slots.",
                "Telekinetic Grasp — AoE push/pull as a bonus action."],
            6: ["Path feature."],
            7: ["Psionic Shift — reaction, teleport 10 ft when hit."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["5th-level slots."],
            10: ["Mental Fortress — immune to charm, advantage on fear saves."],
        },
    },
    "Demihuman": {
        # An Anime 5E chassis for player characters whose 'class' IS their
        # heritage (kitsune swordsman, oni berserker, nekomata scout).
        # Subclass at L3 picks the heritage's combat expression.
        "hit_die": "1d10",
        "save_profs": ["Dexterity", "Charisma"],
        "armor_profs": ["Light armor"],
        "weapon_profs": ["Simple weapons", "Martial weapons"],
        "tool_profs_default": [],
        "skill_choices": "3 from Acrobatics, Athletics, Nature, Perception, Stealth, Survival",
        "spell_progression": "half_caster",  # heritage magic
        "levels": {
            1: ["Heritage Gift — trait derived from race (tail/wings/horns grant flavour feature: +10 ft swim, darkvision 60, scent, etc.).",
                "Unarmored Defense — AC = 10 + DEX + CHA."],
            2: ["Bestial Instinct — advantage on tracking WIS(Survival) + Initiative."],
            3: ["Heritage Path subclass (Kitsune-Sage / Oni-Brawler / Nekomata-Dancer / Tengu-Scout / Naga-Whisperer / Centaur-Charger).",
                "Spellcasting — Charisma-based, heritage-flavored spell list."],
            4: ["Ability Score Improvement (or feat)."],
            5: ["Extra Attack.",
                "Heritage feature."],
            6: ["Blood Call — once/short rest, gain resistance to one damage type for 1 min (tied to heritage)."],
            7: ["Heritage feature."],
            8: ["Ability Score Improvement (or feat)."],
            9: ["Heritage feature."],
            10: ["Ancestral Guidance — 1/long rest commune with a spirit of your lineage (guidance on a decision + +2d6 ancestor bonus dmg on next hit)."],
        },
    },
}


def cumulative_features(class_name: str, level: int) -> Dict[str, Any]:
    """Return cumulative features unlocked from level 1 to `level`.

    Strips parenthetical (e.g. 'Artificer (Alchemist)' → 'Artificer').
    Returns `{class, level, hit_die, save_profs, armor_profs, weapon_profs,
              tool_profs, skill_choices, spell_progression, timeline}`
    where `timeline` is `[{level, features: [...]}]` from level 1 to `level`.
    """
    base = (class_name or "").split("(")[0].strip()
    prog = CLASS_PROGRESSION.get(base)
    if not prog:
        return {
            "class": base, "level": level, "known": False,
            "timeline": [],
            "hit_die": "?",
            "save_profs": [], "armor_profs": [], "weapon_profs": [],
            "tool_profs": [], "skill_choices": "",
            "spell_progression": "unknown",
            "advice": (
                f"Class '{base}' has no canonical progression in the V6.19 "
                f"library — add a homebrew custom class entry via the "
                f"Atelier · References tab (kind: 'custom_class')."
            ),
        }
    timeline: List[Dict[str, Any]] = []
    lvl = max(1, int(level or 1))
    for L in range(1, lvl + 1):
        if L in prog["levels"]:
            timeline.append({"level": L, "features": prog["levels"][L]})
    return {
        "class": base,
        "level": lvl,
        "known": True,
        "hit_die": prog["hit_die"],
        "save_profs": prog["save_profs"],
        "armor_profs": prog["armor_profs"],
        "weapon_profs": prog["weapon_profs"],
        "tool_profs": prog["tool_profs_default"],
        "skill_choices": prog["skill_choices"],
        "spell_progression": prog["spell_progression"],
        "timeline": timeline,
    }
