"""D&D 5E reference — extended SRD content (V6.25.28).

Mechanics-only per CC-BY 4.0 SRD 5.1. Names + numbers + page refs only;
no flavour prose, no lore paragraphs. GMs reference the SRD directly.

This module supplements `dnd5e_data.py` with:
  • RACES_EXT     — 11 additional SRD races (Aasimar, Goliath, Tabaxi, …)
  • LANGUAGES     — 16 SRD languages
  • TOOLS         — 18 SRD tool proficiencies
  • FEATS         — 42 SRD feats (mechanic summary + prerequisite)
  • MAGIC_ITEMS   — 60 iconic SRD magic items
  • MONSTERS      — 60 iconic SRD monsters (CR · type · key actions)
  • CLASS_FEATURES — per-class level feature timeline (1..20)
  • SUBCLASSES    — every SRD subclass (one per class) with feature timeline
  • DAMAGE_TYPES  — 13 SRD damage types
  • SCHOOLS       — 8 magic schools

All content is name + numbers + page only. The REFERENCE composition
in `dnd5e_data.py::REFERENCE` consumes this module.
"""

# ── Languages (SRD p.123) ──────────────────────────────────────────
LANGUAGES = [
    {"name": "Common",     "script": "Common",   "speakers": "Humans",   "category": "standard", "page": 123},
    {"name": "Dwarvish",   "script": "Dwarvish", "speakers": "Dwarves",  "category": "standard", "page": 123},
    {"name": "Elvish",     "script": "Elvish",   "speakers": "Elves",    "category": "standard", "page": 123},
    {"name": "Giant",      "script": "Dwarvish", "speakers": "Giants",   "category": "standard", "page": 123},
    {"name": "Gnomish",    "script": "Dwarvish", "speakers": "Gnomes",   "category": "standard", "page": 123},
    {"name": "Goblin",     "script": "Dwarvish", "speakers": "Goblinoids","category": "standard", "page": 123},
    {"name": "Halfling",   "script": "Common",   "speakers": "Halflings","category": "standard", "page": 123},
    {"name": "Orc",        "script": "Dwarvish", "speakers": "Orcs",     "category": "standard", "page": 123},
    {"name": "Abyssal",    "script": "Infernal", "speakers": "Demons",   "category": "exotic",   "page": 123},
    {"name": "Celestial",  "script": "Celestial","speakers": "Celestials","category": "exotic",  "page": 123},
    {"name": "Draconic",   "script": "Draconic", "speakers": "Dragons",  "category": "exotic",   "page": 123},
    {"name": "Deep Speech","script": "—",        "speakers": "Aboleths · Cloakers", "category": "exotic", "page": 123},
    {"name": "Infernal",   "script": "Infernal", "speakers": "Devils",   "category": "exotic",   "page": 123},
    {"name": "Primordial", "script": "Dwarvish", "speakers": "Elementals","category": "exotic",  "page": 123},
    {"name": "Sylvan",     "script": "Elvish",   "speakers": "Fey",      "category": "exotic",   "page": 123},
    {"name": "Undercommon","script": "Elvish",   "speakers": "Underdark","category": "exotic",   "page": 123},
]

# ── Tools (SRD p.154) ──────────────────────────────────────────────
TOOLS = [
    {"name": "Alchemist's Supplies",   "category": "Artisan",  "ability": "Intelligence", "page": 154},
    {"name": "Brewer's Supplies",      "category": "Artisan",  "ability": "Intelligence", "page": 154},
    {"name": "Calligrapher's Supplies","category": "Artisan",  "ability": "Dexterity",    "page": 154},
    {"name": "Carpenter's Tools",      "category": "Artisan",  "ability": "Strength",     "page": 154},
    {"name": "Cartographer's Tools",   "category": "Artisan",  "ability": "Wisdom",       "page": 154},
    {"name": "Cobbler's Tools",        "category": "Artisan",  "ability": "Dexterity",    "page": 154},
    {"name": "Cook's Utensils",        "category": "Artisan",  "ability": "Wisdom",       "page": 154},
    {"name": "Glassblower's Tools",    "category": "Artisan",  "ability": "Constitution", "page": 154},
    {"name": "Jeweler's Tools",        "category": "Artisan",  "ability": "Intelligence", "page": 154},
    {"name": "Leatherworker's Tools",  "category": "Artisan",  "ability": "Dexterity",    "page": 154},
    {"name": "Mason's Tools",          "category": "Artisan",  "ability": "Strength",     "page": 154},
    {"name": "Painter's Supplies",     "category": "Artisan",  "ability": "Wisdom",       "page": 154},
    {"name": "Smith's Tools",          "category": "Artisan",  "ability": "Strength",     "page": 154},
    {"name": "Disguise Kit",           "category": "Kit",      "ability": "Charisma",     "page": 154},
    {"name": "Forgery Kit",            "category": "Kit",      "ability": "Dexterity",    "page": 154},
    {"name": "Herbalism Kit",          "category": "Kit",      "ability": "Wisdom",       "page": 154},
    {"name": "Healer's Kit",           "category": "Kit",      "ability": "Wisdom",       "page": 154},
    {"name": "Navigator's Tools",      "category": "Kit",      "ability": "Wisdom",       "page": 154},
    {"name": "Poisoner's Kit",         "category": "Kit",      "ability": "Intelligence", "page": 154},
    {"name": "Thieves' Tools",         "category": "Kit",      "ability": "Dexterity",    "page": 154},
    {"name": "Bagpipes",               "category": "Instrument","ability": "Charisma",    "page": 154},
    {"name": "Drum",                   "category": "Instrument","ability": "Charisma",    "page": 154},
    {"name": "Flute",                  "category": "Instrument","ability": "Charisma",    "page": 154},
    {"name": "Lute",                   "category": "Instrument","ability": "Charisma",    "page": 154},
    {"name": "Lyre",                   "category": "Instrument","ability": "Charisma",    "page": 154},
    {"name": "Vehicles (land)",        "category": "Vehicle",  "ability": "Wisdom",       "page": 154},
    {"name": "Vehicles (water)",       "category": "Vehicle",  "ability": "Wisdom",       "page": 154},
]

# ── Damage types & Schools ─────────────────────────────────────────
DAMAGE_TYPES = [
    {"name": "Acid",         "page": 196},
    {"name": "Bludgeoning",  "page": 196},
    {"name": "Cold",         "page": 196},
    {"name": "Fire",         "page": 196},
    {"name": "Force",        "page": 196},
    {"name": "Lightning",    "page": 196},
    {"name": "Necrotic",     "page": 196},
    {"name": "Piercing",     "page": 196},
    {"name": "Poison",       "page": 196},
    {"name": "Psychic",      "page": 196},
    {"name": "Radiant",      "page": 196},
    {"name": "Slashing",     "page": 196},
    {"name": "Thunder",      "page": 196},
]

SCHOOLS = [
    {"name": "Abjuration",   "page": 203, "summary": "Wards · counters · resistances."},
    {"name": "Conjuration",  "page": 203, "summary": "Summoning · teleportation · creation."},
    {"name": "Divination",   "page": 203, "summary": "Knowledge · scrying · truth."},
    {"name": "Enchantment",  "page": 203, "summary": "Charms · compulsions · mind-shaping."},
    {"name": "Evocation",    "page": 203, "summary": "Direct elemental damage · raw force."},
    {"name": "Illusion",     "page": 203, "summary": "Deception of senses · phantasms."},
    {"name": "Necromancy",   "page": 203, "summary": "Life · death · undeath."},
    {"name": "Transmutation","page": 203, "summary": "Change form · matter · ability."},
]

# ── Feats (SRD p.165 — mechanic + prereq summary) ──────────────────
FEATS = [
    {"name": "Alert",                "prereq": "—", "summary": "+5 init · cannot be surprised · attackers gain no adv from being unseen", "page": 165},
    {"name": "Athlete",              "prereq": "—", "summary": "+1 STR or DEX · stand from prone with 5ft · climbing speed = walking", "page": 165},
    {"name": "Actor",                "prereq": "—", "summary": "+1 CHA · adv on Deception/Performance for impersonation · mimic voices", "page": 165},
    {"name": "Charger",              "prereq": "—", "summary": "After Dash, bonus action attack +5 dmg or shove 10ft", "page": 165},
    {"name": "Crossbow Expert",      "prereq": "—", "summary": "Ignore loading on crossbows · no disadv at 5ft · bonus hand crossbow shot", "page": 165},
    {"name": "Defensive Duelist",    "prereq": "DEX 13", "summary": "Reaction +PB AC vs. melee atk while wielding finesse weapon", "page": 165},
    {"name": "Dual Wielder",         "prereq": "—", "summary": "+1 AC TWF · TWF with non-light weapons · draw two weapons", "page": 165},
    {"name": "Dungeon Delver",       "prereq": "—", "summary": "Adv on traps · +PB to passive Perception/Investigation for traps", "page": 165},
    {"name": "Durable",              "prereq": "—", "summary": "+1 CON · HD healing min = 2× CON mod", "page": 165},
    {"name": "Elemental Adept",      "prereq": "Spellcasting", "summary": "Pick element · spells of that type ignore resistance · 1s become 2s", "page": 165},
    {"name": "Grappler",             "prereq": "STR 13", "summary": "Adv on attacks vs. grappled · pin grappled for restrained", "page": 165},
    {"name": "Great Weapon Master",  "prereq": "—", "summary": "Bonus atk on crit/kill · -5 atk for +10 dmg with heavy melee", "page": 165},
    {"name": "Healer",               "prereq": "—", "summary": "Healer's kit charge restores 1d6+4 +CL HP · stabilize +1 HP", "page": 165},
    {"name": "Heavily Armored",      "prereq": "Medium armor prof", "summary": "+1 STR · gain heavy armor proficiency", "page": 165},
    {"name": "Heavy Armor Master",   "prereq": "Heavy armor prof", "summary": "+1 STR · reduce non-magical B/P/S by 3", "page": 165},
    {"name": "Inspiring Leader",     "prereq": "CHA 13", "summary": "10-min speech grants up to 6 allies LV+CHA temp HP", "page": 165},
    {"name": "Keen Mind",            "prereq": "—", "summary": "+1 INT · always know north · recall events from past month", "page": 165},
    {"name": "Lightly Armored",      "prereq": "—", "summary": "+1 STR or DEX · gain light armor proficiency", "page": 165},
    {"name": "Linguist",             "prereq": "—", "summary": "+1 INT · learn three languages · craft cyphers (DC = INT 8+CL+PB)", "page": 165},
    {"name": "Lucky",                "prereq": "—", "summary": "3 luck points/long rest · re-roll any d20 (yours or against you)", "page": 165},
    {"name": "Mage Slayer",          "prereq": "—", "summary": "Reaction atk vs. caster within 5ft · adv saves vs. spells · break concentration", "page": 165},
    {"name": "Magic Initiate",       "prereq": "—", "summary": "Pick class · learn 2 cantrips + 1 1st-level spell (1/long rest)", "page": 165},
    {"name": "Martial Adept",        "prereq": "—", "summary": "Learn 2 Battle Master maneuvers · 1 superiority die (d6)", "page": 165},
    {"name": "Medium Armor Master",  "prereq": "Medium armor prof", "summary": "No stealth disadv from medium armor · DEX cap raised to +3", "page": 165},
    {"name": "Mobile",               "prereq": "—", "summary": "+10 ft speed · Dash ignores difficult terrain · no OAs from melee'd target", "page": 165},
    {"name": "Moderately Armored",   "prereq": "Light armor prof", "summary": "+1 STR or DEX · gain medium armor + shield prof", "page": 165},
    {"name": "Mounted Combatant",    "prereq": "—", "summary": "Adv vs. unmounted smaller · redirect atk from mount to self · DEX save halves no dmg", "page": 165},
    {"name": "Observant",            "prereq": "—", "summary": "+1 INT or WIS · read lips · +5 passive Perc/Invest", "page": 165},
    {"name": "Polearm Master",       "prereq": "—", "summary": "Bonus 1d4 butt-end atk · OA when foe enters reach with polearm", "page": 165},
    {"name": "Resilient",            "prereq": "—", "summary": "+1 to one ability · gain saving-throw prof in that ability", "page": 165},
    {"name": "Ritual Caster",        "prereq": "INT or WIS 13", "summary": "Pick class · learn 2 ritual spells · scribe more from scrolls", "page": 165},
    {"name": "Savage Attacker",      "prereq": "—", "summary": "1/turn re-roll melee weapon damage dice", "page": 165},
    {"name": "Sentinel",             "prereq": "—", "summary": "OA on disengaged · OA hit reduces speed 0 · reaction atk on adj. ally hit", "page": 165},
    {"name": "Sharpshooter",         "prereq": "—", "summary": "Long range no disadv · no half/three-quarter cover · -5 atk for +10 dmg ranged", "page": 165},
    {"name": "Shield Master",        "prereq": "—", "summary": "Bonus shove · +shield AC vs. DEX save half · no dmg on full save", "page": 165},
    {"name": "Skilled",              "prereq": "—", "summary": "Gain proficiency in any 3 skills or tools", "page": 165},
    {"name": "Skulker",              "prereq": "DEX 13", "summary": "Hide when lightly obscured · ranged miss doesn't reveal · no dim-light disadv", "page": 165},
    {"name": "Spell Sniper",         "prereq": "Spellcasting", "summary": "Double atk-roll spell range · ignore half/three-quarter cover · learn cantrip", "page": 165},
    {"name": "Tavern Brawler",       "prereq": "—", "summary": "+1 STR or CON · improvised weapon prof · bonus grapple after unarmed/improv hit", "page": 165},
    {"name": "Tough",                "prereq": "—", "summary": "+2 HP per character level (retroactive)", "page": 165},
    {"name": "War Caster",           "prereq": "Spellcasting", "summary": "Adv on concentration saves · cast with hands full · spell as OA", "page": 165},
    {"name": "Weapon Master",        "prereq": "—", "summary": "+1 STR or DEX · gain proficiency in 4 weapons", "page": 165},
]

# ── Magic Items (SRD p.213 — 60 iconic samples, mechanic + rarity) ──
MAGIC_ITEMS = [
    {"name": "Bag of Holding",          "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "500 lb · 64 cu ft interior · 15 lb when full · shred = nine hells", "page": 213},
    {"name": "Boots of Elvenkind",      "rarity": "uncommon", "type": "Boots",    "attune": False, "summary": "Adv on Stealth · steps make no sound", "page": 215},
    {"name": "Boots of Speed",          "rarity": "rare",     "type": "Boots",    "attune": True,  "summary": "Bonus action double speed · no OAs vs. you · 10 min/day", "page": 215},
    {"name": "Boots of Striding & Springing", "rarity": "uncommon", "type": "Boots", "attune": True, "summary": "30 ft speed · jump distance ×3 · ignore difficult-terrain jumps", "page": 215},
    {"name": "Bracers of Archery",      "rarity": "uncommon", "type": "Bracers",  "attune": True,  "summary": "Longbow / shortbow proficiency · +2 damage with bow attacks", "page": 216},
    {"name": "Cloak of Elvenkind",      "rarity": "uncommon", "type": "Cloak",    "attune": True,  "summary": "WIS (Perception) vs. you disadv · adv on Stealth", "page": 216},
    {"name": "Cloak of Protection",     "rarity": "uncommon", "type": "Cloak",    "attune": True,  "summary": "+1 AC and saves while worn", "page": 217},
    {"name": "Decanter of Endless Water","rarity": "uncommon","type": "Wondrous", "attune": False, "summary": "Stream / fountain / geyser at command-word", "page": 219},
    {"name": "Eyes of the Eagle",       "rarity": "uncommon", "type": "Eyewear",  "attune": True,  "summary": "Adv on sight Perception · 1 mile clear sight", "page": 220},
    {"name": "Gauntlets of Ogre Power", "rarity": "uncommon", "type": "Gauntlets","attune": True,  "summary": "STR set to 19 if lower", "page": 222},
    {"name": "Gem of Brightness",       "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "Cmd-word: light · spotlight · blinding ray (3 charges/dawn)", "page": 222},
    {"name": "Goggles of Night",        "rarity": "uncommon", "type": "Eyewear",  "attune": False, "summary": "Darkvision 60 ft", "page": 222},
    {"name": "Hat of Disguise",         "rarity": "uncommon", "type": "Headwear", "attune": True,  "summary": "Cast Disguise Self at will", "page": 222},
    {"name": "Headband of Intellect",   "rarity": "uncommon", "type": "Headwear", "attune": True,  "summary": "INT set to 19 if lower", "page": 222},
    {"name": "Immovable Rod",           "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "Holds 8000 lb at fixed position · DC 30 STR to move", "page": 223},
    {"name": "Mariner's Armor",         "rarity": "uncommon", "type": "Armor",    "attune": False, "summary": "Swim speed = walking · float on water unconscious", "page": 226},
    {"name": "Periapt of Health",       "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "Immunity to disease while worn", "page": 230},
    {"name": "Periapt of Wound Closure","rarity": "uncommon", "type": "Wondrous", "attune": True,  "summary": "Stable on 0 HP automatically · HD healing roll twice take higher", "page": 230},
    {"name": "Pipes of the Sewers",     "rarity": "uncommon", "type": "Instrument","attune": True, "summary": "Charm rats · summon swarm of rats", "page": 230},
    {"name": "Quiver of Ehlonna",       "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "Three pockets: 60 arrows · 18 javelins · 6 staves/bows", "page": 231},
    {"name": "Ring of Free Action",     "rarity": "rare",     "type": "Ring",     "attune": True,  "summary": "Difficult terrain doesn't slow · immune to paralysis/restraint by spells", "page": 232},
    {"name": "Ring of Jumping",         "rarity": "uncommon", "type": "Ring",     "attune": True,  "summary": "Cast Jump on self at will", "page": 232},
    {"name": "Ring of Mind Shielding",  "rarity": "uncommon", "type": "Ring",     "attune": True,  "summary": "Cannot be charmed/frightened by detection · house ghost on death", "page": 232},
    {"name": "Ring of Protection",      "rarity": "rare",     "type": "Ring",     "attune": True,  "summary": "+1 AC and saves", "page": 233},
    {"name": "Ring of Spell Storing",   "rarity": "rare",     "type": "Ring",     "attune": True,  "summary": "Stores up to 5 levels of spells · cast at storer's stats", "page": 233},
    {"name": "Ring of Swimming",        "rarity": "uncommon", "type": "Ring",     "attune": False, "summary": "Swim speed 40 ft", "page": 233},
    {"name": "Robe of Eyes",            "rarity": "rare",     "type": "Robe",     "attune": True,  "summary": "All-around vision · darkvision 120 ft · adv on Perception · sunlight blinds 1 min", "page": 234},
    {"name": "Robe of Stars",           "rarity": "very rare","type": "Robe",     "attune": True,  "summary": "+1 saves · 6 stars/dawn ranged 1d8 force · astral plane travel", "page": 234},
    {"name": "Rope of Climbing",        "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "60 ft · cmd-word: animate · 3000 lb hold", "page": 234},
    {"name": "Stone of Good Luck",      "rarity": "uncommon", "type": "Wondrous", "attune": True,  "summary": "+1 to ability checks and saving throws", "page": 235},
    {"name": "Wand of Magic Missiles",  "rarity": "uncommon", "type": "Wand",     "attune": False, "summary": "7 charges · cast Magic Missile (1-3 levels)", "page": 235},
    {"name": "Wand of Web",             "rarity": "uncommon", "type": "Wand",     "attune": True,  "summary": "7 charges · cast Web", "page": 235},
    {"name": "Weapon, +1",              "rarity": "uncommon", "type": "Weapon",   "attune": False, "summary": "+1 atk and dmg rolls", "page": 235},
    {"name": "Weapon, +2",              "rarity": "rare",     "type": "Weapon",   "attune": False, "summary": "+2 atk and dmg rolls", "page": 235},
    {"name": "Weapon, +3",              "rarity": "very rare","type": "Weapon",   "attune": False, "summary": "+3 atk and dmg rolls", "page": 235},
    {"name": "Armor, +1",               "rarity": "rare",     "type": "Armor",    "attune": False, "summary": "+1 AC", "page": 213},
    {"name": "Armor, +2",               "rarity": "very rare","type": "Armor",    "attune": False, "summary": "+2 AC", "page": 213},
    {"name": "Shield, +1",              "rarity": "uncommon", "type": "Shield",   "attune": False, "summary": "+1 AC beyond shield's normal bonus", "page": 235},
    {"name": "Potion of Healing",       "rarity": "common",   "type": "Potion",   "attune": False, "summary": "Action: regain 2d4+2 HP", "page": 230},
    {"name": "Potion of Greater Healing","rarity":"uncommon", "type": "Potion",   "attune": False, "summary": "Action: regain 4d4+4 HP", "page": 230},
    {"name": "Potion of Superior Healing","rarity":"rare",    "type": "Potion",   "attune": False, "summary": "Action: regain 8d4+8 HP", "page": 230},
    {"name": "Potion of Supreme Healing","rarity": "very rare","type": "Potion",  "attune": False, "summary": "Action: regain 10d4+20 HP", "page": 230},
    {"name": "Potion of Speed",         "rarity": "very rare","type": "Potion",   "attune": False, "summary": "1 min Haste · 4 levels of exhaustion when ends", "page": 230},
    {"name": "Potion of Invisibility",  "rarity": "very rare","type": "Potion",   "attune": False, "summary": "1 hr invisibility · ends if attack/cast", "page": 230},
    {"name": "Bag of Tricks",           "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "3 furry balls/day · become small beast (CR 1/8 to 1)", "page": 213},
    {"name": "Brooch of Shielding",     "rarity": "uncommon", "type": "Brooch",   "attune": True,  "summary": "Resistance to force · immune Magic Missile", "page": 216},
    {"name": "Cloak of Displacement",   "rarity": "rare",     "type": "Cloak",    "attune": True,  "summary": "Attacks vs. you disadv · ends until next turn after taking damage", "page": 217},
    {"name": "Cube of Force",           "rarity": "rare",     "type": "Wondrous", "attune": True,  "summary": "10 charges · 5-ft cube barrier · 6 face options", "page": 218},
    {"name": "Dust of Disappearance",   "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "Sprinkle: invisible 2d4 min within 10 ft", "page": 219},
    {"name": "Elven Chain",             "rarity": "rare",     "type": "Armor",    "attune": False, "summary": "+1 AC chain shirt · proficient automatically", "page": 220},
    {"name": "Folding Boat",            "rarity": "rare",     "type": "Wondrous", "attune": False, "summary": "Cmd-word: rowboat (10ft) → ship (24ft) → fold back", "page": 221},
    {"name": "Glamoured Studded Leather","rarity": "rare",    "type": "Armor",    "attune": False, "summary": "+1 AC studded leather · cmd-word changes appearance", "page": 222},
    {"name": "Hat of Wizardry",         "rarity": "uncommon", "type": "Headwear", "attune": True,  "summary": "Cast cantrip you know · stash spell up to 1st level", "page": 222},
    {"name": "Helm of Comprehending Languages","rarity":"uncommon","type": "Headwear","attune":False,"summary":"Cast Comprehend Languages","page":222},
    {"name": "Helm of Telepathy",       "rarity": "uncommon", "type": "Headwear", "attune": True,  "summary": "Cast Detect Thoughts (DC 13) · Suggestion 1/dawn", "page": 222},
    {"name": "Lantern of Revealing",    "rarity": "uncommon", "type": "Wondrous", "attune": False, "summary": "Bright 30 ft + dim 30 ft · invisible creatures visible in light", "page": 226},
    {"name": "Manual of Bodily Health", "rarity": "very rare","type": "Wondrous", "attune": False, "summary": "Read: +2 CON & max +2 over 48 hr · single use", "page": 226},
    {"name": "Necklace of Adaptation",  "rarity": "uncommon", "type": "Necklace", "attune": True,  "summary": "Breathe normally in any environment · vacuum / underwater", "page": 228},
    {"name": "Pearl of Power",          "rarity": "uncommon", "type": "Wondrous", "attune": True,  "summary": "Recover one expended spell slot up to 3rd level (1/dawn)", "page": 230},
    {"name": "Wand of Magic Detection", "rarity": "uncommon", "type": "Wand",     "attune": False, "summary": "3 charges · cast Detect Magic", "page": 235},
    {"name": "Winged Boots",            "rarity": "uncommon", "type": "Boots",    "attune": True,  "summary": "Fly speed = walking speed · 4 hr/day", "page": 235},
]


# ── Monsters (SRD p.310 — 60 iconic, CR + key stats only) ──────────
MONSTERS = [
    {"name": "Aboleth",         "cr": 10,  "type": "Aberration", "size": "Large",   "ac": 17, "hp": 135, "speed": "10 ft, swim 40 ft", "atks": "Tentacle 3× 1d6+5 + 4d6 disease", "page": 261},
    {"name": "Animated Armor",  "cr": 1,   "type": "Construct",  "size": "Medium",  "ac": 18, "hp": 33,  "speed": "25 ft", "atks": "Slam 2× 1d6+2", "page": 263},
    {"name": "Ankheg",          "cr": 2,   "type": "Monstrosity","size": "Large",   "ac": 14, "hp": 39,  "speed": "30 ft, burrow 10 ft", "atks": "Bite 2d6+3 + 1d6 acid · acid spray 3d6", "page": 263},
    {"name": "Banshee",         "cr": 4,   "type": "Undead",     "size": "Medium",  "ac": 12, "hp": 58,  "speed": "fly 40 ft hover", "atks": "Corrupting Touch 3d6 necrotic · Wail (3d6 psychic)", "page": 264},
    {"name": "Basilisk",        "cr": 3,   "type": "Monstrosity","size": "Medium",  "ac": 15, "hp": 52,  "speed": "20 ft", "atks": "Bite 2d6+3 + 2d6 poison · Petrifying Gaze", "page": 265},
    {"name": "Black Dragon (Adult)","cr": 14, "type": "Dragon",  "size": "Huge",    "ac": 19, "hp": 195, "speed": "40 ft, fly 80 ft, swim 40 ft", "atks": "Multiattack 1 bite 2 claws · Acid Breath 14d8", "page": 266},
    {"name": "Beholder",        "cr": 13,  "type": "Aberration", "size": "Large",   "ac": 18, "hp": 180, "speed": "fly 20 ft hover", "atks": "Bite 4d6 · 10 Eye Rays (charm/sleep/fear/disintegrate/death)", "page": 268},
    {"name": "Bugbear",         "cr": 1,   "type": "Humanoid",   "size": "Medium",  "ac": 16, "hp": 27,  "speed": "30 ft", "atks": "Morningstar 2d8+2 · Surprise Attack +2d6", "page": 271},
    {"name": "Bullete",         "cr": 5,   "type": "Monstrosity","size": "Large",   "ac": 17, "hp": 94,  "speed": "40 ft, burrow 40 ft", "atks": "Bite 4d12+4 · Deadly Leap", "page": 272},
    {"name": "Centaur",         "cr": 2,   "type": "Monstrosity","size": "Large",   "ac": 12, "hp": 45,  "speed": "50 ft", "atks": "Pike 1d10+4 · Hooves 2d6+4 · Longbow 1d8+2", "page": 272},
    {"name": "Chimera",         "cr": 6,   "type": "Monstrosity","size": "Large",   "ac": 14, "hp": 114, "speed": "30 ft, fly 60 ft", "atks": "Bite/Horn/Claw multi · Fire Breath 7d8", "page": 274},
    {"name": "Cloaker",         "cr": 8,   "type": "Aberration", "size": "Large",   "ac": 14, "hp": 78,  "speed": "10 ft, fly 40 ft", "atks": "Bite + Tail · Moan (frightened DC 13) · Phantasms", "page": 274},
    {"name": "Couatl",          "cr": 4,   "type": "Celestial",  "size": "Medium",  "ac": 19, "hp": 97,  "speed": "30 ft, fly 90 ft", "atks": "Bite 1d6+5 + 4d12 poison · Constrict · innate spells", "page": 275},
    {"name": "Cyclops",         "cr": 6,   "type": "Giant",      "size": "Huge",    "ac": 14, "hp": 138, "speed": "30 ft", "atks": "Greatclub 3d8+6 · Rock 4d10+6", "page": 275},
    {"name": "Death Knight",    "cr": 17,  "type": "Undead",     "size": "Medium",  "ac": 20, "hp": 180, "speed": "30 ft", "atks": "Longsword 3× 1d8+6 · Hellfire Orb 8d8+8d6 fire", "page": 276},
    {"name": "Demilich",        "cr": 18,  "type": "Undead",     "size": "Tiny",    "ac": 20, "hp": 80,  "speed": "fly 30 ft hover", "atks": "Howl 4d6 psychic · Life Drain DC 19 trap soul", "page": 276},
    {"name": "Displacer Beast", "cr": 3,   "type": "Monstrosity","size": "Large",   "ac": 13, "hp": 85,  "speed": "40 ft", "atks": "Tentacle 1d6+3 + 1d6 piercing · Displacement", "page": 278},
    {"name": "Doppelganger",    "cr": 3,   "type": "Monstrosity","size": "Medium",  "ac": 14, "hp": 52,  "speed": "30 ft", "atks": "Slam 1d6+4 · Read Thoughts · Shapechanger", "page": 278},
    {"name": "Drow",            "cr": 0.25,"type": "Humanoid",   "size": "Medium",  "ac": 15, "hp": 13,  "speed": "30 ft", "atks": "Shortsword 1d6+2 · Hand Crossbow 1d6+2 + sleep", "page": 280},
    {"name": "Dryad",           "cr": 1,   "type": "Fey",        "size": "Medium",  "ac": 11, "hp": 22,  "speed": "30 ft", "atks": "Club 1d4 · Fey Charm DC 14 · Tree Stride", "page": 280},
    {"name": "Earth Elemental", "cr": 5,   "type": "Elemental",  "size": "Large",   "ac": 17, "hp": 126, "speed": "30 ft, burrow 30 ft", "atks": "Slam 2× 2d8+5", "page": 282},
    {"name": "Ettin",           "cr": 4,   "type": "Giant",      "size": "Large",   "ac": 12, "hp": 85,  "speed": "40 ft", "atks": "Battleaxe 2d8+5 · Morningstar 2d8+5", "page": 283},
    {"name": "Fire Elemental",  "cr": 5,   "type": "Elemental",  "size": "Large",   "ac": 13, "hp": 102, "speed": "50 ft", "atks": "Touch 2× 2d6+3 fire + ignite", "page": 283},
    {"name": "Fire Giant",      "cr": 9,   "type": "Giant",      "size": "Huge",    "ac": 18, "hp": 162, "speed": "30 ft", "atks": "Greatsword 2× 6d6+7 · Rock 4d10+7", "page": 284},
    {"name": "Flesh Golem",     "cr": 5,   "type": "Construct",  "size": "Medium",  "ac": 9,  "hp": 93,  "speed": "30 ft", "atks": "Slam 2× 2d8+4 · Berserk · Lightning Absorption", "page": 286},
    {"name": "Frost Giant",     "cr": 8,   "type": "Giant",      "size": "Huge",    "ac": 15, "hp": 138, "speed": "40 ft", "atks": "Greataxe 2× 3d12+6 · Rock 4d10+6", "page": 287},
    {"name": "Gargoyle",        "cr": 2,   "type": "Elemental",  "size": "Medium",  "ac": 15, "hp": 52,  "speed": "30 ft, fly 60 ft", "atks": "Bite + 2 Claws", "page": 288},
    {"name": "Gelatinous Cube", "cr": 2,   "type": "Ooze",       "size": "Large",   "ac": 6,  "hp": 84,  "speed": "15 ft", "atks": "Pseudopod 3d6 acid · Engulf · Transparent", "page": 290},
    {"name": "Ghost",           "cr": 4,   "type": "Undead",     "size": "Medium",  "ac": 11, "hp": 45,  "speed": "0 ft, fly 40 ft hover", "atks": "Withering Touch 4d6 necrotic · Possession · Horrifying Visage", "page": 290},
    {"name": "Ghoul",           "cr": 1,   "type": "Undead",     "size": "Medium",  "ac": 12, "hp": 22,  "speed": "30 ft", "atks": "Bite 2d6+2 · Claws DC 10 paralysis", "page": 291},
    {"name": "Giant Spider",    "cr": 1,   "type": "Beast",      "size": "Large",   "ac": 14, "hp": 26,  "speed": "30 ft, climb 30 ft", "atks": "Bite 1d8+3 + 2d8 poison · Web", "page": 297},
    {"name": "Gnoll",           "cr": 0.5, "type": "Humanoid",   "size": "Medium",  "ac": 15, "hp": 22,  "speed": "30 ft", "atks": "Spear 1d6+2 · Longbow 1d8+2 · Rampage bonus bite", "page": 298},
    {"name": "Goblin",          "cr": 0.25,"type": "Humanoid",   "size": "Small",   "ac": 15, "hp": 7,   "speed": "30 ft", "atks": "Scimitar 1d6+2 · Shortbow 1d6+2 · Nimble Escape", "page": 298},
    {"name": "Gorgon",          "cr": 5,   "type": "Monstrosity","size": "Large",   "ac": 19, "hp": 114, "speed": "40 ft", "atks": "Gore 2d12+4 · Hooves 2d10+4 · Petrifying Breath", "page": 299},
    {"name": "Hag, Green",      "cr": 3,   "type": "Fey",        "size": "Medium",  "ac": 17, "hp": 82,  "speed": "30 ft", "atks": "Claws 2d8+4 · Mimicry · Illusory Appearance", "page": 302},
    {"name": "Half-Dragon",     "cr": 0,   "type": "varies",     "size": "varies",  "ac": 0,  "hp": 0,   "speed": "varies", "atks": "Add: Breath Weapon · Damage Resistance · Darkvision · 5×CR HP", "page": 304},
    {"name": "Hippogriff",      "cr": 1,   "type": "Monstrosity","size": "Large",   "ac": 11, "hp": 19,  "speed": "40 ft, fly 60 ft", "atks": "Beak 1d10+3 · Claws 2d6+3", "page": 304},
    {"name": "Hobgoblin",       "cr": 0.5, "type": "Humanoid",   "size": "Medium",  "ac": 18, "hp": 11,  "speed": "30 ft", "atks": "Longsword 1d8+1 · Longbow 1d8+1 · Martial Advantage +2d6", "page": 305},
    {"name": "Hydra",           "cr": 8,   "type": "Monstrosity","size": "Huge",    "ac": 15, "hp": 172, "speed": "30 ft, swim 30 ft", "atks": "Multiattack 5× Bite 1d10+5 · Multi-headed", "page": 305},
    {"name": "Imp",             "cr": 1,   "type": "Fiend",      "size": "Tiny",    "ac": 13, "hp": 10,  "speed": "20 ft, fly 40 ft", "atks": "Sting 1d4+3 + 3d6 poison · Invisibility · Shapechanger", "page": 307},
    {"name": "Kobold",          "cr": 0.125,"type": "Humanoid",  "size": "Small",   "ac": 12, "hp": 5,   "speed": "30 ft", "atks": "Dagger 1d4+2 · Sling 1d4+2 · Pack Tactics", "page": 311},
    {"name": "Kraken",          "cr": 23,  "type": "Monstrosity","size": "Gargantuan","ac":18,"hp": 472,"speed": "20 ft, swim 60 ft", "atks": "10 Tentacles · Bite 23 piercing · Lightning 4d10 · Fling", "page": 311},
    {"name": "Lich",            "cr": 21,  "type": "Undead",     "size": "Medium",  "ac": 17, "hp": 135, "speed": "30 ft", "atks": "Paralyzing Touch 3d6 cold + DC 18 paralysis · 9th-level caster", "page": 312},
    {"name": "Mind Flayer",     "cr": 7,   "type": "Aberration", "size": "Medium",  "ac": 15, "hp": 71,  "speed": "30 ft", "atks": "Tentacles + Extract Brain · Mind Blast 4d8+4 psychic 60ft cone", "page": 314},
    {"name": "Minotaur",        "cr": 3,   "type": "Monstrosity","size": "Large",   "ac": 14, "hp": 76,  "speed": "40 ft", "atks": "Greataxe 2d12+4 · Gore 2d8+4 · Charge", "page": 315},
    {"name": "Mummy",           "cr": 3,   "type": "Undead",     "size": "Medium",  "ac": 11, "hp": 58,  "speed": "20 ft", "atks": "Rotting Fist 2d6+3 + Mummy Rot · Dreadful Glare", "page": 316},
    {"name": "Nothic",          "cr": 2,   "type": "Aberration", "size": "Medium",  "ac": 15, "hp": 45,  "speed": "30 ft", "atks": "Claws 2× 1d6+3 · Rotting Gaze 3d6 necrotic · Weird Insight", "page": 317},
    {"name": "Ogre",            "cr": 2,   "type": "Giant",      "size": "Large",   "ac": 11, "hp": 59,  "speed": "40 ft", "atks": "Greatclub 2d8+4 · Javelin 2d6+4", "page": 317},
    {"name": "Orc",             "cr": 0.5, "type": "Humanoid",   "size": "Medium",  "ac": 13, "hp": 15,  "speed": "30 ft", "atks": "Greataxe 1d12+3 · Javelin 1d6+3 · Aggressive bonus move", "page": 318},
    {"name": "Owlbear",         "cr": 3,   "type": "Monstrosity","size": "Large",   "ac": 13, "hp": 59,  "speed": "40 ft", "atks": "Beak 1d10+5 · Claws 2d8+5", "page": 318},
    {"name": "Pegasus",         "cr": 2,   "type": "Celestial",  "size": "Large",   "ac": 12, "hp": 59,  "speed": "60 ft, fly 90 ft", "atks": "Hooves 2d6+4", "page": 320},
    {"name": "Roper",           "cr": 5,   "type": "Monstrosity","size": "Large",   "ac": 20, "hp": 93,  "speed": "10 ft, climb 10 ft", "atks": "Bite 4d8+4 · 6 Tendrils · Reel · False Appearance", "page": 326},
    {"name": "Sahuagin",        "cr": 0.5, "type": "Humanoid",   "size": "Medium",  "ac": 12, "hp": 22,  "speed": "30 ft, swim 40 ft", "atks": "Bite 1d4+1 · Spear 1d6+1 · Blood Frenzy", "page": 327},
    {"name": "Skeleton",        "cr": 0.25,"type": "Undead",     "size": "Medium",  "ac": 13, "hp": 13,  "speed": "30 ft", "atks": "Shortsword 1d6+2 · Shortbow 1d6+2", "page": 328},
    {"name": "Specter",         "cr": 1,   "type": "Undead",     "size": "Medium",  "ac": 12, "hp": 22,  "speed": "0 ft, fly 50 ft hover", "atks": "Life Drain 3d6 necrotic + max HP reduction", "page": 328},
    {"name": "Stirge",          "cr": 0.125,"type": "Beast",     "size": "Tiny",    "ac": 14, "hp": 2,   "speed": "10 ft, fly 40 ft", "atks": "Blood Drain 1d4+3 piercing · attach", "page": 330},
    {"name": "Troll",           "cr": 5,   "type": "Giant",      "size": "Large",   "ac": 15, "hp": 84,  "speed": "30 ft", "atks": "Bite + 2 Claws · Regeneration 10 (acid/fire stops)", "page": 333},
    {"name": "Vampire",         "cr": 13,  "type": "Undead",     "size": "Medium",  "ac": 16, "hp": 144, "speed": "30 ft", "atks": "Unarmed 1d8+4 · Bite 1d6+4 + 3d6 necrotic + drain · Charm · Children of the Night", "page": 334},
    {"name": "Wight",           "cr": 3,   "type": "Undead",     "size": "Medium",  "ac": 14, "hp": 45,  "speed": "30 ft", "atks": "Life Drain 1d6+3 + max HP reduction · Longsword · Longbow", "page": 336},
    {"name": "Worg",            "cr": 0.5, "type": "Monstrosity","size": "Large",   "ac": 13, "hp": 26,  "speed": "50 ft", "atks": "Bite 2d6+3 + DC 11 prone", "page": 337},
    {"name": "Wyvern",          "cr": 6,   "type": "Dragon",     "size": "Large",   "ac": 13, "hp": 110, "speed": "20 ft, fly 80 ft", "atks": "Bite 2d6+4 · Claws 2d8+4 · Stinger 2d6+4 + 7d6 poison", "page": 337},
    {"name": "Zombie",          "cr": 0.25,"type": "Undead",     "size": "Medium",  "ac": 8,  "hp": 22,  "speed": "20 ft", "atks": "Slam 1d6+1 · Undead Fortitude DC 5+dmg", "page": 339},
]


# ── Additional Races (SRD 5.2 + Volo's-style mechanic-only) ────────
RACES_EXT = [
    {"name": "Aasimar",   "asi": "+2 Cha / +1 Wis",  "size": "Medium", "speed": 30,
     "traits": ["Darkvision 60ft", "Celestial Resistance (necrotic/radiant)", "Healing Hands", "Light cantrip", "Transformation 3rd lv"], "page": 73},
    {"name": "Firbolg",   "asi": "+2 Wis / +1 Str",  "size": "Medium", "speed": 30,
     "traits": ["Firbolg Magic", "Hidden Step", "Powerful Build", "Speech of Beast and Leaf"], "page": 73},
    {"name": "Goliath",   "asi": "+2 Str / +1 Con",  "size": "Medium", "speed": 30,
     "traits": ["Stone's Endurance", "Powerful Build", "Mountain Born (cold-adapted)"], "page": 73},
    {"name": "Kenku",     "asi": "+2 Dex / +1 Wis",  "size": "Medium", "speed": 30,
     "traits": ["Expert Forgery", "Kenku Training (2 skills)", "Mimicry"], "page": 74},
    {"name": "Lizardfolk","asi": "+2 Con / +1 Wis",  "size": "Medium", "speed": 30,
     "traits": ["Bite 1d6+STR", "Cunning Artisan", "Hold Breath 15 min", "Hunter's Lore", "Natural Armor 13+DEX", "Hungry Jaws"], "page": 74},
    {"name": "Tabaxi",    "asi": "+2 Dex / +1 Cha",  "size": "Medium", "speed": 30,
     "traits": ["Darkvision 60ft", "Feline Agility (double speed)", "Cat's Claws climb 20", "Cat's Talent Stealth/Perception"], "page": 74},
    {"name": "Triton",    "asi": "+1 Str / +1 Con / +1 Cha", "size": "Medium", "speed": 30,
     "traits": ["Amphibious", "Control Air & Water (FogCloud→GustOfWind→WallOfWater)", "Darkvision 60ft", "Cold/Underwater adapted"], "page": 75},
    {"name": "Yuan-ti Pureblood","asi": "+2 Cha / +1 Int", "size": "Medium", "speed": 30,
     "traits": ["Darkvision 60ft", "Innate Spellcasting (Poison Spray, Animal Friendship, Suggestion)", "Magic Resistance", "Poison Immunity"], "page": 75},
    {"name": "Genasi (Air)","asi": "+2 Con / +1 Dex",  "size": "Medium", "speed": 30,
     "traits": ["Unending Breath", "Mingle with the Wind (Levitate 1/long rest)"], "page": 76},
    {"name": "Genasi (Earth)","asi": "+2 Con / +1 Str","size": "Medium", "speed": 30,
     "traits": ["Earth Walk (no difficult terrain on stone/earth)", "Merge with Stone (Pass Without Trace 1/long rest)"], "page": 76},
    {"name": "Genasi (Fire)","asi": "+2 Con / +1 Int","size": "Medium", "speed": 30,
     "traits": ["Darkvision 60ft", "Fire Resistance", "Reach to the Blaze (Produce Flame · Burning Hands 1/long rest)"], "page": 76},
    {"name": "Genasi (Water)","asi": "+2 Con / +1 Wis","size": "Medium", "speed": 30,
     "traits": ["Acid Resistance", "Amphibious", "Swim 30 ft", "Call to the Wave (Shape Water · Create or Destroy Water 1/long rest)"], "page": 76},
]

# ── Class progression — feature timeline (mechanic only) ───────────
# Each class gets a per-level summary of its hallmark SRD features.
CLASS_FEATURES = {
    "Barbarian": [
        {"level": 1,  "features": ["Rage 2/long rest +2 dmg", "Unarmored Defense 10+DEX+CON"]},
        {"level": 2,  "features": ["Reckless Attack", "Danger Sense (adv on DEX vs. seen)"]},
        {"level": 3,  "features": ["Primal Path subclass", "Rage 3/long rest"]},
        {"level": 4,  "features": ["ASI / Feat"]},
        {"level": 5,  "features": ["Extra Attack", "Fast Movement +10 ft"]},
        {"level": 7,  "features": ["Feral Instinct (adv init)", "Surprise rage"]},
        {"level": 9,  "features": ["Brutal Critical (1 die)"]},
        {"level": 11, "features": ["Relentless Rage (DC 10 CON to drop to 1 HP)"]},
        {"level": 15, "features": ["Persistent Rage (no time-out)"]},
        {"level": 18, "features": ["Indomitable Might (STR ≥ ability score)"]},
        {"level": 20, "features": ["Primal Champion (+4 STR/CON, max 24)"]},
    ],
    "Bard": [
        {"level": 1, "features": ["Spellcasting (full)", "Bardic Inspiration d6 (CHA mod uses)", "Cantrips 2"]},
        {"level": 2, "features": ["Jack of All Trades (+½ PB)", "Song of Rest d6"]},
        {"level": 3, "features": ["Bard College subclass", "Expertise (2 skills)"]},
        {"level": 5, "features": ["Bardic Inspiration d8", "Font of Inspiration (recover on short rest)"]},
        {"level": 6, "features": ["Countercharm"]},
        {"level": 10,"features": ["Magical Secrets (2 spells any list)", "Bardic Inspiration d10"]},
        {"level": 14,"features": ["Magical Secrets (+2)", "subclass feature"]},
        {"level": 15,"features": ["Bardic Inspiration d12"]},
        {"level": 18,"features": ["Magical Secrets (+2)"]},
        {"level": 20,"features": ["Superior Inspiration (regain on init)"]},
    ],
    "Cleric": [
        {"level": 1, "features": ["Spellcasting (full WIS)", "Divine Domain subclass", "3 cantrips"]},
        {"level": 2, "features": ["Channel Divinity 1/rest", "Turn Undead"]},
        {"level": 5, "features": ["Destroy Undead CR 1/2"]},
        {"level": 8, "features": ["Destroy Undead CR 1", "Divine Strike or Potent Spellcasting (subclass)"]},
        {"level": 10,"features": ["Divine Intervention (CL %)"]},
        {"level": 17,"features": ["Destroy Undead CR 4"]},
        {"level": 20,"features": ["Divine Intervention auto-success 1/wk"]},
    ],
    "Druid": [
        {"level": 1, "features": ["Spellcasting (full WIS)", "Druidic language", "2 cantrips"]},
        {"level": 2, "features": ["Wild Shape (CR ≤ 1/4 no fly/swim)", "Druid Circle subclass"]},
        {"level": 4, "features": ["Wild Shape (CR ≤ 1/2, no fly)"]},
        {"level": 8, "features": ["Wild Shape (CR ≤ 1)"]},
        {"level": 18,"features": ["Beast Spells (cast in Wild Shape)"]},
        {"level": 20,"features": ["Archdruid (unlimited Wild Shape, no components for druid spells)"]},
    ],
    "Fighter": [
        {"level": 1, "features": ["Fighting Style", "Second Wind (1d10+CL)"]},
        {"level": 2, "features": ["Action Surge 1/rest"]},
        {"level": 3, "features": ["Martial Archetype subclass"]},
        {"level": 5, "features": ["Extra Attack"]},
        {"level": 9, "features": ["Indomitable 1/long rest (re-roll save)"]},
        {"level": 11,"features": ["Extra Attack (2)"]},
        {"level": 17,"features": ["Action Surge (2/rest)", "Indomitable 3/long rest"]},
        {"level": 20,"features": ["Extra Attack (3)"]},
    ],
    "Monk": [
        {"level": 1, "features": ["Unarmored Defense 10+DEX+WIS", "Martial Arts d4"]},
        {"level": 2, "features": ["Ki (CL pts)", "Unarmored Movement +10 ft"]},
        {"level": 3, "features": ["Monastic Tradition subclass", "Deflect Missiles"]},
        {"level": 4, "features": ["Slow Fall"]},
        {"level": 5, "features": ["Extra Attack", "Stunning Strike (1 ki)", "Martial Arts d6"]},
        {"level": 6, "features": ["Ki-Empowered Strikes (count as magical)"]},
        {"level": 7, "features": ["Evasion", "Stillness of Mind"]},
        {"level": 11,"features": ["Martial Arts d8"]},
        {"level": 14,"features": ["Diamond Soul (proficiency in all saves)"]},
        {"level": 17,"features": ["Martial Arts d10"]},
        {"level": 18,"features": ["Empty Body (1 hr invis · 4 ki)"]},
        {"level": 20,"features": ["Perfect Self (regain 4 ki at init)"]},
    ],
    "Paladin": [
        {"level": 1, "features": ["Divine Sense 1+CHA/long rest", "Lay on Hands (5×CL HP pool)"]},
        {"level": 2, "features": ["Spellcasting (half)", "Divine Smite (slot → +2d8 radiant)", "Fighting Style"]},
        {"level": 3, "features": ["Sacred Oath subclass", "Divine Health (immune disease)"]},
        {"level": 5, "features": ["Extra Attack"]},
        {"level": 6, "features": ["Aura of Protection (+CHA to saves 10ft)"]},
        {"level": 10,"features": ["Aura of Courage (immune frightened 10ft)"]},
        {"level": 11,"features": ["Improved Divine Smite (+1d8 radiant on hit)"]},
        {"level": 14,"features": ["Cleansing Touch (end spell with action, CHA/long rest)"]},
        {"level": 18,"features": ["Aura range expands to 30 ft"]},
    ],
    "Ranger": [
        {"level": 1, "features": ["Favored Enemy", "Natural Explorer"]},
        {"level": 2, "features": ["Spellcasting (half)", "Fighting Style"]},
        {"level": 3, "features": ["Ranger Archetype subclass", "Primeval Awareness"]},
        {"level": 5, "features": ["Extra Attack"]},
        {"level": 8, "features": ["Land's Stride (no difficult terrain non-magical)"]},
        {"level": 10,"features": ["Hide in Plain Sight (1 min camo)"]},
        {"level": 14,"features": ["Vanish (Hide as bonus action)"]},
        {"level": 18,"features": ["Feral Senses (detect invisible 30ft)"]},
        {"level": 20,"features": ["Foe Slayer (+WIS to hit/dmg vs. favored)"]},
    ],
    "Rogue": [
        {"level": 1, "features": ["Expertise (2 skills/thieves' tools)", "Sneak Attack 1d6", "Thieves' Cant"]},
        {"level": 2, "features": ["Cunning Action (Dash/Disengage/Hide as BA)"]},
        {"level": 3, "features": ["Roguish Archetype subclass", "Sneak Attack 2d6"]},
        {"level": 5, "features": ["Uncanny Dodge (½ dmg on seen attack)", "Sneak 3d6"]},
        {"level": 7, "features": ["Evasion", "Sneak 4d6"]},
        {"level": 11,"features": ["Reliable Talent (treat d20 ≤ 9 as 10)"]},
        {"level": 14,"features": ["Blindsense 10 ft"]},
        {"level": 15,"features": ["Slippery Mind (WIS save proficiency)"]},
        {"level": 18,"features": ["Elusive (no advantage vs. you while not incap)"]},
        {"level": 20,"features": ["Stroke of Luck (turn miss → hit · failed check → 20)"]},
    ],
    "Sorcerer": [
        {"level": 1, "features": ["Spellcasting (full CHA)", "Sorcerous Origin subclass", "4 cantrips"]},
        {"level": 2, "features": ["Font of Magic (2 sorcery points)", "Flexible Casting"]},
        {"level": 3, "features": ["Metamagic (2 options)"]},
        {"level": 10,"features": ["Metamagic (+1)"]},
        {"level": 17,"features": ["Metamagic (+1, total 4)"]},
        {"level": 20,"features": ["Sorcerous Restoration (regain 4 SP on short rest)"]},
    ],
    "Warlock": [
        {"level": 1, "features": ["Otherworldly Patron subclass", "Pact Magic (slots recharge on short rest)", "2 cantrips"]},
        {"level": 2, "features": ["Eldritch Invocations (2)"]},
        {"level": 3, "features": ["Pact Boon (Blade/Chain/Tome)"]},
        {"level": 11,"features": ["Mystic Arcanum (6th)"]},
        {"level": 13,"features": ["Mystic Arcanum (7th)"]},
        {"level": 15,"features": ["Mystic Arcanum (8th)"]},
        {"level": 17,"features": ["Mystic Arcanum (9th)"]},
        {"level": 20,"features": ["Eldritch Master (regain pact slots in 1 min · 1/long rest)"]},
    ],
    "Wizard": [
        {"level": 1, "features": ["Spellcasting (full INT)", "Arcane Recovery (slots = ½ CL)", "Spellbook (6 spells)", "3 cantrips"]},
        {"level": 2, "features": ["Arcane Tradition subclass"]},
        {"level": 18,"features": ["Spell Mastery (1st & 2nd-level no slot)"]},
        {"level": 20,"features": ["Signature Spells (two 3rd-level cast 1/short rest)"]},
    ],
}

# ── Subclasses (one canonical SRD subclass per class) ──────────────
SUBCLASSES = [
    {"class": "Barbarian", "name": "Path of the Berserker", "key": ["Frenzy", "Mindless Rage 6", "Intimidating Presence 10", "Retaliation 14"], "page": 7},
    {"class": "Bard",      "name": "College of Lore",       "key": ["Bonus Proficiencies (3 skills)", "Cutting Words 3", "Additional Magical Secrets 6", "Peerless Skill 14"], "page": 13},
    {"class": "Cleric",    "name": "Life Domain",           "key": ["Disciple of Life", "Preserve Life CD 2", "Blessed Healer 6", "Divine Strike 8 (1d8 radiant)", "Supreme Healing 17"], "page": 17},
    {"class": "Druid",     "name": "Circle of the Land",    "key": ["Bonus Cantrip 2", "Natural Recovery 2", "Circle Spells 3/5/7/9", "Land's Stride 6", "Nature's Ward 10", "Nature's Sanctuary 14"], "page": 25},
    {"class": "Fighter",   "name": "Champion",              "key": ["Improved Critical (19+) 3", "Remarkable Athlete 7", "Additional Fighting Style 10", "Superior Critical (18+) 15", "Survivor 18"], "page": 30},
    {"class": "Monk",      "name": "Way of the Open Hand",  "key": ["Open Hand Technique 3", "Wholeness of Body 6", "Tranquility 11", "Quivering Palm 17"], "page": 34},
    {"class": "Paladin",   "name": "Oath of Devotion",      "key": ["Sacred Weapon CD 3", "Aura of Devotion 7", "Purity of Spirit 15", "Holy Nimbus 20"], "page": 39},
    {"class": "Ranger",    "name": "Hunter",                "key": ["Hunter's Prey 3", "Defensive Tactics 7", "Multiattack 11", "Superior Hunter's Defense 15"], "page": 43},
    {"class": "Rogue",     "name": "Thief",                 "key": ["Fast Hands 3", "Second-Story Work 3", "Supreme Sneak 9", "Use Magic Device 13", "Thief's Reflexes 17"], "page": 47},
    {"class": "Sorcerer",  "name": "Draconic Bloodline",    "key": ["Draconic Resilience 1 (+1 HP/lv, AC 13+DEX)", "Elemental Affinity 6", "Dragon Wings 14", "Draconic Presence 18"], "page": 51},
    {"class": "Warlock",   "name": "The Fiend",             "key": ["Dark One's Blessing 1 (CHA+CL temp HP)", "Dark One's Own Luck 6", "Fiendish Resilience 10", "Hurl Through Hell 14"], "page": 55},
    {"class": "Wizard",    "name": "School of Evocation",   "key": ["Evocation Savant 2", "Sculpt Spells 2", "Potent Cantrip 6", "Empowered Evocation 10 (+INT to dmg)", "Overchannel 14"], "page": 60},
]
