"""D&D-spell-mimic BESM Power Bundle templates.

Seeded from `/app/memory/references/Anime_5E_Spell_Conversions.pdf`
(Anime 5E · Spell Conversions · Digital Expansion). Each entry is a
**template**: a ready-to-drop Power Bundle that a GM can add to their
campaign's reference table (via the Atelier's Reference Editor) or that
a player can pull onto a character sheet via the bundle picker.

Template shape
──────────────
  {
    "name": "<spell name>",
    "description": "<short rule blurb — mechanic only, no verbatim prose>",
    "source_spell_name": "<canonical D&D / Anime 5E spell name>",
    "source_spell_level": 0..9,
    "school": "<D&D spell school for UI grouping>",
    "invocation": "per-scene" | "per-charge" | "per-day"
                   | "roll-to-invoke" | "energy-cost",
    "charges_max": <int, 0 = no cap>,
    "energy_cost": <int, EP spent per cast>,
    "cooldown": "<free text — '1 round' | 'short rest' | …>",
    "cost": <net CP cost after enhancements/limiters>,
    "components": [
      {
        "kind": "attribute",
        "name": "<BESM Attribute>",
        "level": <int>,
        "cost_per_level": <float>,
        "enhancements": [{"name": "<name>", "value": <int>}, …],
        "limiters":     [{"name": "<name>", "value": <int>}, …],
        "note": "<conversion note>"
      }, …
    ],
    "references": ["BESM 4E p.X", "Anime 5E Spell Conversions"],
    "tags": ["<school>", "cantrip"|"leveled"],
  }

Starter library — cantrips + selected 1st-9th level spells. A future
patch can extend this from the full PDF; this subset covers every school
and every spell tier so the UI can be exercised end-to-end.
"""
from __future__ import annotations

from typing import Any, Dict, List


POWER_BUNDLE_TEMPLATES: List[Dict[str, Any]] = [
    {
        "name": "Dancing Lights",
        "source_spell_name": "Dancing Lights",
        "source_spell_level": 0,
        "school": "Evocation",
        "description": "Up to four torch-bright motes of light that a caster can steer within range. Concentration.",
        "invocation": "roll-to-invoke",
        "charges_max": 0, "energy_cost": 0,
        "cooldown": "concentration, up to 1 minute",
        "cost": 3,
        "components": [{
            "kind": "attribute", "name": "Control Environment (Light)",
            "level": 3, "cost_per_level": 1,
            "enhancements": [],
            "limiters": [{"name": "Range: 100 ft", "value": -3},
                          {"name": "Concentration", "value": 1}],
            "note": "Range: 100 ft (-3), Concentration (+1)",
        }],
        "references": ["Anime 5E Spell Conversions", "BESM 4E — Control Environment"],
        "tags": ["evocation", "cantrip"],
    },
    {
        "name": "Cure Wounds",
        "source_spell_name": "Cure Wounds",
        "source_spell_level": 1,
        "school": "Evocation",
        "description": "Restore hit points to a touched creature. Does not affect undead or constructs.",
        "invocation": "per-charge",
        "charges_max": 2, "energy_cost": 0,
        "cooldown": "short rest",
        "cost": 1,
        "components": [{
            "kind": "attribute", "name": "Healing (+1d8 HP)",
            "level": 1, "cost_per_level": 1,
            "enhancements": [], "limiters": [],
            "note": "Baseline Healing at +1d8 HP per cast.",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["evocation", "leveled"],
    },
    {
        "name": "Enlarge / Reduce",
        "source_spell_name": "Enlarge/Reduce",
        "source_spell_level": 2,
        "school": "Transmutation",
        "description": "Shift a creature up or down one size category for the duration.",
        "invocation": "roll-to-invoke",
        "charges_max": 0, "energy_cost": 0,
        "cooldown": "concentration, up to 1 minute",
        "cost": 5,
        "components": [{
            "kind": "attribute", "name": "Size Change",
            "level": 1, "cost_per_level": 5,
            "enhancements": [{"name": "Potent", "value": -2}],
            "limiters": [{"name": "Concentration", "value": 1},
                          {"name": "Unique Limiter: Con save resists (DC 8+PB)", "value": 1}],
            "note": "Potent (-2), Concentration (+1), Unique Limiter (+1)",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["transmutation", "leveled"],
    },
    {
        "name": "Dispel Magic",
        "source_spell_name": "Dispel Magic",
        "source_spell_level": 3,
        "school": "Abjuration",
        "description": "End one spell effect on a target. Higher-level effects may require a check.",
        "invocation": "per-day",
        "charges_max": 3, "energy_cost": 0,
        "cooldown": "long rest",
        "cost": 20,
        "components": [{
            "kind": "attribute", "name": "Nullify (Magic)",
            "level": 3, "cost_per_level": 4,
            "enhancements": [],
            "limiters": [{"name": "Range: 100 ft", "value": -3},
                          {"name": "Unique Limiter: one effect at a time", "value": 2}],
            "note": "Nullify Magic · cost 4(3) × 3 = 20 after modifiers",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["abjuration", "leveled"],
    },
    {
        "name": "Greater Invisibility",
        "source_spell_name": "Greater Invisibility",
        "source_spell_level": 4,
        "school": "Illusion",
        "description": "Become invisible to Sight for 1 minute; persists through attacks and casting.",
        "invocation": "per-day",
        "charges_max": 1, "energy_cost": 0,
        "cooldown": "long rest",
        "cost": 3,
        "components": [{
            "kind": "attribute", "name": "Undetectable (Sight 2)",
            "level": 2, "cost_per_level": 1,
            "enhancements": [{"name": "Potent", "value": -1}],
            "limiters": [{"name": "Concentration", "value": 1},
                          {"name": "Environmental: only 1 minute", "value": 1}],
            "note": "Potent (-1), Concentration (+1), Environmental (+1)",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["illusion", "leveled"],
    },
    {
        "name": "Insect Plague",
        "source_spell_name": "Insect Plague",
        "source_spell_level": 5,
        "school": "Conjuration",
        "description": "Summon a 30-ft sphere of biting insects dealing 4d10 piercing; area persists.",
        "invocation": "per-day",
        "charges_max": 1, "energy_cost": 0,
        "cooldown": "long rest",
        "cost": 12,
        "components": [{
            "kind": "attribute", "name": "Weapon: Insect Swarm (4d10 piercing)",
            "level": 10, "cost_per_level": 1,
            "enhancements": [{"name": "Save +4 (Con vs DC 10+PB)", "value": -4}],
            "limiters": [{"name": "Area: 30 ft", "value": -2},
                          {"name": "Duration: 10 minutes", "value": -1},
                          {"name": "Range: 100 ft", "value": -3}],
            "note": "4d10 piercing; Area/Duration/Range limiters net 12 CP",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["conjuration", "leveled"],
    },
    {
        "name": "Move Earth",
        "source_spell_name": "Move Earth",
        "source_spell_level": 6,
        "school": "Transmutation",
        "description": "Slowly sculpt soft earth over a 40-ft cube. 10-minute casting.",
        "invocation": "roll-to-invoke",
        "charges_max": 0, "energy_cost": 0,
        "cooldown": "10 minutes casting + concentration",
        "cost": 24,
        "components": [{
            "kind": "attribute", "name": "Telekinesis (1,000 t / 20,000 ft³)",
            "level": 7, "cost_per_level": 6,
            "enhancements": [],
            "limiters": [{"name": "Range: 100 ft", "value": -3},
                          {"name": "Focussed: Dirt/sand/clay", "value": 1},
                          {"name": "Unique Limiter: slow movement only", "value": 3}],
            "note": "Telekinesis cost 6(7) × 7 after modifiers = 24",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["transmutation", "leveled"],
    },
    {
        "name": "Plane Shift",
        "source_spell_name": "Plane Shift",
        "source_spell_level": 7,
        "school": "Conjuration",
        "description": "Open a portal or transport up to 8 willing creatures to another plane of existence.",
        "invocation": "per-day",
        "charges_max": 1, "energy_cost": 0,
        "cooldown": "long rest",
        "cost": 5,
        "components": [{
            "kind": "attribute", "name": "Portal (One plane of choice)",
            "level": 5, "cost_per_level": 1,
            "enhancements": [{"name": "Portal destination dynamic", "value": -2}],
            "limiters": [{"name": "Equipment: object attuned to destination", "value": 1},
                          {"name": "Unique Limiter: portal closes after use", "value": 1}],
            "note": "Requires attuned focus object.",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["conjuration", "leveled"],
    },
    {
        "name": "Control Weather",
        "source_spell_name": "Control Weather",
        "source_spell_level": 8,
        "school": "Transmutation",
        "description": "Over 10 minutes of casting, alter precipitation / temperature / wind across 10 miles for 8 hours.",
        "invocation": "per-day",
        "charges_max": 1, "energy_cost": 0,
        "cooldown": "24 hours",
        "cost": 7,
        "components": [{
            "kind": "attribute", "name": "Control Environment (Weather)",
            "level": 3, "cost_per_level": 7,
            "enhancements": [{"name": "Activation: 10 minutes", "value": 3}],
            "limiters": [{"name": "Area: 10 miles", "value": -6},
                          {"name": "Duration: 8 hours", "value": -3},
                          {"name": "Concentration", "value": 1},
                          {"name": "Unique Limiter: gradual changes only", "value": 1}],
            "note": "Control Environment 7(3); net cost 7 CP",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["transmutation", "leveled"],
    },
    {
        "name": "Meteor Swarm",
        "source_spell_name": "Meteor Swarm",
        "source_spell_level": 9,
        "school": "Evocation",
        "description": "Rain four meteors across a 1-mile arc — each 20d6 fire + 20d6 bludgeoning in a 30-ft sphere.",
        "invocation": "per-day",
        "charges_max": 1, "energy_cost": 0,
        "cooldown": "long rest + taxing",
        "cost": 66,
        "components": [{
            "kind": "attribute", "name": "Weapon: Meteor Swarm (20d6 fire + 20d6 bludgeoning)",
            "level": 60, "cost_per_level": 1,
            "enhancements": [{"name": "Save +4 (Dex vs DC 10+PB)", "value": -4}],
            "limiters": [{"name": "Area: 30 ft", "value": -2},
                          {"name": "Range: 1 mile", "value": -5},
                          {"name": "Spreading: 4 different locations", "value": -3}],
            "note": "Headline 9th-level conversion — 66 CP.",
        }],
        "references": ["Anime 5E Spell Conversions"],
        "tags": ["evocation", "leveled", "9th-level"],
    },
]
