"""D&D-to-BESM spell/ability conversion reference library.

Read-only lookup table for players running Anime 5E (or BESM 4E)
campaigns who want to port D&D 5E spells & class abilities to the
BESM Attribute framework. Style-guided by the user-supplied `Anime 5E
Spell Conversions (Digital Expansion)` — every entry follows the same
grammar:

  * Source SRD spell / class ability + short description
  * Target BESM Attribute(s) with Cost/Level × Level
  * Enhancement rows (lower effective Level, broaden the power)
  * Limiter rows (raise effective Level, narrow the power)
  * Net CP cost (matches the character validator's math)
  * SRD source citation (page-reference-equivalent)

These entries are NOT Power Bundles — they're a translation atlas,
so players can see how their favourite D&D effect gets expressed on a
BESM sheet. A GM can copy any row into the Reference Editor as a
Power Bundle or Attribute custom-entry if they want it purchasable.

Conversion policy
─────────────────
* All enhancement/limiter `value`s follow BESM Extras ch.3 sign
  convention: POSITIVE = limiter (raises effective level), NEGATIVE =
  enhancement (lowers effective level).
* Net CP costs assume a baseline cost-per-level of 1-6 (lookup from
  BESM 4E p.21+); modifier values shift the paid CP by ±1 per level
  per delta. Check per-line `notes` for any special-case math.
* SRD references use the open CC-BY SRD 5.1 document ("SRD p.X");
  non-SRD sources (like Anime 5E Spell Conversions supplement) are
  cited explicitly.
"""
from __future__ import annotations

from typing import Any, Dict, List


def _entry(name, level, school, desc, besm, net, src):
    return {
        "source_name": name,
        "source_level": level,
        "school": school,
        "short_description": desc,
        "besm": besm,
        "net_cp": net,
        "source_reference": src,
    }


# Helper so every BESM row is the same shape.
def A(name, cpl, lvl, enh=None, lim=None, note=""):
    return {
        "attribute": name, "cost_per_level": cpl, "level": lvl,
        "enhancements": enh or [], "limiters": lim or [],
        "note": note,
    }


SPELL_CONVERSIONS: List[Dict[str, Any]] = [
    # ═══ Cantrips (level 0) — 10 entries ═══
    _entry("Dancing Lights", 0, "Evocation",
           "Up to four steerable motes of light for 1 minute; concentration.",
           [A("Control Environment (Light)", 1, 3,
              lim=[{"name": "Range: 100 ft", "value": -3},
                    {"name": "Concentration", "value": 1}])],
           3, "SRD 5.1 p.99"),
    _entry("Mage Hand", 0, "Conjuration",
           "Spectral hand manipulates objects up to 10 lb within 30 ft. 1 minute.",
           [A("Telekinesis", 4, 1,
              lim=[{"name": "Range: 30 ft", "value": -2},
                    {"name": "Only Light Objects (10 lb)", "value": 2}])],
           4, "SRD 5.1 p.113"),
    _entry("Fire Bolt", 0, "Evocation",
           "Ranged spell attack; 1d10 fire damage. Scales at L5/11/17.",
           [A("Weapon (Fire, 1d10)", 1, 3,
              lim=[{"name": "Range: 120 ft", "value": -3},
                    {"name": "Attack Roll to Hit", "value": 1}])],
           3, "SRD 5.1 p.104"),
    _entry("Minor Illusion", 0, "Illusion",
           "Sound or 5-ft image within 30 ft for 1 minute.",
           [A("Illusion (Sound or Sight)", 1, 2,
              lim=[{"name": "Range: 30 ft", "value": -2},
                    {"name": "One sensory mode only", "value": 2}])],
           4, "SRD 5.1 p.113"),
    _entry("Ray of Frost", 0, "Evocation",
           "Ranged spell attack for 1d8 cold; target's Speed −10 ft.",
           [A("Weapon (Cold, 1d8)", 1, 3,
              enh=[{"name": "Slow target −10 ft (1 round)", "value": -1}],
              lim=[{"name": "Range: 60 ft", "value": -2},
                    {"name": "Attack Roll to Hit", "value": 1}])],
           3, "SRD 5.1 p.122"),
    _entry("Sacred Flame", 0, "Evocation",
           "Target makes DEX save or takes 1d8 radiant; no cover benefit.",
           [A("Weapon (Radiant, 1d8)", 1, 3,
              lim=[{"name": "Range: 60 ft", "value": -2},
                    {"name": "DEX save for half", "value": 1},
                    {"name": "Ignores cover", "value": -1}])],
           3, "SRD 5.1 p.124"),
    _entry("Prestidigitation", 0, "Transmutation",
           "Minor magical tricks (flavour a drink, tidy soil, snuff flames, etc).",
           [A("Control Environment (Trivial)", 1, 1,
              lim=[{"name": "Range: 10 ft", "value": -1},
                    {"name": "Trivial effect only", "value": 2}])],
           2, "SRD 5.1 p.121"),
    _entry("Light", 0, "Evocation",
           "Touched object sheds 20 ft bright light / 20 ft dim for 1 hour.",
           [A("Illumination", 1, 2,
              lim=[{"name": "Touched object only", "value": 1},
                    {"name": "Duration 1 hour", "value": -1}])],
           2, "SRD 5.1 p.111"),
    _entry("Poison Spray", 0, "Conjuration",
           "Target within 10 ft makes CON save or takes 1d12 poison.",
           [A("Weapon (Poison, 1d12)", 1, 3,
              lim=[{"name": "Range: 10 ft", "value": -1},
                    {"name": "CON save negates", "value": 2}])],
           3, "SRD 5.1 p.121"),
    _entry("Vicious Mockery", 0, "Enchantment",
           "Target WIS save or takes 1d4 psychic + disadvantage on its next attack.",
           [A("Weapon (Psychic, 1d4)", 1, 1,
              enh=[{"name": "Imposes Disadvantage next attack", "value": -2}],
              lim=[{"name": "Range: 60 ft", "value": -2},
                    {"name": "WIS save negates", "value": 2}])],
           1, "SRD 5.1 p.137"),

    # ═══ 1st level — 10 entries ═══
    _entry("Magic Missile", 1, "Evocation",
           "Three darts of magical force; each 1d4+1 force; auto-hits.",
           [A("Weapon (Force, 1d4+1)", 1, 3,
              enh=[{"name": "Auto-Hit (no attack roll)", "value": -2},
                    {"name": "Spreading (3 darts)", "value": -1}],
              lim=[{"name": "Range: 120 ft", "value": -3}])],
           3, "SRD 5.1 p.113"),
    _entry("Cure Wounds", 1, "Evocation",
           "Touch heals 1d8+casting modifier HP. No effect on undead or constructs.",
           [A("Healing (+1d8 HP)", 1, 1)],
           1, "SRD 5.1 p.100"),
    _entry("Shield", 1, "Abjuration",
           "+5 AC until start of your next turn. Reaction.",
           [A("Defence (+5 AC)", 2, 1,
              lim=[{"name": "Reaction only", "value": 1},
                    {"name": "Duration: until next turn", "value": -1}])],
           2, "SRD 5.1 p.126"),
    _entry("Sleep", 1, "Enchantment",
           "5d8 HP worth of creatures fall unconscious in 20-ft radius (weakest first).",
           [A("Incapacitation (Unconscious)", 4, 1,
              enh=[{"name": "Area: 20 ft", "value": -2},
                    {"name": "Targets lowest-HP first", "value": -1}],
              lim=[{"name": "Capped at 5d8 HP of creatures", "value": 2}])],
           4, "SRD 5.1 p.128"),
    _entry("Thunderwave", 1, "Evocation",
           "15-ft cube; CON save or 2d8 thunder + pushed 10 ft.",
           [A("Weapon (Thunder, 2d8)", 1, 6,
              enh=[{"name": "Area: 15 ft", "value": -2},
                    {"name": "Push 10 ft", "value": -1}],
              lim=[{"name": "CON save for half + no push", "value": 2}])],
           6, "SRD 5.1 p.135"),
    _entry("Healing Word", 1, "Evocation",
           "Bonus action heal 1d4+casting mod at 60 ft.",
           [A("Healing (+1d4 HP)", 1, 1,
              enh=[{"name": "Bonus action", "value": -1},
                    {"name": "Range: 60 ft", "value": -2}])],
           1, "SRD 5.1 p.106"),
    _entry("Charm Person", 1, "Enchantment",
           "Humanoid WIS save or is charmed for 1 hour; awareness of charm after spell.",
           [A("Mind Control (Humanoids)", 4, 1,
              lim=[{"name": "WIS save negates", "value": 2},
                    {"name": "Humanoids only", "value": 1},
                    {"name": "Duration 1 hour", "value": -1}])],
           4, "SRD 5.1 p.95"),
    _entry("Bless", 1, "Enchantment",
           "Up to 3 creatures add 1d4 to attack rolls and saves for 1 minute.",
           [A("Combat Technique (+1d4 atk/save)", 2, 1,
              enh=[{"name": "Up to 3 targets", "value": -2}],
              lim=[{"name": "Concentration", "value": 1},
                    {"name": "Duration: 1 minute", "value": -1}])],
           2, "SRD 5.1 p.94"),
    _entry("Detect Magic", 1, "Divination",
           "Sense magic within 30 ft for 10 minutes; concentration.",
           [A("Sixth Sense (Magic)", 1, 2,
              lim=[{"name": "Range: 30 ft", "value": -2},
                    {"name": "Concentration", "value": 1}])],
           2, "SRD 5.1 p.101"),
    _entry("Feather Fall", 1, "Transmutation",
           "Up to 5 falling creatures descend at 60 ft/round; reaction.",
           [A("Flight (Glide)", 4, 1,
              enh=[{"name": "Up to 5 targets", "value": -2}],
              lim=[{"name": "Reaction only", "value": 1},
                    {"name": "Downward only", "value": 1}])],
           4, "SRD 5.1 p.103"),

    # ═══ 2nd level — 8 entries ═══
    _entry("Enlarge / Reduce", 2, "Transmutation",
           "Target grows or shrinks one size; advantage or disadvantage on STR checks.",
           [A("Size Change", 5, 1,
              enh=[{"name": "Potent (auto +/- one size)", "value": -2}],
              lim=[{"name": "Concentration", "value": 1},
                    {"name": "CON save resists", "value": 1}])],
           5, "SRD 5.1 p.102"),
    _entry("Hold Person", 2, "Enchantment",
           "Humanoid paralysed until it saves (end of each turn).",
           [A("Incapacitation (Paralysed)", 4, 2,
              lim=[{"name": "Humanoids only", "value": 1},
                    {"name": "WIS save ends each turn", "value": 2},
                    {"name": "Concentration", "value": 1}])],
           8, "SRD 5.1 p.108"),
    _entry("Invisibility", 2, "Illusion",
           "One creature invisible for 1 hour or until it attacks; concentration.",
           [A("Undetectable (Sight)", 1, 2,
              lim=[{"name": "Concentration", "value": 1},
                    {"name": "Ends on attack", "value": 1}])],
           4, "SRD 5.1 p.110"),
    _entry("Misty Step", 2, "Conjuration",
           "Bonus-action teleport up to 30 ft to a space you can see.",
           [A("Teleport", 4, 1,
              enh=[{"name": "Bonus action", "value": -2}],
              lim=[{"name": "Range: 30 ft", "value": -2},
                    {"name": "Line-of-sight only", "value": 1}])],
           4, "SRD 5.1 p.115"),
    _entry("Spiritual Weapon", 2, "Evocation",
           "Bonus-action summoned weapon 1d8+mod force; lasts 1 minute.",
           [A("Weapon (Force, 1d8+mod)", 1, 3,
              enh=[{"name": "Bonus action to attack", "value": -2},
                    {"name": "Ally-steered mobile source", "value": -1}],
              lim=[{"name": "Duration 1 minute", "value": -1},
                    {"name": "Attack roll still required", "value": 1}])],
           3, "SRD 5.1 p.129"),
    _entry("Mirror Image", 2, "Illusion",
           "Three duplicates divert attacks; each image has AC 10+DEX.",
           [A("Defence (Images)", 4, 1,
              enh=[{"name": "Three duplicates", "value": -2}],
              lim=[{"name": "Images burst when hit", "value": 2},
                    {"name": "Duration 1 minute", "value": -1}])],
           4, "SRD 5.1 p.113"),
    _entry("Web", 2, "Conjuration",
           "20-ft cube of sticky web; DEX save or restrained; concentration.",
           [A("Weapon (Restrain)", 1, 4,
              enh=[{"name": "Area: 20 ft cube", "value": -2},
                    {"name": "Difficult terrain", "value": -1}],
              lim=[{"name": "DEX save negates", "value": 2},
                    {"name": "Concentration 1 hour", "value": 1}])],
           4, "SRD 5.1 p.136"),
    _entry("Scorching Ray", 2, "Evocation",
           "Three 2d6 fire rays; each a separate ranged spell attack.",
           [A("Weapon (Fire, 2d6)", 1, 6,
              enh=[{"name": "Spreading (3 rays)", "value": -2}],
              lim=[{"name": "Range: 120 ft", "value": -3},
                    {"name": "Attack roll per ray", "value": 1}])],
           6, "SRD 5.1 p.124"),

    # ═══ 3rd level — 8 entries ═══
    _entry("Fireball", 3, "Evocation",
           "20-ft sphere at 150 ft; 8d6 fire; DEX save for half.",
           [A("Weapon (Fire, 8d6)", 1, 24,
              enh=[{"name": "Area: 20 ft sphere", "value": -2},
                    {"name": "Save (DEX) for half", "value": -4}],
              lim=[{"name": "Range: 150 ft", "value": -3}])],
           24, "SRD 5.1 p.104"),
    _entry("Counterspell", 3, "Abjuration",
           "Reaction; stop a spell of 3rd level or lower outright.",
           [A("Nullify (Magic)", 4, 3,
              enh=[{"name": "Reaction", "value": -1}],
              lim=[{"name": "Range: 60 ft", "value": -2},
                    {"name": "Single spell target", "value": 2}])],
           12, "SRD 5.1 p.98"),
    _entry("Dispel Magic", 3, "Abjuration",
           "End one magical effect within 120 ft.",
           [A("Nullify (Magic)", 4, 3,
              lim=[{"name": "Range: 100 ft", "value": -3},
                    {"name": "One effect at a time", "value": 2}])],
           20, "Anime 5E Spell Conversions (V6.4 seed)"),
    _entry("Fly", 3, "Transmutation",
           "Touched creature gains 60 ft fly speed for 10 minutes; concentration.",
           [A("Flight", 4, 2,
              lim=[{"name": "Touched target only", "value": 1},
                    {"name": "Concentration", "value": 1},
                    {"name": "Duration 10 minutes", "value": -1}])],
           8, "SRD 5.1 p.104"),
    _entry("Haste", 3, "Transmutation",
           "Target doubles speed, +2 AC, advantage on DEX saves, 1 extra attack.",
           [A("Combat Mastery (Accelerated)", 4, 2,
              enh=[{"name": "+2 AC", "value": -1},
                    {"name": "Extra action on turn", "value": -2}],
              lim=[{"name": "Concentration", "value": 1},
                    {"name": "Ends in lethargy", "value": 2}])],
           8, "SRD 5.1 p.105"),
    _entry("Lightning Bolt", 3, "Evocation",
           "100-ft line; 8d6 lightning; DEX save for half.",
           [A("Weapon (Lightning, 8d6)", 1, 24,
              enh=[{"name": "Line: 100 ft × 5 ft", "value": -2},
                    {"name": "Save (DEX) for half", "value": -4}])],
           24, "SRD 5.1 p.112"),
    _entry("Animate Dead", 3, "Necromancy",
           "Raise humanoid corpse as skeleton or zombie minion.",
           [A("Companion (Undead Minion)", 2, 3,
              lim=[{"name": "Humanoid corpse required", "value": 1},
                    {"name": "Daily command renewal", "value": 1}])],
           6, "SRD 5.1 p.92"),
    _entry("Revivify", 3, "Necromancy",
           "Bring a creature dead ≤ 1 minute back to life with 1 HP.",
           [A("Healing (Restore Life)", 4, 2,
              enh=[{"name": "Overcome Death (within 1 min)", "value": -2}],
              lim=[{"name": "Touched target", "value": 1},
                    {"name": "Consumes 300gp diamond", "value": 1}])],
           8, "SRD 5.1 p.123"),

    # ═══ 4th level — 6 entries ═══
    _entry("Greater Invisibility", 4, "Illusion",
           "Target invisible for 1 minute even through attacks; concentration.",
           [A("Undetectable (Sight)", 1, 2,
              enh=[{"name": "Persists through attacks", "value": -1}],
              lim=[{"name": "Concentration", "value": 1},
                    {"name": "Duration 1 min", "value": 1}])],
           3, "Anime 5E Spell Conversions (V6.4 seed)"),
    _entry("Wall of Fire", 4, "Evocation",
           "60-ft wall; 5d8 fire on entry / end of turn.",
           [A("Weapon (Fire, 5d8)", 1, 15,
              enh=[{"name": "Wall (60 ft)", "value": -2},
                    {"name": "Persistent area", "value": -1}],
              lim=[{"name": "Concentration 1 minute", "value": 1},
                    {"name": "Fixed placement", "value": 1}])],
           15, "SRD 5.1 p.135"),
    _entry("Banishment", 4, "Abjuration",
           "Target CHA save or banished to a harmless demiplane.",
           [A("Incapacitation (Banished)", 4, 2,
              lim=[{"name": "CHA save negates", "value": 2},
                    {"name": "Concentration 1 minute", "value": 1}])],
           8, "SRD 5.1 p.94"),
    _entry("Polymorph", 4, "Transmutation",
           "Creature transforms into beast ≤ CR equal to target; concentration.",
           [A("Alternate Form (Beast)", 8, 2,
              lim=[{"name": "WIS save resists", "value": 2},
                    {"name": "Concentration", "value": 1},
                    {"name": "CR limit equal to target's", "value": 1}])],
           16, "SRD 5.1 p.121"),
    _entry("Ice Storm", 4, "Evocation",
           "20-ft radius cylinder; 2d8 bludgeon + 4d6 cold; difficult terrain.",
           [A("Weapon (Cold + Bludgeon, 6d6)", 1, 18,
              enh=[{"name": "Area: 20-ft cylinder", "value": -2},
                    {"name": "Difficult terrain", "value": -1}],
              lim=[{"name": "DEX save for half", "value": 2}])],
           15, "SRD 5.1 p.108"),
    _entry("Stoneskin", 4, "Abjuration",
           "Resistance to nonmagical B/P/S damage for 1 hour; concentration.",
           [A("Armour (Physical)", 2, 4,
              enh=[{"name": "Damage Halved", "value": -2}],
              lim=[{"name": "Nonmagical B/P/S only", "value": 2},
                    {"name": "Concentration", "value": 1}])],
           8, "SRD 5.1 p.131"),

    # ═══ 5th-9th level — 10 entries ═══
    _entry("Telekinesis", 5, "Transmutation",
           "Move creatures/objects up to 1,000 lb within 60 ft; concentration.",
           [A("Telekinesis", 6, 4,
              enh=[{"name": "Up to 1,000 lb", "value": -2}],
              lim=[{"name": "Concentration 10 minutes", "value": 1}])],
           24, "SRD 5.1 p.133"),
    _entry("Wall of Force", 5, "Evocation",
           "Invisible, indestructible wall ≤ 10 sections × 10 ft.",
           [A("Defence (Wall)", 8, 3,
              enh=[{"name": "Force barrier", "value": -2},
                    {"name": "Large area", "value": -1}],
              lim=[{"name": "Concentration 10 min", "value": 1},
                    {"name": "Fixed placement", "value": 1}])],
           24, "SRD 5.1 p.135"),
    _entry("Dominate Person", 5, "Enchantment",
           "Humanoid WIS save or dominated; concentration 1 minute.",
           [A("Mind Control (Humanoid)", 4, 4,
              enh=[{"name": "Full control", "value": -2}],
              lim=[{"name": "WIS save resists", "value": 2},
                    {"name": "Concentration", "value": 1}])],
           16, "SRD 5.1 p.103"),
    _entry("Cone of Cold", 5, "Evocation",
           "60-ft cone; 8d8 cold; CON save for half.",
           [A("Weapon (Cold, 8d8)", 1, 32,
              enh=[{"name": "Cone: 60 ft", "value": -2},
                    {"name": "Save (CON) for half", "value": -4}])],
           32, "SRD 5.1 p.98"),
    _entry("Insect Plague", 5, "Conjuration",
           "20-ft sphere; 4d10 piercing; area persists; CON save half.",
           [A("Weapon (Piercing Swarm, 4d10)", 1, 10,
              enh=[{"name": "Area: 20 ft", "value": -2},
                    {"name": "Persistent (10 min)", "value": -1},
                    {"name": "Save (CON) for half", "value": -4}],
              lim=[{"name": "Range: 100 ft", "value": -3}])],
           12, "Anime 5E Spell Conversions (V6.4 seed)"),
    _entry("Move Earth", 6, "Transmutation",
           "Reshape 40-ft cube of soft earth for 2 hours; concentration.",
           [A("Telekinesis (Earth)", 6, 7,
              lim=[{"name": "Dirt/sand/clay only", "value": 1},
                    {"name": "Slow movement", "value": 3}])],
           24, "Anime 5E Spell Conversions (V6.4 seed)"),
    _entry("Disintegrate", 6, "Transmutation",
           "Single target; 10d6+40 force damage; reduced to dust on kill.",
           [A("Weapon (Force, 10d6+40)", 1, 75,
              enh=[{"name": "Reduce to ash on kill", "value": -2},
                    {"name": "Bypass normal objects", "value": -1}],
              lim=[{"name": "Single target", "value": 2},
                    {"name": "Range: 60 ft", "value": -2}])],
           75, "SRD 5.1 p.102"),
    _entry("Plane Shift", 7, "Conjuration",
           "Transport 8 willing creatures to a target plane.",
           [A("Portal", 1, 5,
              enh=[{"name": "Any plane of choice", "value": -2}],
              lim=[{"name": "Attuned focus required", "value": 1},
                    {"name": "Portal closes after use", "value": 1}])],
           5, "Anime 5E Spell Conversions (V6.4 seed)"),
    _entry("Control Weather", 8, "Transmutation",
           "Alter weather over 5 miles for 8 hours; 10-min cast.",
           [A("Control Environment (Weather)", 7, 3,
              enh=[{"name": "10-min activation", "value": 3}],
              lim=[{"name": "Area: 5 miles", "value": -6},
                    {"name": "Duration 8 hours", "value": -3},
                    {"name": "Gradual changes only", "value": 1}])],
           7, "Anime 5E Spell Conversions (V6.4 seed)"),
    _entry("Meteor Swarm", 9, "Evocation",
           "Four 40-ft spheres; 20d6 fire + 20d6 bludgeon each.",
           [A("Weapon (Fire+Bludgeon, 40d6)", 1, 60,
              enh=[{"name": "Save (DEX) for half", "value": -4}],
              lim=[{"name": "Area: 40 ft × 4", "value": -2},
                    {"name": "Range: 1 mile", "value": -5},
                    {"name": "Spreading: 4 sites", "value": -3}])],
           66, "Anime 5E Spell Conversions (V6.4 seed)"),

    # ═══ Class abilities (non-spell) — 10 entries ═══
    _entry("Barbarian: Rage", 1, "Class Feature",
           "+2 melee damage, resist B/P/S damage, advantage on STR checks.",
           [A("Combat Mastery (Rage)", 4, 1,
              enh=[{"name": "Dmg +2 / resist B/P/S", "value": -2}],
              lim=[{"name": "Activation: Bonus Action", "value": 1},
                    {"name": "Duration 1 min", "value": -1},
                    {"name": "N uses/day (class-tied)", "value": 1}])],
           4, "SRD 5.1 Barbarian p.11"),
    _entry("Fighter: Action Surge", 2, "Class Feature",
           "Once per short rest, take an additional action.",
           [A("Combat Mastery (Extra Action)", 6, 1,
              enh=[{"name": "Full extra action", "value": -2}],
              lim=[{"name": "Once per short rest", "value": 2}])],
           6, "SRD 5.1 Fighter p.12"),
    _entry("Monk: Flurry of Blows", 2, "Class Feature",
           "Bonus-action 2 unarmed strikes for 1 ki point.",
           [A("Combat Mastery (Flurry)", 4, 1,
              enh=[{"name": "Bonus action 2 strikes", "value": -2}],
              lim=[{"name": "1 Ki per use", "value": 1}])],
           4, "SRD 5.1 Monk p.15"),
    _entry("Paladin: Lay On Hands", 1, "Class Feature",
           "Pool of HP equal to 5× level; touch heal or cure disease.",
           [A("Healing (Pool)", 1, 5,
              enh=[{"name": "Cure disease", "value": -1}],
              lim=[{"name": "Pool (5×level)", "value": 2},
                    {"name": "Touch only", "value": 1}])],
           5, "SRD 5.1 Paladin p.17"),
    _entry("Ranger: Favoured Enemy", 1, "Class Feature",
           "Advantage on WIS-tracking and INT checks vs chosen enemy.",
           [A("Combat Technique (Study)", 2, 2,
              enh=[{"name": "Advantage on tracking", "value": -1}],
              lim=[{"name": "One creature type", "value": 1}])],
           4, "SRD 5.1 Ranger p.18"),
    _entry("Rogue: Sneak Attack", 1, "Class Feature",
           "+1d6 damage per level-tier on a PC with advantage or ally-adjacent.",
           [A("Weapon (Sneak Attack, +Xd6)", 1, 10,
              enh=[{"name": "Scales with level", "value": -2}],
              lim=[{"name": "Requires advantage or ally-adjacent", "value": 2},
                    {"name": "Finesse/ranged weapon", "value": 1}])],
           10, "SRD 5.1 Rogue p.20"),
    _entry("Warlock: Eldritch Blast", 0, "Class Feature",
           "Cantrip; 1d10 force beam; scales to multiple beams by level.",
           [A("Weapon (Force, 1d10)", 1, 3,
              enh=[{"name": "Additional beams at L5/11/17", "value": -2}],
              lim=[{"name": "Range: 120 ft", "value": -3},
                    {"name": "Attack roll", "value": 1}])],
           3, "SRD 5.1 Warlock p.23"),
    _entry("Druid: Wild Shape", 2, "Class Feature",
           "Transform into a beast of CR ≤ 1/2 level; duration = 1/2 level hours.",
           [A("Alternate Form (Beast)", 8, 2,
              enh=[{"name": "Multiple forms", "value": -2}],
              lim=[{"name": "CR gate", "value": 1},
                    {"name": "N uses / short rest", "value": 1}])],
           16, "SRD 5.1 Druid p.7"),
    _entry("Sorcerer: Metamagic — Quickened Spell", 3, "Class Feature",
           "Cast a 1-action spell as a bonus action (2 sorcery points).",
           [A("Combat Mastery (Metamagic)", 4, 1,
              enh=[{"name": "Bonus-action spell cast", "value": -2}],
              lim=[{"name": "2 Sorcery Points", "value": 1},
                    {"name": "1-action spells only", "value": 1}])],
           4, "SRD 5.1 Sorcerer p.20"),
    _entry("Cleric: Turn Undead", 2, "Class Feature",
           "Each undead within 30 ft WIS save or flees for 1 min.",
           [A("Incapacitation (Flee)", 4, 2,
              enh=[{"name": "Area: 30 ft", "value": -2}],
              lim=[{"name": "Undead only", "value": 1},
                    {"name": "WIS save negates", "value": 2}])],
           8, "SRD 5.1 Cleric p.6"),
]


SPELL_CONVERSION_SCHOOLS = sorted({r["school"] for r in SPELL_CONVERSIONS if r.get("school")})
